#!/usr/bin/env python3
"""Part 3: Generate remaining 5 disciplines + output final TypeScript file"""
import json, os

BASE = os.path.dirname(__file__)
with open(os.path.join(BASE, 'gen_disciplines_part2.json'), 'r', encoding='utf-8') as f:
    disciplines = json.load(f)

def make_discipline(did, dname, dnameEn, dicon, dcolor, ddesc, cats, formulas=None, standards=None):
    glossary = []
    for cat, terms in cats:
        for t in terms:
            glossary.append({"term": t[0], "termEn": t[1], "definition": t[2], "category": cat})
    return {"id": did, "name": dname, "nameEn": dnameEn, "icon": dicon, "color": dcolor,
            "description": ddesc, "glossary": glossary, "formulas": formulas or [], "standards": standards or []}

# ============================================================
# 9. 农学 Agriculture
# ============================================================
agri_cats = [
    ("作物科学", [
        ("作物","Crop","栽培的植物。"),
        ("粮食作物","Grain Crop","水稻小麦玉米等。"),
        ("经济作物","Cash Crop","棉花油菜甘蔗等。"),
        ("饲料作物","Forage Crop","饲喂动物的作物。"),
        ("绿肥作物","Green Manure Crop","改良土壤的作物。"),
        ("品种","Variety","作物的品种。"),
        ("杂交种","Hybrid","杂交后代。"),
        ("自交系","Inbred Line","自交纯化品系。"),
        ("育种","Breeding","培育新品种。"),
        ("分子育种","Molecular Breeding","分子水平的育种。"),
        ("转基因","Transgenic","基因转移技术。"),
        ("基因编辑","Gene Editing","CRISPR等技术。"),
        ("产量","Yield","单位面积产量。"),
        ("品质","Quality","作物品质。"),
        ("抗性","Resistance","抗病虫害能力。"),
        ("适应性","Adaptability","适应环境能力。"),
        ("生育期","Growth Period","从播种到成熟的时间。"),
        ("物候期","Phenological Phase","生长阶段。"),
        ("光合作用","Photosynthesis","光能转化有机物。"),
        ("呼吸作用","Respiration","有机物氧化分解释能。"),
    ]),
    ("土壤学", [
        ("土壤","Soil","地球表层松散物质。"),
        ("土壤质地","Soil Texture","砂粒粉粒粘粒比例。"),
        ("土壤结构","Soil Structure","土壤颗粒排列。"),
        ("土壤有机质","SOM","土壤中含碳有机物。"),
        ("土壤肥力","Soil Fertility","土壤供给养分的能力。"),
        ("土壤pH","Soil pH","土壤酸碱度。"),
        ("土壤养分","Soil Nutrients","氮磷钾等元素。"),
        ("氮磷钾","NPK","三大营养元素。"),
        ("微量元素","Micronutrient","铁锰锌铜硼钼。"),
        ("土壤微生物","Soil Microorganism","土壤中的微生物。"),
        ("土壤酶","Soil Enzyme","土壤中的酶类。"),
        ("土壤水分","Soil Moisture","土壤含水量。"),
        ("田间持水量","Field Capacity","土壤最大持水量。"),
        ("凋萎系数","Wilting Point","植物凋萎的含水量。"),
        ("土壤侵蚀","Soil Erosion","土壤流失。"),
        ("水土保持","Soil and Water Conservation","防止水土流失。"),
        ("盐碱化","Salinization","土壤盐分积累。"),
        ("沙漠化","Desertification","土地沙化。"),
        ("土壤改良","Soil Amendment","改善土壤性质。"),
        ("土壤污染","Soil Pollution","土壤有害物质。"),
    ]),
    ("植物保护", [
        ("病虫害","Pest and Disease","害虫和病害的总称。"),
        ("昆虫","Insect","六足节肢动物。"),
        ("害虫","Pest","危害作物的昆虫。"),
        ("天敌","Natural Enemy","捕食害虫的生物。"),
        ("病原菌","Pathogen","引起病害的微生物。"),
        ("真菌","Fungi","一类病原微生物。"),
        ("细菌","Bacteria","一类病原微生物。"),
        ("病毒","Virus","一类病原微生物。"),
        ("线虫","Nematode","一类病原生物。"),
        ("农药","Pesticide","防治病虫害的药剂。"),
        ("杀虫剂","Insecticide","杀灭害虫的药剂。"),
        ("杀菌剂","Fungicide","杀灭病菌的药剂。"),
        ("除草剂","Herbicide","杀灭杂草的药剂。"),
        ("生物防治","Biological Control","利用天敌防治。"),
        ("综合防治","IPM","综合多种方法防治。"),
        ("抗性管理","Resistance Management","延缓抗药性。"),
        ("农药残留","Pesticide Residue","农药在作物上的残留。"),
        ("绿色防控","Green Control","环保的防控方法。"),
        ("预测预报","Forecast","病虫害预测。"),
        ("检疫","Quarantine","防止病虫害传播。"),
    ]),
    ("园艺学", [
        ("果树","Fruit Tree","生产水果的树木。"),
        ("蔬菜","Vegetable","食用的植物器官。"),
        ("花卉","Flower","观赏植物。"),
        ("果树栽培","Fruit Cultivation","果树种植管理。"),
        ("蔬菜栽培","Vegetable Cultivation","蔬菜种植管理。"),
        ("设施园艺","Protected Horticulture","温室大棚等设施。"),
        ("温室","Greenhouse","控制环境的种植设施。"),
        ("大棚","Plastic Tunnel","塑料薄膜覆盖的设施。"),
        ("无土栽培","Soilless Culture","不用土壤的栽培。"),
        ("水培","Hydroponics","水溶液栽培。"),
        ("嫁接","Grafting","植物嫁接技术。"),
        ("扦插","Cutting","枝条扦插繁殖。"),
        ("组织培养","Tissue Culture","离体培养技术。"),
        ("修剪","Pruning","修整树形。"),
        ("疏花疏果","Thinning","去除多余花果。"),
        ("采收","Harvest","收获果实。"),
        ("保鲜","Preservation","延长保鲜期。"),
        ("采后处理","Postharvest Handling","采收后处理。"),
        ("观赏园艺","Ornamental Horticulture","观赏植物种植。"),
        ("景观园艺","Landscape Horticulture","园林景观设计。"),
    ]),
    ("畜牧兽医", [
        ("家畜","Livestock","饲养的动物。"),
        ("家禽","Poultry","鸡鸭鹅等。"),
        ("猪","Pig","主要家畜。"),
        ("牛","Cattle","奶牛肉牛。"),
        ("羊","Sheep/Goat","绵羊山羊。"),
        ("鸡","Chicken","主要家禽。"),
        ("饲料","Feed","动物食物。"),
        ("配合饲料","Compound Feed","多种原料配合。"),
        ("添加剂","Additive","饲料添加剂。"),
        ("饲养管理","Feeding Management","饲养的管理。"),
        ("繁殖","Reproduction","动物繁殖。"),
        ("人工授精","AI","人工授精技术。"),
        ("胚胎移植","Embryo Transfer","胚胎移植技术。"),
        ("育种","Breeding","动物品种改良。"),
        ("兽医","Veterinary","动物医学。"),
        ("疫苗","Vaccine","预防疾病的生物制品。"),
        ("免疫","Immunity","抗病能力。"),
        ("人畜共患病","Zoonosis","人畜共患的疾病。"),
        ("兽药","Veterinary Drug","动物用药品。"),
        ("动物福利","Animal Welfare","动物的健康福利。"),
    ]),
    ("农业工程", [
        ("农业机械化","Agricultural Mechanization","机械代替人力。"),
        ("拖拉机","Tractor","农业动力机械。"),
        ("收割机","Harvester","收获机械。"),
        ("播种机","Seeder","播种机械。"),
        ("灌溉","Irrigation","人工供水。"),
        ("滴灌","Drip Irrigation","逐滴供水。"),
        ("喷灌","Sprinkler Irrigation","喷洒供水。"),
        ("排水","Drainage","排除积水。"),
        ("农业航空","Agricultural Aviation","航空农业应用。"),
        ("精准农业","Precision Agriculture","信息技术精确管理。"),
        ("农业遥感","Agricultural Remote Sensing","遥感监测作物。"),
        ("农业物联网","Agricultural IoT","物联网农业应用。"),
        ("智慧农业","Smart Agriculture","AI驱动的农业。"),
        ("农业大数据","Agricultural Big Data","农业数据分析。"),
        ("农产品加工","Agricultural Product Processing","农产品深加工。"),
    ]),
    ("林业", [
        ("森林","Forest","大片树木。"),
        ("造林","Afforestation","种植森林。"),
        ("森林经营","Forest Management","森林管理。"),
        ("林业","Forestry","经营森林的产业。"),
        ("木材","Timber","树木材料。"),
        ("树种","Tree Species","树木种类。"),
        ("针叶林","Coniferous Forest","针叶树林。"),
        ("阔叶林","Broadleaf Forest","阔叶树林。"),
        ("混交林","Mixed Forest","混合树种林。"),
        ("森林火灾","Forest Fire","森林火灾。"),
        ("森林病虫害","Forest Pest","森林病虫危害。"),
        ("生态林业","Ecological Forestry","生态友好的林业。"),
        ("碳汇","Carbon Sink","森林固碳。"),
        ("生物多样性","Biodiversity","森林生物多样性。"),
        ("水土保持林","Soil Conservation Forest","水土保持的森林。"),
    ]),
    ("农业经济", [
        ("农业经济","Agricultural Economy","农业部门的经济。"),
        ("土地流转","Land Transfer","土地经营权流转。"),
        ("农业合作社","Agricultural Cooperative","农民合作组织。"),
        ("家庭农场","Family Farm","家庭经营的农场。"),
        ("农业保险","Agricultural Insurance","农业风险保障。"),
        ("农产品贸易","Agricultural Trade","农产品买卖。"),
        ("粮食安全","Food Security","粮食供给保障。"),
        ("农业补贴","Agricultural Subsidy","政府农业补贴。"),
        ("乡村振兴","Rural Revitalization","农村全面发展。"),
        ("脱贫攻坚","Poverty Alleviation","消除贫困。"),
        ("农业现代化","Agricultural Modernization","农业现代化进程。"),
        ("可持续农业","Sustainable Agriculture","可持续发展的农业。"),
        ("生态农业","Eco-Agriculture","生态友好的农业。"),
        ("有机农业","Organic Agriculture","无化学品的农业。"),
        ("循环农业","Circular Agriculture","资源循环利用。"),
    ]),
    ("水产养殖", [
        ("水产养殖","Aquaculture","水生生物养殖。"),
        ("鱼类","Fish","水生脊椎动物。"),
        ("虾蟹","Shrimp and Crab","甲壳类水生动物。"),
        ("贝类","Shellfish","软体动物。"),
        ("藻类","Algae","水生植物。"),
        ("鱼苗","Fry","幼鱼。"),
        ("饲料","Feed","水产饲料。"),
        ("水质","Water Quality","水体质量。"),
        ("溶氧","Dissolved Oxygen","水中溶解氧。"),
        ("pH值","pH","水体酸碱度。"),
        ("氨氮","Ammonia Nitrogen","水中氨氮含量。"),
        ("鱼病","Fish Disease","鱼类疾病。"),
        ("池塘养殖","Pond Culture","池塘养殖方式。"),
        ("网箱养殖","Cage Culture","网箱养殖方式。"),
        ("工厂化养殖","Intensive Culture","高密度工厂化养殖。"),
    ]),
]
agri_disc = make_discipline("agriculture", "农学", "Agriculture", "agr", "#558b2f",
    "研究农业生产、作物育种和农业资源的学科", agri_cats,
    formulas=[
        {"name": "光合效率", "formula": "η = (化学能 / 光能) × 100%", "description": "光合作用转化效率，通常1-2%", "unit": "%"},
        {"name": "施肥量", "formula": "F = (目标产量×需肥量 - 土壤供肥量) / 肥料利用率", "description": "推荐施肥量计算", "unit": "kg/亩"},
        {"name": "蒸腾速率", "formula": "E = k × (ei - ea) / (P × ra)", "description": "k=常数，ei=叶片内水汽压，ea=空气水汽压", "unit": "mmol·m⁻²·s⁻¹"},
        {"name": "作物水分利用效率", "formula": "WUE = 生物量(或产量) / 耗水量", "description": "单位水分产出", "unit": "kg/m³"},
    ],
    standards=[
        {"name": "绿色食品标准", "code": "NY/T 391", "description": "中国绿色食品产地环境质量标准。"},
        {"name": "种子检验规程", "code": "GB/T 3543", "description": "农作物种子检验的国家标准。"},
    ])
disciplines.append(agri_disc)
print(f"Agriculture: {len(agri_disc['glossary'])} terms")


# ============================================================
# 10. 医学 Medicine
# ============================================================
med_cats = [
    ("基础医学", [
        ("解剖学","Anatomy","研究人体结构的学科。"),
        ("组织学","Histology","研究组织的学科。"),
        ("胚胎学","Embryology","研究胚胎发育的学科。"),
        ("生理学","Physiology","研究人体功能的学科。"),
        ("病理学","Pathology","研究疾病的学科。"),
        ("病理生理学","Pathophysiology","研究疾病功能的学科。"),
        ("药理学","Pharmacology","研究药物作用的学科。"),
        ("免疫学","Immunology","研究免疫系统的学科。"),
        ("微生物学","Microbiology","研究微生物的学科。"),
        ("寄生虫学","Parasitology","研究寄生虫的学科。"),
        ("生物化学","Biochemistry","研究生物分子的学科。"),
        ("分子生物学","Molecular Biology","研究分子的生物学。"),
        ("遗传学","Genetics","研究遗传的学科。"),
        ("细胞生物学","Cell Biology","研究细胞的学科。"),
        ("神经生物学","Neurobiology","研究神经系统的学科。"),
        ("解剖位置","Anatomical Position","标准解剖体位。"),
        ("冠状面","Coronal Plane","将身体分前后两半的面。"),
        ("矢状面","Sagittal Plane","将身体分左右两半的面。"),
        ("横断面","Transverse Plane","将身体分上下两半的面。"),
        ("内侧外侧","Medial/Lateral","靠近远离正中面。"),
    ]),
    ("临床医学·内科", [
        ("心血管内科","Cardiology","心脏血管疾病科。"),
        ("呼吸内科","Pulmonology","呼吸系统疾病科。"),
        ("消化内科","Gastroenterology","消化系统疾病科。"),
        ("内分泌科","Endocrinology","内分泌疾病科。"),
        ("肾内科","Nephrology","肾脏疾病科。"),
        ("血液科","Hematology","血液疾病科。"),
        ("风湿免疫科","Rheumatology","风湿免疫疾病科。"),
        ("神经内科","Neurology","神经系统疾病科。"),
        ("感染科","Infectious Disease","感染性疾病科。"),
        ("肿瘤内科","Oncology","肿瘤疾病科。"),
        ("高血压","Hypertension","血压持续升高。"),
        ("冠心病","CHD","冠状动脉粥样硬化性心脏病。"),
        ("心力衰竭","Heart Failure","心脏泵血功能下降。"),
        ("心律失常","Arrhythmia","心跳节律异常。"),
        ("糖尿病","Diabetes","血糖升高的代谢病。"),
        ("慢阻肺","COPD","慢性阻塞性肺疾病。"),
        ("哮喘","Asthma","气道慢性炎症。"),
        ("肝硬化","Cirrhosis","肝脏纤维化。"),
        ("消化性溃疡","Peptic Ulcer","胃十二指肠溃疡。"),
        ("脑卒中","Stroke","脑血管意外。"),
    ]),
    ("临床医学·外科", [
        ("普通外科","General Surgery","一般外科。"),
        ("心胸外科","Cardiothoracic Surgery","心胸手术科。"),
        ("神经外科","Neurosurgery","脑脊髓手术科。"),
        ("骨科","Orthopedics","骨骼手术科。"),
        ("泌尿外科","Urology","泌尿系统手术科。"),
        ("烧伤整形","Burn and Plastic Surgery","烧伤整形科。"),
        ("麻醉学","Anesthesiology","麻醉学科。"),
        ("手术","Surgery","外科操作。"),
        ("微创手术","Minimally Invasive Surgery","小切口手术。"),
        ("腹腔镜","Laparoscopy","腹腔内窥镜手术。"),
        ("缝合","Suture","伤口缝合。"),
        ("引流","Drainage","排出体液。"),
        ("无菌术","Aseptic Technique","无菌操作。"),
        ("围手术期","Perioperative Period","手术前后时期。"),
        ("术后并发症","Postoperative Complication","手术后并发症。"),
        ("创伤","Trauma","物理损伤。"),
        ("骨折","Fracture","骨的断裂。"),
        ("脱位","Dislocation","关节面移位。"),
        ("疝","Hernia","组织突出。"),
        ("阑尾炎","Appendicitis","阑尾炎症。"),
    ]),
    ("临床医学·妇儿及其他", [
        ("妇产科","Obstetrics and Gynecology","女性生殖科。"),
        ("儿科","Pediatrics","儿童疾病科。"),
        ("眼科","Ophthalmology","眼部疾病科。"),
        ("耳鼻喉科","ENT","耳鼻喉疾病科。"),
        ("口腔科","Dentistry","口腔疾病科。"),
        ("皮肤科","Dermatology","皮肤疾病科。"),
        ("精神科","Psychiatry","精神疾病科。"),
        ("急诊科","Emergency Medicine","急救科。"),
        ("康复科","Rehabilitation","康复治疗科。"),
        ("老年科","Geriatrics","老年疾病科。"),
        ("妊娠","Pregnancy","怀孕。"),
        ("分娩","Delivery","生产。"),
        ("产前检查","Prenatal Check","孕期检查。"),
        ("新生儿","Newborn","出生后28天内。"),
        ("婴幼儿","Infant","0-3岁儿童。"),
        ("生长发育","Growth and Development","儿童生长。"),
        ("疫苗接种","Vaccination","预防接种。"),
        ("视力","Vision","视觉能力。"),
        ("听力","Hearing","听觉能力。"),
        ("口腔卫生","Oral Hygiene","口腔清洁。"),
    ]),
    ("护理学", [
        ("护理","Nursing","照护患者的专业。"),
        ("护理程序","Nursing Process","评估-诊断-计划-实施-评价。"),
        ("护理评估","Nursing Assessment","收集患者信息。"),
        ("护理诊断","Nursing Diagnosis","护理问题的判断。"),
        ("护理计划","Nursing Care Plan","护理方案制定。"),
        ("护理实施","Nursing Implementation","护理方案执行。"),
        ("护理评价","Nursing Evaluation","护理效果评价。"),
        ("SBAR交接","SBAR","结构化交接工具。"),
        ("NANDA诊断","NANDA-I","标准化护理诊断。"),
        ("循证护理","EBN","循证护理实践。"),
        ("基础护理","Basic Nursing","基础护理操作。"),
        ("专科护理","Specialty Nursing","专科护理操作。"),
        ("生命体征","Vital Signs","体温脉搏呼吸血压。"),
        ("体温","Temperature","体表温度。"),
        ("脉搏","Pulse","动脉搏动。"),
        ("呼吸","Respiration","呼吸频率。"),
        ("血压","Blood Pressure","动脉血压。"),
        ("疼痛评估","Pain Assessment","疼痛程度评估。"),
        ("压疮","Pressure Ulcer","压力性损伤。"),
        ("跌倒风险","Fall Risk","跌倒的危险性。"),
        ("静脉输液","IV Therapy","静脉输注液体。"),
        ("给药","Medication Administration","药物给予。"),
        ("伤口护理","Wound Care","伤口处理。"),
        ("管路护理","Catheter Care","管道护理。"),
        ("心理护理","Psychological Care","心理支持护理。"),
        ("健康教育","Health Education","健康知识教育。"),
        ("出院指导","Discharge Teaching","出院指导。"),
        ("临终关怀","Hospice Care","临终护理。"),
        ("护理伦理","Nursing Ethics","护理职业道德。"),
        ("护理管理","Nursing Management","护理行政管理。"),
    ]),
    ("预防医学与公共卫生", [
        ("预防医学","Preventive Medicine","疾病预防的医学。"),
        ("公共卫生","Public Health","人群健康的维护。"),
        ("流行病学","Epidemiology","疾病分布和决定因素的研究。"),
        ("环境卫生","Environmental Health","环境与健康。"),
        ("职业卫生","Occupational Health","职业与健康。"),
        ("营养学","Nutrition","营养与健康。"),
        ("食品卫生","Food Hygiene","食品安全。"),
        ("卫生统计","Health Statistics","卫生数据的统计。"),
        ("健康教育","Health Education","健康知识传播。"),
        ("妇幼保健","Maternal and Child Health","妇女儿童健康。"),
        ("传染病","Infectious Disease","传染性疾病。"),
        ("慢性病","Chronic Disease","慢性非传染性疾病。"),
        ("地方病","Endemic Disease","特定地区的疾病。"),
        ("职业病","Occupational Disease","职业相关的疾病。"),
        ("疫苗接种","Vaccination","预防接种。"),
        ("健康促进","Health Promotion","促进健康的活动。"),
        ("疾病监测","Disease Surveillance","疾病监测系统。"),
        ("突发公共卫生事件","Public Health Emergency","公共卫生紧急事件。"),
        ("三级预防","Three-Level Prevention","三级预防策略。"),
        ("筛查","Screening","早期发现疾病。"),
    ]),
    ("药学与中药学", [
        ("药物","Drug","治疗疾病的物质。"),
        ("药代动力学","Pharmacokinetics","药物在体内的过程。"),
        ("药效学","Pharmacodynamics","药物作用机制。"),
        ("处方","Prescription","医生开具的用药指示。"),
        ("药物相互作用","Drug Interaction","药物间的影响。"),
        ("不良反应","Adverse Reaction","药物的不良反应。"),
        ("耐药性","Drug Resistance","药物敏感性下降。"),
        ("中药","Traditional Chinese Medicine","传统中医药。"),
        ("方剂","Prescription","中药配方。"),
        ("中药药性","Property of TCM","中药的性能。"),
        ("四气五味","Four Properties Five Flavors","中药药性理论。"),
        ("归经","Meridian Tropism","药物作用部位。"),
        ("炮制","Processing","中药加工。"),
        ("中药化学","TCM Chemistry","中药化学成分。"),
        ("中药药理学","TCM Pharmacology","中药药理作用。"),
    ]),
    ("医学影像与检验", [
        ("X光","X-ray","X射线影像。"),
        ("CT","Computed Tomography","计算机断层扫描。"),
        ("MRI","Magnetic Resonance Imaging","磁共振成像。"),
        ("超声","Ultrasound","超声波影像。"),
        ("PET","Positron Emission Tomography","正电子发射断层。"),
        ("心电图","ECG","心脏电活动记录。"),
        ("脑电图","EEG","脑电活动记录。"),
        ("血常规","Blood Test","血液常规检查。"),
        ("尿常规","Urinalysis","尿液常规检查。"),
        ("生化检验","Biochemical Test","血液生化检查。"),
        ("免疫检验","Immunoassay","免疫学检查。"),
        ("微生物检验","Microbial Test","微生物检查。"),
        ("病理检验","Pathological Examination","病理学检查。"),
        ("基因检测","Genetic Testing","基因分析。"),
        ("分子诊断","Molecular Diagnostics","分子水平诊断。"),
    ]),
    ("医学伦理与法律", [
        ("医学伦理","Medical Ethics","医学道德规范。"),
        ("知情同意","Informed Consent","患者知情后同意。"),
        ("隐私保护","Privacy Protection","患者隐私保护。"),
        ("医疗事故","Medical Malpractice","医疗差错事故。"),
        ("安乐死","Euthanasia","无痛死亡。"),
        ("器官移植","Organ Transplantation","器官移植伦理。"),
        ("代孕","Surrogacy","代孕伦理。"),
        ("基因编辑伦理","Gene Editing Ethics","基因编辑的伦理问题。"),
        ("临床试验伦理","Clinical Trial Ethics","人体试验伦理。"),
        ("医疗资源分配","Healthcare Allocation","医疗资源公平分配。"),
    ]),
]
med_disc = make_discipline("medicine", "医学", "Medicine", "med", "#c62828",
    "研究人体健康、疾病预防、诊断和治疗的学科", med_cats,
    formulas=[
        {"name": "体表面积", "formula": "BSA = √(身高×体重/3600)", "description": "Mosteller公式", "unit": "m²"},
        {"name": "BMI", "formula": "BMI = 体重(kg) / 身高²(m)", "description": "体质指数，正常范围18.5-23.9", "unit": "kg/m²"},
        {"name": "肌酐清除率", "formula": "Ccr = ((140-年龄)×体重) / (72×血肌酐) × (0.85 if 女性)", "description": "Cockcroft-Gault公式", "unit": "mL/min"},
        {"name": "敏感度", "formula": "Se = TP / (TP + FN)", "description": "真阳性/(真阳性+假阴性)", "unit": "%"},
        {"name": "特异度", "formula": "Sp = TN / (TN + FP)", "description": "真阴性/(真阴性+假阳性)", "unit": "%"},
        {"name": "阳性预测值", "formula": "PPV = TP / (TP + FP)", "description": "阳性结果中真正患病的比例", "unit": "%"},
        {"name": "相对风险", "formula": "RR = (a/(a+b)) / (c/(c+d))", "description": "暴露组发病率/非暴露组发病率", "unit": "比值"},
    ],
    standards=[
        {"name": "中国药典", "code": "2025版", "description": "中国药品质量标准的法定依据。"},
        {"name": "疾病分类与代码", "code": "GB/T 14396 (ICD-10)", "description": "中国疾病分类国家标准，等同ICD-10。"},
    ])
disciplines.append(med_disc)
print(f"Medicine: {len(med_disc['glossary'])} terms")


# ============================================================
# 11. 管理学 Management
# ============================================================
mgmt_cats = [
    ("战略管理", [
        ("战略","Strategy","组织长期发展的总体谋划。"),
        ("战略管理","Strategic Management","战略制定执行评估的过程。"),
        ("SWOT分析","SWOT","优势劣势机会威胁分析。"),
        ("PEST分析","PEST","政治经济社会技术分析。"),
        ("波特五力","Porter's Five Forces","行业竞争分析。"),
        ("价值链","Value Chain","波特的价值创造模型。"),
        ("核心竞争力","Core Competence","独特难以模仿的能力。"),
        ("竞争优势","Competitive Advantage","超越竞争者的优势。"),
        ("蓝海战略","Blue Ocean Strategy","开创无竞争市场。"),
        ("红海战略","Red Ocean Strategy","在竞争激烈市场中竞争。"),
        ("多元化","Diversification","进入不同业务领域。"),
        ("垂直整合","Vertical Integration","产业链上下游整合。"),
        ("水平整合","Horizontal Integration","同行业整合。"),
        ("战略联盟","Strategic Alliance","企业间合作。"),
        ("并购","M&A","合并与收购。"),
        ("战略实施","Strategy Implementation","战略的执行。"),
        ("战略评估","Strategy Evaluation","战略效果的评估。"),
        ("使命","Mission","组织存在的目的。"),
        ("愿景","Vision","组织未来图景。"),
        ("价值观","Values","组织核心信念。"),
    ]),
    ("组织行为", [
        ("组织行为","Organizational Behavior","人在组织中的行为。"),
        ("激励","Motivation","激发行为的过程。"),
        ("马斯洛需求层次","Maslow's Hierarchy","五层需求理论。"),
        ("赫茨伯格双因素","Herzberg's Two Factors","保健因素和激励因素。"),
        ("期望理论","Expectancy Theory","弗鲁姆的激励理论。"),
        ("公平理论","Equity Theory","亚当斯的公平理论。"),
        ("目标设置","Goal Setting","洛克的目标理论。"),
        ("自我决定理论","SDT","自主胜任关联需要。"),
        ("组织文化","Organizational Culture","组织的价值观和规范。"),
        ("组织结构","Organizational Structure","组织的分工协调方式。"),
        ("领导","Leadership","影响他人达成目标的过程。"),
        ("变革型领导","Transformational Leadership","变革型领导风格。"),
        ("交易型领导","Transactional Leadership","交易型领导风格。"),
        ("魅力型领导","Charismatic Leadership","魅力型领导风格。"),
        ("服务型领导","Servant Leadership","服务型领导风格。"),
        ("团队","Team","协作的工作群体。"),
        ("冲突","Conflict","利益或目标不一致。"),
        ("沟通","Communication","信息传递交流。"),
        ("权力","Power","影响他人的能力。"),
        ("组织变革","Organizational Change","组织的变革过程。"),
    ]),
    ("运营管理", [
        ("运营管理","Operations Management","生产运营的管理。"),
        ("供应链","Supply Chain","从原料到客户的链条。"),
        ("库存管理","Inventory Management","库存的控制。"),
        ("质量管理","Quality Management","质量的管理。"),
        ("精益生产","Lean Production","消除浪费的生产方式。"),
        ("六西格玛","Six Sigma","减少缺陷的方法。"),
        ("流程再造","BPR","业务流程根本重新设计。"),
        ("瓶颈","Bottleneck","制约产能的环节。"),
        ("产能","Capacity","最大产出能力。"),
        ("排程","Scheduling","生产计划安排。"),
        ("MRP","Material Requirements Planning","物料需求计划。"),
        ("ERP","Enterprise Resource Planning","企业资源计划。"),
        ("JIT","Just-in-Time","准时制生产。"),
        ("看板","Kanban","拉动式生产信号。"),
        ("5S","5S","整理整顿清扫清洁素养。"),
        ("持续改进","Kaizen","持续改善。"),
        ("PDCA","PDCA","计划执行检查行动循环。"),
        ("流程","Process","一组相关活动。"),
        ("标准化","Standardization","统一规范。"),
        ("交付周期","Lead Time","从下单到交付的时间。"),
    ]),
    ("人力资源管理", [
        ("人力资源","Human Resources","组织的人力资本。"),
        ("招聘","Recruitment","吸引选择员工。"),
        ("选拔","Selection","评估选择候选人。"),
        ("培训","Training","员工能力提升。"),
        ("绩效管理","Performance Management","绩效的持续管理。"),
        ("薪酬管理","Compensation Management","薪酬体系管理。"),
        ("福利","Benefits","非工资报酬。"),
        ("职业发展","Career Development","员工职业成长。"),
        ("绩效评估","Performance Appraisal","绩效的评定。"),
        ("360度反馈","360 Feedback","多方位评价。"),
        ("KPI","Key Performance Indicator","关键绩效指标。"),
        ("OKR","Objectives and Key Results","目标与关键结果。"),
        ("胜任力","Competency","胜任岗位的能力。"),
        ("员工关系","Employee Relations","劳动关系的维护。"),
        ("员工敬业度","Employee Engagement","员工的投入程度。"),
        ("人才管理","Talent Management","核心人才的管理。"),
        ("继任计划","Succession Planning","接班人计划。"),
        ("组织发展","OD","组织变革与发展。"),
        ("人力资源规划","HR Planning","人力资源的需求规划。"),
        ("工作分析","Job Analysis","岗位内容的分析。"),
    ]),
    ("项目管理", [
        ("项目","Project","有始有终的独特任务。"),
        ("项目管理","Project Management","项目的计划执行控制。"),
        ("项目范围","Project Scope","项目的工作范围。"),
        ("项目时间","Project Time","项目的时间管理。"),
        ("项目成本","Project Cost","项目的费用管理。"),
        ("项目质量","Project Quality","项目的质量管理。"),
        ("项目风险","Project Risk","项目的风险管理。"),
        ("关键路径","Critical Path","决定项目工期的路径。"),
        ("甘特图","Gantt Chart","项目进度图表。"),
        ("WBS","Work Breakdown Structure","工作分解结构。"),
        ("敏捷项目管理","Agile Project Management","迭代敏捷的管理。"),
        ("瀑布模型","Waterfall Model","顺序项目管理。"),
        ("干系人","Stakeholder","项目相关方。"),
        ("里程碑","Milestone","项目的关键节点。"),
        ("基线","Baseline","项目的基准计划。"),
    ]),
    ("财务管理", [
        ("财务","Finance","资金的筹集使用分配。"),
        ("财务报表","Financial Statement","财务状况的报表。"),
        ("资产负债表","Balance Sheet","资产=负债+所有者权益。"),
        ("利润表","Income Statement","收入-费用=利润。"),
        ("现金流量表","Cash Flow Statement","现金的流入流出。"),
        ("财务分析","Financial Analysis","财务数据的分析。"),
        ("比率分析","Ratio Analysis","财务比率的分析。"),
        ("杜邦分析","DuPont Analysis","ROE的分解。"),
        ("净现值","NPV","现金流的现值。"),
        ("内部收益率","IRR","NPV=0的折现率。"),
        ("资本结构","Capital Structure","债务与股权的比例。"),
        ("资本成本","Cost of Capital","使用资本的成本。"),
        ("WACC","WACC","加权平均资本成本。"),
        ("营运资本","Working Capital","流动资产减流动负债。"),
        ("预算","Budget","收支计划。"),
        ("成本会计","Cost Accounting","成本的核算分析。"),
        ("审计","Audit","财务的审查。"),
        ("内部控制","Internal Control","内部的风险控制。"),
        ("投资","Investment","资金的投放。"),
        ("融资","Financing","资金的筹集。"),
    ]),
    ("市场营销", [
        ("营销","Marketing","创造传递价值的过程。"),
        ("市场","Market","买卖交易的场所。"),
        ("市场调研","Market Research","市场信息的收集分析。"),
        ("STP","Segmentation Targeting Positioning","细分目标定位。"),
        ("4P","Product Price Place Promotion","营销组合。"),
        ("4C","Customer Cost Convenience Communication","顾客导向组合。"),
        ("品牌","Brand","产品标识和形象。"),
        ("品牌资产","Brand Equity","品牌的价值。"),
        ("客户关系","CRM","客户关系管理。"),
        ("消费者行为","Consumer Behavior","消费者的购买行为。"),
        ("产品生命周期","Product Life Cycle","产品从上市到退出。"),
        ("定价","Pricing","价格的确定。"),
        ("渠道","Distribution","产品的流通途径。"),
        ("促销","Promotion","销售的促进活动。"),
        ("数字营销","Digital Marketing","数字化营销。"),
        ("社交媒体营销","Social Media Marketing","社交媒体的营销。"),
        ("内容营销","Content Marketing","内容的营销。"),
        ("搜索引擎优化","SEO","搜索引擎优化。"),
        ("客户细分","Customer Segmentation","客户群体的划分。"),
        ("净推荐值","NPS","客户推荐意愿度量。"),
    ]),
    ("创新与创业", [
        ("创新","Innovation","新想法的商业化。"),
        ("创造性破坏","Creative Destruction","熊彼特的概念。"),
        ("颠覆性创新","Disruptive Innovation","颠覆现有市场的创新。"),
        ("持续性创新","Sustaining Innovation","改进现有的创新。"),
        ("开放式创新","Open Innovation","利用外部资源的创新。"),
        ("设计思维","Design Thinking","以用户为中心的创新方法。"),
        ("精益创业","Lean Startup","最小可行产品的创业方法。"),
        ("商业模式","Business Model","价值创造的方式。"),
        ("商业模式画布","Business Model Canvas","商业模式分析工具。"),
        ("创业","Entrepreneurship","创建新企业。"),
        ("风险投资","Venture Capital","对初创企业的投资。"),
        ("天使投资","Angel Investment","早期个人投资。"),
        ("孵化器","Incubator","创业支持机构。"),
        ("加速器","Accelerator","创业加速机构。"),
        ("独角兽","Unicorn","估值超10亿美元的初创企业。"),
    ]),
    ("管理思想史", [
        ("科学管理","Scientific Management","泰勒的管理理论。"),
        ("行政管理","Administrative Management","法约尔的管理理论。"),
        ("科层制","Bureaucracy","韦伯的组织理论。"),
        ("霍桑实验","Hawthorne Studies","人际关系学派的起源。"),
        ("人际关系运动","Human Relations Movement","重视人的管理。"),
        ("决策理论","Decision Theory","西蒙的管理理论。"),
        ("系统理论","Systems Theory","将组织视为系统。"),
        ("权变理论","Contingency Theory","没有一成不变的管理。"),
        ("全面质量管理","TQM","全面的质量管理。"),
        ("学习型组织","Learning Organization","彼得·圣吉的理论。"),
    ]),
]
mgmt_disc = make_discipline("management", "管理学", "Management", "mgmt", "#ef6c00",
    "研究组织管理、决策优化和资源配置的学科", mgmt_cats,
    formulas=[
        {"name": "投资回报率", "formula": "ROI = (收益 - 成本) / 成本 × 100%", "description": "投资回报率", "unit": "%"},
        {"name": "净现值", "formula": "NPV = Σ CFₜ/(1+r)ᵗ - C₀", "description": "现金流折现减初始投资", "unit": "元"},
        {"name": "盈亏平衡点", "formula": "BEP = 固定成本 / (单价 - 单位变动成本)", "description": "收入等于成本的产量", "unit": "件"},
        {"name": "流动比率", "formula": "流动比率 = 流动资产 / 流动负债", "description": "短期偿债能力指标", "unit": "倍"},
        {"name": "杜邦分析", "formula": "ROE = 净利率 × 资产周转率 × 权益乘数", "description": "净资产收益率分解", "unit": "%"},
        {"name": "关键比率", "formula": "CR = (正常时间 - 实际时间) / 正常时间", "description": "工作评定系数", "unit": "无量纲"},
    ],
    standards=[
        {"name": "质量管理体系", "code": "ISO 9001:2015", "description": "国际质量管理标准。"},
        {"name": "项目管理标准", "code": "PMBOK Guide 7th", "description": "PMI项目管理知识体系指南第七版。"},
    ])
disciplines.append(mgmt_disc)
print(f"Management: {len(mgmt_disc['glossary'])} terms")


# ============================================================
# 12. 艺术学 Art
# ============================================================
art_cats = [
    ("艺术理论", [
        ("艺术","Art","创造性表达的产物。"),
        ("美学","Aesthetics","研究美的学科。"),
        ("审美","Aesthetics","对美的感受判断。"),
        ("艺术创作","Artistic Creation","创造艺术作品的过程。"),
        ("艺术欣赏","Art Appreciation","感受理解艺术。"),
        ("艺术批评","Art Criticism","评价分析艺术。"),
        ("艺术史","Art History","艺术发展的历史。"),
        ("艺术家","Artist","创造艺术的人。"),
        ("艺术品","Artwork","艺术创作的产物。"),
        ("艺术风格","Art Style","艺术的特征面貌。"),
        ("艺术流派","Art Movement","艺术思潮群体。"),
        ("形式","Form","艺术的外在结构。"),
        ("内容","Content","艺术的内在意义。"),
        ("主题","Theme","作品的核心思想。"),
        ("意象","Imagery","感性形象的意义。"),
        ("意境","Artistic Conception","情景交融的境界。"),
        ("表现","Expression","情感的表达。"),
        ("再现","Representation","现实的反映。"),
        ("象征","Symbol","以具体表抽象。"),
        ("隐喻","Metaphor","以彼物喻此物。"),
    ]),
    ("美术·绘画", [
        ("绘画","Painting","以颜料在平面上作画。"),
        ("素描","Sketch","单色绘画。"),
        ("油画","Oil Painting","油彩绘画。"),
        ("水彩","Watercolor","水彩颜料绘画。"),
        ("国画","Chinese Painting","中国传统绘画。"),
        ("壁画","Mural","墙壁绘画。"),
        ("版画","Printmaking","版面印刷的画。"),
        ("透视","Perspective","三维空间的平面表现。"),
        ("构图","Composition","画面的组织安排。"),
        ("色彩","Color","颜色的运用。"),
        ("色相","Hue","颜色的种类。"),
        ("明度","Value","颜色的明暗。"),
        ("饱和度","Saturation","颜色的纯度。"),
        ("色调","Tone","画面的整体色彩倾向。"),
        ("笔触","Brushwork","笔的痕迹。"),
        ("线条","Line","绘画的基本元素。"),
        ("明暗","Light and Shade","光影的表现。"),
        ("写实","Realism","如实描绘。"),
        ("抽象","Abstraction","非具象表现。"),
        ("写意","Freehand","中国画表现手法。"),
    ]),
    ("美术·雕塑与建筑", [
        ("雕塑","Sculpture","三维空间的艺术。"),
        ("圆雕","Sculpture in the Round","可从四面观看的雕塑。"),
        ("浮雕","Relief","附着于平面的雕塑。"),
        ("铸铜","Bronze Casting","铜铸造技术。"),
        ("石雕","Stone Carving","石材雕刻。"),
        ("木雕","Wood Carving","木材雕刻。"),
        ("建筑","Architecture","建筑的艺术。"),
        ("建筑设计","Architectural Design","建筑的设计。"),
        ("建筑风格","Architectural Style","建筑的特征。"),
        ("古典建筑","Classical Architecture","古希腊罗马建筑。"),
        ("哥特式","Gothic","尖拱肋拱建筑风格。"),
        ("巴洛克","Baroque","华丽动态的风格。"),
        ("现代主义建筑","Modernist Architecture","功能主义建筑。"),
        ("后现代建筑","Postmodern Architecture","多元折衷的建筑。"),
        ("中国古建筑","Chinese Architecture","中国传统建筑。"),
    ]),
    ("音乐", [
        ("音乐","Music","声音的艺术。"),
        ("旋律","Melody","音符的线性排列。"),
        ("和声","Harmony","同时发声的组合。"),
        ("节奏","Rhythm","音的长短强弱。"),
        ("音色","Timbre","声音的特色。"),
        ("音高","Pitch","声音的高低。"),
        ("音强","Dynamics","声音的强弱。"),
        ("调式","Mode","音阶的组织方式。"),
        ("大调","Major","大调式。"),
        ("小调","Minor","小调式。"),
        ("五声音阶","Pentatonic Scale","五声音阶。"),
        ("交响乐","Symphony","管弦乐作品。"),
        ("奏鸣曲","Sonata","多乐章器乐曲。"),
        ("协奏曲","Concerto","独奏与管弦乐协奏。"),
        ("室内乐","Chamber Music","小型合奏。"),
        ("歌剧","Opera","歌唱戏剧。"),
        ("民歌","Folk Music","民间歌曲。"),
        ("爵士乐","Jazz","即兴音乐风格。"),
        ("流行音乐","Pop Music","大众音乐。"),
        ("中国民乐","Chinese Folk Music","中国民族音乐。"),
    ]),
    ("戏剧与影视", [
        ("戏剧","Drama","舞台表演艺术。"),
        ("话剧","Spoken Drama","以对话为主的戏剧。"),
        ("戏曲","Chinese Opera","中国传统戏剧。"),
        ("京剧","Peking Opera","中国国粹。"),
        ("话剧表演","Acting","舞台表演。"),
        ("导演","Director","演出组织者。"),
        ("舞台美术","Stage Design","舞台视觉设计。"),
        ("剧本","Script","戏剧文本。"),
        ("独白","Monologue","独自说白。"),
        ("对白","Dialogue","对话说白。"),
        ("电影","Film/Cinema","影视艺术。"),
        ("蒙太奇","Montage","电影剪辑手法。"),
        ("长镜头","Long Take","不间断拍摄。"),
        ("景别","Shot Size","画面的大小。"),
        ("特写","Close-up","近距拍摄。"),
        ("空镜头","Establishing Shot","无人的景物镜头。"),
        ("平行剪辑","Parallel Editing","交替剪辑。"),
        ("场面调度","Mise-en-scène","画面内元素安排。"),
        ("电影类型","Film Genre","电影分类。"),
        ("纪录片","Documentary","纪实影片。"),
    ]),
    ("设计", [
        ("设计","Design","有目的的创造活动。"),
        ("平面设计","Graphic Design","二维视觉设计。"),
        ("工业设计","Industrial Design","产品设计。"),
        ("环境设计","Environmental Design","空间环境设计。"),
        ("视觉传达","Visual Communication","视觉信息传递。"),
        ("交互设计","Interaction Design","人机交互设计。"),
        ("用户体验","UX","用户使用体验。"),
        ("用户界面","UI","用户界面设计。"),
        ("字体设计","Typography","字体设计。"),
        ("色彩设计","Color Design","色彩方案设计。"),
        ("版式设计","Layout Design","版面排版设计。"),
        ("包装设计","Packaging Design","产品包装设计。"),
        ("品牌设计","Brand Design","品牌视觉设计。"),
        ("插画","Illustration","插图绘画。"),
        ("摄影","Photography","影像艺术。"),
    ]),
    ("艺术史与流派", [
        ("文艺复兴","Renaissance","14-16世纪艺术复兴。"),
        ("巴洛克","Baroque","17世纪华丽风格。"),
        ("洛可可","Rococo","18世纪装饰风格。"),
        ("新古典主义","Neoclassicism","回归古典的风格。"),
        ("浪漫主义","Romanticism","强调情感的流派。"),
        ("现实主义","Realism","如实描绘的流派。"),
        ("印象派","Impressionism","光色表现的流派。"),
        ("后印象派","Post-Impressionism","主观表现的流派。"),
        ("野兽派","Fauvism","色彩强烈的流派。"),
        ("立体派","Cubism","几何分解的流派。"),
        ("表现主义","Expressionism","扭曲表现的流派。"),
        ("超现实主义","Surrealism","探索潜意识的流派。"),
        ("抽象表现主义","Abstract Expressionism","抽象表现的流派。"),
        ("波普艺术","Pop Art","大众文化的流派。"),
        ("极简主义","Minimalism","极简形式的流派。"),
    ]),
    ("中国艺术", [
        ("山水画","Landscape Painting","中国山水画。"),
        ("花鸟画","Flower-Bird Painting","中国花鸟画。"),
        ("人物画","Figure Painting","中国人物画。"),
        ("工笔","Gongbi","工整细致的画法。"),
        ("写意","Xieyi","简练随意的画法。"),
        ("白描","Line Drawing","纯线条的画法。"),
        ("青绿山水","Blue-Green Landscape","青绿色调山水画。"),
        ("水墨画","Ink Wash","水墨写意画。"),
        ("书法","Calligraphy","汉字书写艺术。"),
        ("楷书","Regular Script","端正字体。"),
        ("行书","Running Script","行书字体。"),
        ("草书","Cursive Script","草书字体。"),
        ("隶书","Clerical Script","隶书字体。"),
        ("篆书","Seal Script","篆书字体。"),
        ("印章","Seal","篆刻艺术。"),
    ]),
    ("数字艺术", [
        ("数字艺术","Digital Art","数字技术创作的艺术。"),
        ("新媒体艺术","New Media Art","新媒体的艺术。"),
        ("互动艺术","Interactive Art","观众参与的艺术。"),
        ("影像艺术","Video Art","影像的艺术。"),
        ("装置艺术","Installation Art","空间装置的艺术。"),
        ("行为艺术","Performance Art","行为表演的艺术。"),
        ("概念艺术","Conceptual Art","以概念为核心的艺术。"),
        ("NFT艺术","NFT Art","区块链艺术。"),
        ("AI艺术","AI Art","人工智能艺术。"),
        ("生成艺术","Generative Art","算法生成的艺术。"),
    ]),
]
art_disc = make_discipline("art", "艺术学", "Art", "art", "#ad1457",
    "研究艺术创作、审美理论和艺术史的学科", art_cats,
    formulas=[
        {"name": "黄金比例", "formula": "φ = (1 + √5) / 2 ≈ 1.618", "description": "黄金分割比", "unit": "比值"},
        {"name": "色彩对比", "formula": "ΔE = √((ΔL)² + (Δa)² + (Δb)²)", "description": "Lab色彩空间中的色差", "unit": "ΔE"},
        {"name": "曝光三角", "formula": "EV = log₂(N²/t) = log₂(ISO × N² / (t × 100))", "description": "光圈(N)、快门(t)、感光度(ISO)的关系", "unit": "EV"},
    ],
    standards=[
        {"name": "色彩空间标准", "code": "sRGB / Adobe RGB", "description": "数字色彩的国际标准色彩空间。"},
        {"name": "印刷色彩标准", "code": "ISO 12647-2", "description": "胶印色彩管理的国际标准。"},
    ])
disciplines.append(art_disc)
print(f"Art: {len(art_disc['glossary'])} terms")


# ============================================================
# 13. 军事学 Military Science
# ============================================================
mil_cats = [
    ("军事理论", [
        ("战略","Strategy","指导战争全局的方略。"),
        ("战术","Tactics","指导和进行战斗的方法。"),
        ("战役","Campaign","介于战争与战斗之间的军事行动。"),
        ("战争","War","政治集团间的武装冲突。"),
        ("军事","Military","与武装力量相关的事务。"),
        ("国防","National Defense","国家的防务。"),
        ("军种","Branch of Service","陆海空等军种。"),
        ("兵种","Arm","军种内的专业分类。"),
        ("编制","Organization","军队的组织编制。"),
        ("装备","Equipment","武器装备。"),
        ("后勤","Logistics","军事保障。"),
        ("情报","Intelligence","军事信息。"),
        ("指挥","Command","军队指挥。"),
        ("通信","Communications","军事通信。"),
        ("电子战","Electronic Warfare","电磁领域作战。"),
    ]),
    ("军事思想史", [
        ("孙子兵法","The Art of War","孙武的兵学经典。"),
        ("克劳塞维茨","Clausewitz","《战争论》作者。"),
        ("若米尼","Jomini","《战争艺术概论》作者。"),
        ("马汉","Mahan","海权论提出者。"),
        ("杜黑","Douhet","制空权论提出者。"),
        ("毛泽东军事思想","Mao's Military Thought","人民战争理论。"),
        ("总体战","Total War","全面战争理论。"),
        ("机械化战争","Mechanized Warfare","机械化战争理论。"),
        ("核威慑","Nuclear Deterrence","核武器威慑理论。"),
        ("信息战","Information Warfare","信息时代战争理论。"),
    ]),
    ("军事技术", [
        ("武器","Weapon","用于战斗的工具。"),
        ("枪械","Firearm","轻武器。"),
        ("火炮","Artillery","炮兵武器。"),
        ("坦克","Tank","装甲战斗车辆。"),
        ("战斗机","Fighter","空中作战飞机。"),
        ("轰炸机","Bomber","轰炸飞机。"),
        ("军舰","Warship","海军舰艇。"),
        ("潜艇","Submarine","水下舰艇。"),
        ("导弹","Missile","制导武器。"),
        ("核武器","Nuclear Weapon","大规模杀伤性武器。"),
        ("生物武器","Biological Weapon","生物制剂武器。"),
        ("化学武器","Chemical Weapon","化学毒剂武器。"),
        ("无人机","UAV","无人驾驶飞行器。"),
        ("雷达","Radar","无线电探测。"),
        ("卫星","Satellite","军事卫星。"),
    ]),
    ("军事战略", [
        ("威慑","Deterrence","以实力阻止对方行动。"),
        ("核威慑","Nuclear Deterrence","以核武器威慑。"),
        ("常规威慑","Conventional Deterrence","以常规力量威慑。"),
        ("进攻","Offense","主动出击。"),
        ("防御","Defense","抵御进攻。"),
        ("反击","Counterattack","对进攻的回击。"),
        ("机动","Maneuver","快速移动以占据有利位置。"),
        ("包围","Encirclement","围困敌方。"),
        ("迂回","Flanking","从侧翼攻击。"),
        ("穿插","Penetration","插入敌方纵深。"),
        ("闪击战","Blitzkrieg","快速突击战术。"),
        ("消耗战","War of Attrition","消耗对方实力。"),
        ("游击战","Guerrilla Warfare","小规模骚扰战术。"),
        ("人民战争","People's War","全民参与的战争。"),
        ("不对称作战","Asymmetric Warfare","以弱胜强的战法。"),
    ]),
    ("现代战争形态", [
        ("信息化战争","Informationized Warfare","以信息为主导的战争。"),
        ("网络战","Cyber Warfare","网络空间作战。"),
        ("太空战","Space Warfare","太空领域作战。"),
        ("认知战","Cognitive Warfare","认知领域的作战。"),
        ("混合战争","Hybrid Warfare","多种手段混合的战争。"),
        ("代理人战争","Proxy War","通过第三方进行的战争。"),
        ("反恐战争","War on Terror","反恐军事行动。"),
        ("维和行动","Peacekeeping","联合国维和行动。"),
        ("联合行动","Joint Operations","多军种协同作战。"),
        ("全域作战","All-Domain Operations","跨域协同作战。"),
    ]),
    ("军事制度与法规", [
        ("兵役制度","Conscription System","征兵制度。"),
        ("义务兵役","Conscription","强制兵役。"),
        ("志愿兵役","Volunteer Service","自愿兵役。"),
        ("军衔","Military Rank","军人等级。"),
        ("军法","Military Law","军事法规。"),
        ("日内瓦公约","Geneva Conventions","国际人道法。"),
        ("战争法","Law of War","规范战争的法规。"),
        ("中立法","Law of Neutrality","中立国法规。"),
        ("军事法庭","Military Court","军事审判机构。"),
        ("退役军人","Veteran","退出现役的军人。"),
    ]),
    ("军事地理与历史", [
        ("军事地理","Military Geography","地理与军事的关系。"),
        ("地形","Terrain","地表形态。"),
        ("气候","Climate","气候对军事的影响。"),
        ("制海权","Command of the Sea","海上控制权。"),
        ("制空权","Command of the Air","空中控制权。"),
        ("制天权","Command of Space","太空控制权。"),
        ("制信息权","Information Dominance","信息控制权。"),
        ("战略要地","Strategic Point","具有重要战略意义的地点。"),
        ("军事基地","Military Base","军事设施。"),
        ("军事同盟","Military Alliance","军事联盟。"),
    ]),
]
mil_disc = make_discipline("military", "军事学", "Military Science", "mil", "#263238",
    "研究战争规律、军事组织和军事技术的学科", mil_cats,
    formulas=[
        {"name": "兰彻斯特平方律", "formula": "dR/dt = -α·B, dB/dt = -β·R", "description": "现代战争中战斗力与数量平方成正比", "unit": "兵力"},
        {"name": "侦察覆盖", "formula": "C = Aₛ / A_total × 100%", "description": "侦察面积/总面积", "unit": "%"},
    ],
    standards=[
        {"name": "国防标准体系", "code": "GJB", "description": "中国国家军用标准。"},
        {"name": "北约标准化协议", "code": "STANAG", "description": "北约成员国军事标准。"},
    ])
disciplines.append(mil_disc)
print(f"Military: {len(mil_disc['glossary'])} terms")


# ============================================================
# Output final TypeScript file
# ============================================================
OUTPUT = os.path.join(BASE, 'frontend', 'src', 'data', 'disciplines.ts')

with open(OUTPUT, 'w', encoding='utf-8') as f:
    f.write('/**\n')
    f.write(' * Selenyx 全学科数据集 —— 按中国学科门类覆盖\n')
    f.write(f' * R83: 深度扩展至 {len(disciplines)} 个学科门类，共 {sum(len(d["glossary"]) for d in disciplines)} 个术语\n')
    f.write(' * 不依赖后端，全部内置在前端\n')
    f.write(' */\n\n')

    f.write('export interface DisciplineGlossary {\n')
    f.write('  term: string;\n  termEn: string;\n  definition: string;\n  category: string;\n}\n\n')
    f.write('export interface DisciplineFormula {\n  name: string;\n  formula: string;\n  description: string;\n  unit?: string;\n  reference?: string;\n}\n\n')
    f.write('export interface DisciplineStandard {\n  name: string;\n  code: string;\n  description: string;\n}\n\n')
    f.write('export interface Discipline {\n')
    f.write('  id: string;\n  name: string;\n  nameEn: string;\n  icon: string;\n  color: string;\n  description: string;\n  glossary: DisciplineGlossary[];\n  formulas: DisciplineFormula[];\n  standards: DisciplineStandard[];\n}\n\n')

    f.write('export const DISCIPLINES: Discipline[] = [\n')

    for idx, d in enumerate(disciplines):
        f.write(f'  // ========== {idx+1}. {d["name"]} {d["nameEn"]} ==========\n')
        f.write('  {\n')
        f.write(f'    id: {json.dumps(d["id"])}, name: {json.dumps(d["name"])}, nameEn: {json.dumps(d["nameEn"])},\n')
        f.write(f'    icon: {json.dumps(d["icon"])}, color: {json.dumps(d["color"])},\n')
        f.write(f'    description: {json.dumps(d["description"])},\n')
        f.write('    glossary: [\n')
        for g in d["glossary"]:
            # Handle both dict (from make_discipline) and list (from JSON-serialized tuples)
            if isinstance(g, dict):
                t, te, df, cat = g["term"], g["termEn"], g["definition"], g["category"]
            else:
                t, te, df, cat = g[0], g[1], g[2], g[3]
            f.write(f'      {{ term: {json.dumps(t)}, termEn: {json.dumps(te)}, definition: {json.dumps(df)}, category: {json.dumps(cat)} }},\n')
        f.write('    ],\n')
        f.write('    formulas: [\n')
        for fo in d["formulas"]:
            unit_str = f', unit: {json.dumps(fo["unit"])}' if "unit" in fo else ""
            ref_str = f', reference: {json.dumps(fo["reference"])}' if "reference" in fo else ""
            f.write(f'      {{ name: {json.dumps(fo["name"])}, formula: {json.dumps(fo["formula"])}, description: {json.dumps(fo["description"])}{unit_str}{ref_str} }},\n')
        f.write('    ],\n')
        f.write('    standards: [\n')
        for s in d["standards"]:
            f.write(f'      {{ name: {json.dumps(s["name"])}, code: {json.dumps(s["code"])}, description: {json.dumps(s["description"])} }},\n')
        f.write('    ],\n')
        f.write('  },\n\n')

    f.write('];\n')

print(f"\n✅ Final TypeScript file written to {OUTPUT}")
print(f"   Total: {len(disciplines)} disciplines, {sum(len(d['glossary']) for d in disciplines)} terms")
for d in disciplines:
    print(f"   {d['name']:6s}: {len(d['glossary']):4d} terms ({len(d['formulas'])} formulas, {len(d['standards'])} standards)")
