#!/usr/bin/env python3
"""
Generate disciplines.ts with 500+ glossary terms per discipline.
13 disciplines × 500+ terms = 6500+ terms total.
Outputs to frontend/src/data/disciplines.ts
"""
import json, os

OUTPUT = os.path.join(os.path.dirname(__file__), 'frontend', 'src', 'data', 'disciplines.ts')

# Helper: each discipline has (id, name, nameEn, icon, color, description, glossary[], formulas[], standards[])
# glossary entry: (term, termEn, definition, category)

disciplines = []

# ============================================================
# 1. 哲学 Philosophy
# ============================================================
phil_glossary = []
# --- 中国哲学·先秦儒家 ---
confucian = [
    ("仁","Ren","儒家核心概念，指人与人之间的关爱与同情。","中国哲学·儒家"),
    ("义","Yi","正当、合理的行为准则和道德规范。","中国哲学·儒家"),
    ("礼","Li","社会规范、礼仪制度及行为准则的总称。","中国哲学·儒家"),
    ("智","Zhi","辨别是非善恶的智慧和道德认知。","中国哲学·儒家"),
    ("信","Xin","诚实不欺、遵守诺言的品德。","中国哲学·儒家"),
    ("忠","Zhong","尽心竭力、忠诚无私的态度。","中国哲学·儒家"),
    ("恕","Shu","推己及人、己所不欲勿施于人。","中国哲学·儒家"),
    ("孝","Xiao","子女对父母的敬爱与赡养。","中国哲学·儒家"),
    ("悌","Ti","弟弟对兄长的敬爱。","中国哲学·儒家"),
    ("君子","Junzi","儒家理想人格，具备仁德修养的人。","中国哲学·儒家"),
    ("小人","Xiaoren","缺乏道德修养、唯利是图的人。","中国哲学·儒家"),
    ("中庸","Zhongyong","不偏不倚、无过无不及的处事原则。","中国哲学·儒家"),
    ("慎独","Shendu","独处时仍能严守道德自律。","中国哲学·儒家"),
    ("格物","Gewu","探究事物的道理。","中国哲学·儒家"),
    ("致知","Zhizhi","通过格物达到对事物的认知。","中国哲学·儒家"),
    ("诚意","Chengyi","使意念真实无妄。","中国哲学·儒家"),
    ("正心","Zhengxin","使心端正无偏。","中国哲学·儒家"),
    ("修身","Xiushen","提高自身的道德修养。","中国哲学·儒家"),
    ("齐家","Qijia","管理好家庭和家族。","中国哲学·儒家"),
    ("治国","Zhiguo","治理好国家。","中国哲学·儒家"),
    ("平天下","Ping Tianxia","使天下太平。","中国哲学·儒家"),
    ("内圣外王","Nei Sheng Wai Wang","内在圣德与外在王道的统一。","中国哲学·儒家"),
    ("王道","Wangdao","以德服人、以仁治国的政治理想。","中国哲学·儒家"),
    ("霸道","Badao","以力服人、以功利治国的政治方式。","中国哲学·儒家"),
    ("天命","Tianming","上天赋予的使命或命运。","中国哲学·儒家"),
    ("性善论","Xing Shan Lun","孟子主张人性本善。","中国哲学·儒家"),
    ("性恶论","Xing E Lun","荀子主张人性本恶需要教化。","中国哲学·儒家"),
    ("四端","Si Duan","孟子提出的恻隐、羞恶、辞让、是非之心。","中国哲学·儒家"),
    ("五伦","Wu Lun","君臣、父子、夫妇、兄弟、朋友五种人伦关系。","中国哲学·儒家"),
    ("经世致用","Jingshi Zhiyong","学问须用于治理国家和社会。","中国哲学·儒家"),
    ("理学","Lixue","宋明以理为本体的哲学流派。","中国哲学·理学"),
    ("心学","Xinxue","以心为本体的哲学流派，陆九渊王阳明为代表。","中国哲学·理学"),
    ("致良知","Zhi Liangzhi","王阳明核心思想，发挥本心的良知。","中国哲学·理学"),
    ("知行合一","Zhi Xing He Yi","王阳明主张知与行不可分离。","中国哲学·理学"),
    ("存天理灭人欲","Cun Tianli Mie Renyu","朱熹主张克制私欲以存天理。","中国哲学·理学"),
    ("理气论","Li Qi Lun","朱熹关于理与气关系的本体论。","中国哲学·理学"),
    ("心即理","Xin Ji Li","陆王心学主张心与理同一。","中国哲学·理学"),
    ("格物致知","Gewu Zhizhi","《大学》八条目之首，探究事物以获得知识。","中国哲学·理学"),
    ("太极","Taiji","宇宙万物本原的哲学概念。","中国哲学·理学"),
    ("阴阳","Yin Yang","宇宙间对立统一的两股力量。","中国哲学·理学"),
    ("道统","Daotong","儒家道义传承的统绪。","中国哲学·理学"),
]
phil_glossary.extend(confucian)

# --- 中国哲学·道家 ---
taoist = [
    ("道","Dao","道家核心概念，宇宙万物的本原和运行规律。","中国哲学·道家"),
    ("德","De","道在万物中的体现，事物的本性。","中国哲学·道家"),
    ("无为","Wuwei","顺其自然不妄为的处事方式。","中国哲学·道家"),
    ("自然","Ziran","事物本来的状态，不受外力干预。","中国哲学·道家"),
    ("逍遥","Xiaoyao","精神自由无拘无束的境界。","中国哲学·道家"),
    ("齐物","Qiwu","万物平等无差别的观点。","中国哲学·道家"),
    ("心斋","Xinzhai","心志清虚以体道的方法。","中国哲学·道家"),
    ("坐忘","Zuowang","物我两忘与道合一的境界。","中国哲学·道家"),
    ("气","Qi","构成万物的精微物质。","中国哲学·道家"),
    ("有","You","存在、实有。","中国哲学·道家"),
    ("无","Wu","不存在、虚空。","中国哲学·道家"),
    ("虚","Xu","空虚、虚静。","中国哲学·道家"),
    ("静","Jing","安静、宁静。","中国哲学·道家"),
    ("反者道之动","Fan Zhe Dao Zhi Dong","事物发展到极点必然向反面转化。","中国哲学·道家"),
    ("上善若水","Shang Shan Ruo Shui","最高境界的善如同水一样。","中国哲学·道家"),
    ("大器晚成","Da Qi Wan Cheng","大才之人需长期磨炼方成。","中国哲学·道家"),
    ("知足不辱","Zhi Zu Bu Ru","知足的人不会遭受耻辱。","中国哲学·道家"),
    ("柔弱胜刚强","Rouruo Sheng Gangqiang","柔弱能战胜刚强。","中国哲学·道家"),
    ("天人合一","Tian Ren He Yi","人与自然和谐统一的境界。","中国哲学·道家"),
    ("道法自然","Dao Fa Ziran","道效法自然规律。","中国哲学·道家"),
]
phil_glossary.extend(taoist)

# --- 中国哲学·法家墨家名家 ---
legalist = [
    ("法","Fa","法家核心概念，法律和制度。","中国哲学·法家"),
    ("术","Shu","君主驾驭臣下的权术。","中国哲学·法家"),
    ("势","Shi","君主的权威和地位。","中国哲学·法家"),
    ("耕战","Geng Zhan","重农抑商、奖励军功的政策。","中国哲学·法家"),
    ("以法治国","Yi Fa Zhi Guo","用法律治理国家。","中国哲学·法家"),
    ("兼爱","Jian Ai","墨家主张无差别的爱。","中国哲学·墨家"),
    ("非攻","Fei Gong","墨家反对侵略战争。","中国哲学·墨家"),
    ("尚贤","Shang Xian","墨家主张任用贤能。","中国哲学·墨家"),
    ("尚同","Shang Tong","墨家主张思想统一。","中国哲学·墨家"),
    ("节用","Jie Yong","墨家主张节约开支。","中国哲学·墨家"),
    ("节葬","Jie Zang","墨家主张薄葬。","中国哲学·墨家"),
    ("天志","Tian Zhi","墨家主张天有意志。","中国哲学·墨家"),
    ("明鬼","Ming Gui","墨家主张鬼神存在。","中国哲学·墨家"),
    ("非命","Fei Ming","墨家反对命定论。","中国哲学·墨家"),
    ("白马非马","Bai Ma Fei Ma","公孙龙的名辩命题。","中国哲学·名家"),
    ("离坚白","Li Jian Bai","公孙龙关于属性分离的命题。","中国哲学·名家"),
    ("合同异","He Tong Yi","惠施关于同异的辩证命题。","中国哲学·名家"),
]
phil_glossary.extend(legalist)

# --- 中国哲学·佛学 ---
buddhism_cn = [
    ("空","Kong","佛教核心概念，万物无自性。","中国哲学·佛学"),
    ("色","Se","物质现象的总称。","中国哲学·佛学"),
    ("色即是空","Se Ji Shi Kong","物质现象本质为空。","中国哲学·佛学"),
    ("缘起","Yuan Qi","万物因缘和合而生。","中国哲学·佛学"),
    ("涅槃","Nie Pan","熄灭烦恼、超越生死轮回的境界。","中国哲学·佛学"),
    ("般若","Bo Re","通达诸法实相的智慧。","中国哲学·佛学"),
    ("禅","Chan","冥想、静虑的修行方法。","中国哲学·佛学"),
    ("顿悟","Dun Wu","瞬间觉悟真理。","中国哲学·佛学"),
    ("渐悟","Jian Wu","逐步修行觉悟。","中国哲学·佛学"),
    ("明心见性","Ming Xin Jian Xing","禅宗核心，直指本心见本性。","中国哲学·佛学"),
    ("一花一世界","Yi Hua Yi Shi Jie","微观中包含宏观的哲学意涵。","中国哲学·佛学"),
    ("业力","Ye Li","行为产生的因果力量。","中国哲学·佛学"),
    ("轮回","Lun Hui","生死流转的循环。","中国哲学·佛学"),
    ("慈悲","Ci Bei","慈与悲，给予安乐与拔除痛苦。","中国哲学·佛学"),
]
phil_glossary.extend(buddhism_cn)

# --- 西方哲学·古希腊 ---
greek = [
    ("理念论","Theory of Ideas","柏拉图主张真实存在的是永恒不变的理念。","西方哲学·古希腊"),
    ("洞穴比喻","Allegory of the Cave","柏拉图比喻人类认知如洞穴中的囚徒。","西方哲学·古希腊"),
    ("四因说","Four Causes","亚里士多德提出质料因、形式因、动力因、目的因。","西方哲学·古希腊"),
    ("第一哲学","First Philosophy","亚里士多德对形而上学的称呼。","西方哲学·古希腊"),
    ("实体","Substance","亚里士多德哲学中的根本存在。","西方哲学·古希腊"),
    ("潜能与现实","Potentiality and Actuality","亚里士多德关于事物发展的概念。","西方哲学·古希腊"),
    ("黄金中道","Golden Mean","亚里士多德伦理学中适度为德。","西方哲学·古希腊"),
    ("智者学派","Sophists","古希腊以教授修辞和论辩为业的学派。","西方哲学·古希腊"),
    ("逻各斯","Logos","理性、规律、话语的多重含义。","西方哲学·古希腊"),
    ("努斯","Nous","心灵、理性的哲学概念。","西方哲学·古希腊"),
    ("泰勒斯","Thales","西方哲学之父，认为水是万物的本原。","西方哲学·古希腊"),
    ("赫拉克利特","Heraclitus","认为万物处于永恒变化中。","西方哲学·古希腊"),
    ("巴门尼德","Parmenides","认为存在是不变的。","西方哲学·古希腊"),
    ("德谟克利特","Democritus","原子论创始人。","西方哲学·古希腊"),
    ("苏格拉底方法","Socratic Method","通过提问引导对方发现真理的辩证法。","西方哲学·古希腊"),
    ("柏拉图主义","Platonism","以理念论为核心的哲学体系。","西方哲学·古希腊"),
    ("逍遥学派","Peripatetic School","亚里士多德创立的学派。","西方哲学·古希腊"),
    ("犬儒学派","Cynicism","主张简朴生活、蔑视世俗的学派。","西方哲学·古希腊"),
    ("斯多葛学派","Stoicism","主张理性控制情感、顺应自然的学派。","西方哲学·古希腊"),
    ("伊壁鸠鲁学派","Epicureanism","追求心灵宁静的快乐主义学派。","西方哲学·古希腊"),
    ("怀疑学派","Pyrrhonism","对一切判断悬置的学派。","西方哲学·古希腊"),
    ("美德即知识","Virtue is Knowledge","苏格拉底主张道德与知识统一。","西方哲学·古希腊"),
    ("灵魂三分说","Tripartite Soul","柏拉图将灵魂分为理性、激情、欲望。","西方哲学·古希腊"),
    ("理想国","Republic","柏拉图关于正义城邦的著作。","西方哲学·古希腊"),
    ("形而上学","Metaphysics","研究存在本质的哲学分支。","西方哲学·古希腊"),
]
phil_glossary.extend(greek)

# --- 西方哲学·中世纪与近代 ---
medieval_modern = [
    ("经院哲学","Scholasticism","中世纪以理性论证信仰的哲学。","西方哲学·中世纪"),
    ("上帝存在证明","Proofs of God","安瑟伦和托马斯·阿奎那的上帝存在论证。","西方哲学·中世纪"),
    ("唯名论","Nominalism","主张共相只是名称而非实在。","西方哲学·中世纪"),
    ("唯实论","Realism","主张共相独立存在。","西方哲学·中世纪"),
    ("文艺复兴","Renaissance","14-16世纪欧洲思想文化运动。","西方哲学·中世纪"),
    ("我思故我在","Cogito Ergo Sum","笛卡尔哲学第一原理。","西方哲学·近代"),
    ("心物二元论","Mind-Body Dualism","笛卡尔主张心灵与物质是两种实体。","西方哲学·近代"),
    ("天赋观念","Innate Ideas","笛卡尔认为某些观念天生存在于心灵中。","西方哲学·近代"),
    ("方法论怀疑","Methodological Doubt","笛卡尔系统性怀疑以达确定知识。","西方哲学·近代"),
    ("经验论","Empiricism","知识来源于感觉经验的主张。","西方哲学·近代"),
    ("唯理论","Rationalism","知识来源于理性的主张。","西方哲学·近代"),
    ("白板说","Tabula Rasa","洛克主张心灵初始如白板。","西方哲学·近代"),
    ("物自体","Ding an sich","康德指独立于经验的存在。","西方哲学·近代"),
    ("先验综合判断","Synthetic A Priori","康德哲学核心概念。","西方哲学·近代"),
    ("绝对命令","Categorical Imperative","康德伦理学核心，无条件的行为准则。","西方哲学·近代"),
    ("现象界","Phenomenal World","康德指可经验的世界。","西方哲学·近代"),
    ("本体界","Noumenal World","康德指物自体的世界。","西方哲学·近代"),
    ("三大批判","Three Critiques","康德的纯粹理性批判、实践理性批判、判断力批判。","西方哲学·近代"),
    ("绝对精神","Absolute Spirit","黑格尔哲学的核心概念。","西方哲学·近代"),
    ("辩证法","Dialectics","黑格尔的正反合辩证运动。","西方哲学·近代"),
    ("主奴辩证法","Master-Slave Dialectic","黑格尔《精神现象学》中的著名段落。","西方哲学·近代"),
    ("异化","Alienation","黑格尔和马克思的重要概念。","西方哲学·近代"),
    ("扬弃","Aufheben","黑格尔辩证法中否定与保存的统一。","西方哲学·近代"),
    ("历史唯物主义","Historical Materialism","马克思关于历史发展规律的理论。","西方哲学·近代"),
    ("阶级斗争","Class Struggle","马克思关于社会冲突的理论。","西方哲学·近代"),
    ("意识形态","Ideology","马克思指统治阶级的思想体系。","西方哲学·近代"),
    ("上层建筑","Superstructure","马克思指建立在经济基础上的社会制度。","西方哲学·近代"),
    ("剩余价值","Surplus Value","马克思揭示资本主义剥削的核心概念。","西方哲学·近代"),
    ("商品拜物教","Commodity Fetishism","马克思对资本主义关系的批判。","西方哲学·近代"),
    ("实证主义","Positivism","孔德创始的哲学流派，强调经验验证。","西方哲学·近代"),
    ("功利主义","Utilitarianism","边沁和密尔主张最大多数人的最大幸福。","西方哲学·近代"),
    ("社会契约论","Social Contract Theory","霍布斯、洛克、卢梭的契约论。","西方哲学·近代"),
    ("自然状态","State of Nature","契约论中假设的前社会状态。","西方哲学·近代"),
    ("自然权利","Natural Rights","人生而具有的权利。","西方哲学·近代"),
    ("人民主权","Popular Sovereignty","卢梭主张主权属于人民。","西方哲学·近代"),
    ("意志自由","Freedom of Will","关于人的意志是否自由的问题。","西方哲学·近代"),
    ("决定论","Determinism","一切事件由先前原因决定。","西方哲学·近代"),
    ("相容论","Compatibilism","自由意志与决定论可以共存。","西方哲学·近代"),
]
phil_glossary.extend(medieval_modern)

# --- 20世纪哲学 ---
contemporary = [
    ("分析哲学","Analytic Philosophy","以语言分析为方法的哲学传统。","西方哲学·当代"),
    ("语言转向","Linguistic Turn","20世纪哲学从认识论转向语言分析。","西方哲学·当代"),
    ("逻辑原子论","Logical Atomism","罗素和早期维特根斯坦的哲学。","西方哲学·当代"),
    ("图像论","Picture Theory","维特根斯坦早期语言哲学。","西方哲学·当代"),
    ("语言游戏","Language Game","维特根斯坦后期哲学核心概念。","西方哲学·当代"),
    ("家族相似","Family Resemblance","维特根斯坦关于概念边界模糊的论述。","西方哲学·当代"),
    ("现象学","Phenomenology","胡塞尔创立的描述意识经验的哲学方法。","西方哲学·当代"),
    ("意向性","Intentionality","布伦塔诺和胡塞尔的核心概念，意识的指向性。","西方哲学·当代"),
    ("悬置","Epoché","胡塞尔现象学还原的方法。","西方哲学·当代"),
    ("生活世界","Lebenswelt","胡塞尔后期哲学核心概念。","西方哲学·当代"),
    ("存在主义","Existentialism","强调个体存在、自由和选择的哲学思潮。","西方哲学·当代"),
    ("存在先于本质","Existence Precedes Essence","萨特的核心命题。","西方哲学·当代"),
    ("自在与自为","En-soi and Pour-soi","萨特关于存在的区分。","西方哲学·当代"),
    ("烦","Sorge/Care","海德格尔此在的基本结构。","西方哲学·当代"),
    ("向死而生","Being-toward-Death","海德格尔关于死亡与存在的论述。","西方哲学·当代"),
    ("此在","Dasein","海德格尔对人的存在的称呼。","西方哲学·当代"),
    ("在世存在","Being-in-the-World","海德格尔哲学核心概念。","西方哲学·当代"),
    ("解构","Deconstruction","德里达的批判方法。","西方哲学·当代"),
    ("延异","Différance","德里达创造的概念，意指意义的延迟和差异。","西方哲学·当代"),
    ("权力意志","Will to Power","尼采哲学的核心概念。","西方哲学·当代"),
    ("永恒轮回","Eternal Recurrence","尼采关于时间循环的命题。","西方哲学·当代"),
    ("超人","Übermensch","尼采提出的超越传统道德的理想人格。","西方哲学·当代"),
    ("上帝已死","God is Dead","尼采宣告传统价值的崩塌。","西方哲学·当代"),
    ("谱系学","Genealogy","尼采和福柯的批判方法。","西方哲学·当代"),
    ("权力-知识","Power-Knowledge","福柯关于权力与知识关系的论述。","西方哲学·当代"),
    ("规训与惩罚","Discipline and Punish","福柯关于现代权力机制的著作。","西方哲学·当代"),
    ("话语","Discourse","福柯关于知识生产的话语分析。","西方哲学·当代"),
    ("生物政治","Biopolitics","福柯关于生命政治的概念。","西方哲学·当代"),
    ("拟像","Simulacra","鲍德里亚关于后现代仿真概念。","西方哲学·当代"),
    ("后现代主义","Postmodernism","质疑宏大叙事和确定性的哲学思潮。","西方哲学·当代"),
    ("元叙事","Metanarrative","利奥塔对宏大叙事的批判。","西方哲学·当代"),
    ("交往理性","Communicative Rationality","哈贝马斯的哲学核心概念。","西方哲学·当代"),
    ("公共领域","Public Sphere","哈贝马斯关于民主讨论空间的概念。","西方哲学·当代"),
    ("后结构主义","Post-Structuralism","德里达、福柯、德勒兹等人的哲学。","西方哲学·当代"),
    ("块茎","Rhizome","德勒兹和加塔利关于非等级结构的概念。","西方哲学·当代"),
    ("精神分裂分析","Schizoanalysis","德勒兹和加塔利的批判方法。","西方哲学·当代"),
    ("事件","Event","巴迪欧、齐泽克等关于断裂性事件的概念。","西方哲学·当代"),
    ("思辨实在论","Speculative Realism","21世纪兴起的新实在论思潮。","西方哲学·当代"),
    ("面向对象本体论","Object-Oriented Ontology","哈曼等人的哲学立场。","西方哲学·当代"),
    ("新唯物主义","New Materialism","强调物质能动性的当代思潮。","西方哲学·当代"),
]
phil_glossary.extend(contemporary)

# --- 逻辑学 ---
logic = [
    ("命题逻辑","Propositional Logic","研究命题之间逻辑关系的分支。","逻辑学"),
    ("谓词逻辑","Predicate Logic","包含量词和谓词的逻辑系统。","逻辑学"),
    ("模态逻辑","Modal Logic","研究必然性与可能性的逻辑。","逻辑学"),
    ("三段论","Syllogism","亚里士多德的演绎推理形式。","逻辑学"),
    ("归纳推理","Inductive Reasoning","从特殊到一般的推理方式。","逻辑学"),
    ("演绎推理","Deductive Reasoning","从一般到特殊的推理方式。","逻辑学"),
    ("溯因推理","Abductive Reasoning","从结果推断最佳解释的推理。","逻辑学"),
    ("同一律","Law of Identity","A=A，形式逻辑基本律。","逻辑学"),
    ("矛盾律","Law of Non-Contradiction","¬(P∧¬P)，不能同时肯定和否定。","逻辑学"),
    ("排中律","Law of Excluded Middle","P∨¬P，没有第三种可能。","逻辑学"),
    ("充足理由律","Principle of Sufficient Reason","一切事物都有其存在的理由。","逻辑学"),
    ("布尔代数","Boolean Algebra","逻辑运算的代数系统。","逻辑学"),
    ("哥德尔不完备定理","Gödel's Incompleteness Theorem","任何足够强的形式系统都包含不可判定的命题。","逻辑学"),
    ("图灵机","Turing Machine","图灵提出的计算模型。","逻辑学"),
    ("可计算性","Computability","问题能否被算法解决的性质。","逻辑学"),
    ("谓词","Predicate","表示主词属性或关系的逻辑成分。","逻辑学"),
    ("量词","Quantifier","全称量词∀和存在量词∃。","逻辑学"),
    ("真值表","Truth Table","列出命题所有可能真值的表。","逻辑学"),
    ("自然演绎","Natural Deduction","根岑提出的推理系统。","逻辑学"),
    ("直觉主义逻辑","Intuitionistic Logic","布劳威尔拒绝排中律的逻辑体系。","逻辑学"),
]
phil_glossary.extend(logic)

# --- 伦理学 ---
ethics = [
    ("德性伦理","Virtue Ethics","以品格为核心的伦理学理论。","伦理学"),
    ("义务论","Deontology","以义务为核心的伦理学理论。","伦理学"),
    ("后果论","Consequentialism","以结果为判断标准的伦理学理论。","伦理学"),
    ("元伦理学","Meta-ethics","研究伦理概念本质的哲学分支。","伦理学"),
    ("规范伦理学","Normative Ethics","研究行为规范的伦理学。","伦理学"),
    ("应用伦理学","Applied Ethics","将伦理原则应用于实际问题的分支。","伦理学"),
    ("道德相对主义","Moral Relativism","道德标准因文化而异的主张。","伦理学"),
    ("道德实在论","Moral Realism","道德事实客观存在的立场。","伦理学"),
    ("道德虚无主义","Moral Nihilism","否认道德真理存在的立场。","伦理学"),
    ("电车难题","Trolley Problem","经典伦理学思想实验。","伦理学"),
    ("无知之幕","Veil of Ignorance","罗尔斯正义论的思想实验。","伦理学"),
    ("正义论","A Theory of Justice","罗尔斯的正义理论。","伦理学"),
    ("差别原则","Difference Principle","罗尔斯正义论的第二个原则。","伦理学"),
    ("关怀伦理","Care Ethics","强调关系和关怀的伦理学。","伦理学"),
    ("生命伦理","Bioethics","研究生命科学中伦理问题的分支。","伦理学"),
    ("环境伦理","Environmental Ethics","研究人与自然关系的伦理学。","伦理学"),
    ("技术伦理","Technology Ethics","研究技术发展中的伦理问题。","伦理学"),
    ("分配正义","Distributive Justice","关于社会资源如何分配的理论。","伦理学"),
    ("代际正义","Intergenerational Justice","当代与后代之间的正义问题。","伦理学"),
    ("应得","Desert","关于应得回报的伦理概念。","伦理学"),
]
phil_glossary.extend(ethics)

# --- 美学 ---
aesthetics = [
    ("崇高","Sublime","超越美的宏伟壮烈的审美范畴。","美学"),
    ("优美","Beautiful","和谐愉悦的审美范畴。","美学"),
    ("悲剧","Tragedy","亚里士多德定义的审美范畴。","美学"),
    ("喜剧","Comedy","以滑稽为特征的审美范畴。","美学"),
    ("荒诞","Absurd","现代主义的核心审美范畴。","美学"),
    ("审美判断","Aesthetic Judgment","康德关于美的判断理论。","美学"),
    ("审美无利害","Disinterestedness","康德美学核心概念。","美学"),
    ("模仿","Mimesis","艺术模仿自然或现实的理论。","美学"),
    ("表现","Expression","艺术是情感表现的理论。","美学"),
    ("形式美","Formal Beauty","以形式为美的理论。","美学"),
    ("意境","Yijing","中国传统美学的核心范畴。","美学"),
    ("气韵","Qiyun","中国美学关于生动气质的概念。","美学"),
    ("趣味","Taste","审美感受力的概念。","美学"),
    ("天才","Genius","康德关于艺术创造力的论述。","美学"),
    ("艺术终结论","End of Art","丹托和黑格尔关于艺术终结的命题。","美学"),
    ("机械复制","Mechanical Reproduction","本雅明关于艺术复制的论述。","美学"),
    ("灵韵","Aura","本雅明关于艺术独特性的概念。","美学"),
    ("审美距离","Aesthetic Distance","审美主体与对象间的心理距离。","美学"),
    ("净化","Catharsis","亚里士多德关于悲剧效果的论述。","美学"),
    ("丑学","Aesthetics of Ugliness","研究丑的审美价值。","美学"),
]
phil_glossary.extend(aesthetics)

# --- 科学哲学 ---
phil_science = [
    ("可证伪性","Falsifiability","波普尔区分科学与非科学的标准。","科学哲学"),
    ("范式","Paradigm","库恩关于科学革命的核心概念。","科学哲学"),
    ("科学革命","Scientific Revolution","库恩关于范式转换的理论。","科学哲学"),
    ("研究纲领","Research Programme","拉卡托斯关于科学发展的理论。","科学哲学"),
    ("归纳问题","Problem of Induction","休谟提出的归纳推理合理性质疑。","科学哲学"),
    ("观察渗透理论","Theory-Ladenness of Observation","汉森提出的观察受理论影响的主张。","科学哲学"),
    ("迪昂-蒯因论题","Duhem-Quine Thesis","整体论的科学检验观。","科学哲学"),
    ("划界问题","Demarcation Problem","区分科学与非科学的标准问题。","科学哲学"),
    ("科学实在论","Scientific Realism","科学理论描述客观实在的主张。","科学哲学"),
    ("反实在论","Anti-Realism","科学理论仅为有用工具的主张。","科学哲学"),
    ("工具主义","Instrumentalism","科学理论只是预测工具。","科学哲学"),
    ("常规科学","Normal Science","库恩关于范式内科学活动的概念。","科学哲学"),
    ("不可通约性","Incommensurability","库恩关于不同范式不可比较的主张。","科学哲学"),
    ("科学社会学","Sociology of Science","研究科学社会维度的学科。","科学哲学"),
    ("实验者回归","Experimenter's Regress","柯林斯关于科学实验验证的问题。","科学哲学"),
    ("科学划界","Science Demarcation","区分科学与伪科学的问题。","科学哲学"),
    ("拉卡托斯硬核","Hard Core","研究纲领中不可反驳的核心假设。","科学哲学"),
    ("保护带","Protective Belt","研究纲领中可调整的辅助假设。","科学哲学"),
    ("贝叶斯主义","Bayesianism","用贝叶斯定理解释科学推理。","科学哲学"),
    ("自然主义","Naturalism","哲学应与自然科学连续的主张。","科学哲学"),
]
phil_glossary.extend(phil_science)

# --- 心智哲学 ---
phil_mind = [
    ("心身问题","Mind-Body Problem","心灵与身体关系的哲学问题。","心智哲学"),
    ("物理主义","Physicalism","一切都是物理的主张。","心智哲学"),
    ("二元论","Dualism","心灵与物质是两种不同实体的主张。","心智哲学"),
    ("功能主义","Functionalism","心理状态由功能角色定义。","心智哲学"),
    ("行为主义","Behaviorism","心理状态等同于行为倾向。","心智哲学"),
    ("同一论","Identity Theory","心理状态等同于大脑状态。","心智哲学"),
    ("属性二元论","Property Dualism","物理实体有非物理属性。","心智哲学"),
    ("取消主义","Eliminativism"," Folk psychology将被科学取代。","心智哲学"),
    ("中文房间","Chinese Room","塞尔反驳强人工智能的思想实验。","心智哲学"),
    ("图灵测试","Turing Test","图灵提出的机器智能标准。","心智哲学"),
    ("感受质","Qualia","主观感受的哲学概念。","心智哲学"),
    ("意识困难问题","Hard Problem of Consciousness","查尔默斯提出的意识难题。","心智哲学"),
    ("僵尸论证","Zombie Argument","无意识但行为相同的假想存在。","心智哲学"),
    ("多重实现","Multiple Realizability","心理状态可由不同物理基质实现。","心智哲学"),
    ("延展心灵","Extended Mind","克拉克主张认知延伸到体外。","心智哲学"),
    ("意向性","Intentionality","意识关于某物的指向性。","心智哲学"),
    ("他心问题","Problem of Other Minds","如何知道他人有心灵的哲学问题。","心智哲学"),
    ("知识论证","Knowledge Argument","杰克逊关于感受质的论证。","心智哲学"),
    ("缸中之脑","Brain in a Vat","怀疑论思想实验。","心智哲学"),
    ("自由意志","Free Will","意志是否自由选择的哲学问题。","心智哲学"),
]
phil_glossary.extend(phil_mind)

# --- 政治哲学 ---
political_phil = [
    ("正义","Justice","关于社会公平分配的哲学概念。","政治哲学"),
    ("自由","Liberty/Freedom","不受干涉或自主决定的状态。","政治哲学"),
    ("平等","Equality","人们在地位、机会或结果上的等同。","政治哲学"),
    ("权利","Rights","个人正当拥有的主张或自由。","政治哲学"),
    ("民主","Democracy","人民统治的政治制度。","政治哲学"),
    ("共和主义","Republicanism","强调公共善和公民美德的政治理论。","政治哲学"),
    ("自由主义","Liberalism","强调个人自由的政治哲学。","政治哲学"),
    ("保守主义","Conservatism","维护传统和秩序的政治哲学。","政治哲学"),
    ("社会主义","Socialism","主张社会共有生产资料的政治理论。","政治哲学"),
    ("无政府主义","Anarchism","反对国家权威的政治哲学。","政治哲学"),
    ("女性主义","Feminism","追求性别平等的政治哲学。","政治哲学"),
    ("社群主义","Communitarianism","强调社群价值的政治理论。","政治哲学"),
    ("多元主义","Pluralism","承认多种价值并存的立场。","政治哲学"),
    ("宽容","Tolerance","对异见的容忍和尊重。","政治哲学"),
    ("公民身份","Citizenship","政治共同体成员的法律和政治地位。","政治哲学"),
    ("消极自由","Negative Liberty","不受干涉的自由。","政治哲学"),
    ("积极自由","Positive Liberty","自主决定的自由。","政治哲学"),
    ("分配正义","Distributive Justice","关于社会资源分配的理论。","政治哲学"),
    ("矫正正义","Corrective Justice","纠正不公正状态的正义。","政治哲学"),
    ("全球正义","Global Justice","跨国正义的理论。","政治哲学"),
]
phil_glossary.extend(political_phil)

# --- 语言哲学 ---
lang_phil = [
    ("意义","Meaning","语言符号所表达的内容。","语言哲学"),
    ("指称","Reference","语言符号与对象的关系。","语言哲学"),
    ("涵义","Sense","弗雷格区分的词义层面。","语言哲学"),
    ("言语行为","Speech Act","奥斯汀关于语言行动的理论。","语言哲学"),
    ("施事行为","Illocutionary Act","言语行为中以言行事的部分。","语言哲学"),
    ("合作原则","Cooperative Principle","格莱斯关于会话合作的原则。","语言哲学"),
    ("会话含义","Conversational Implicature","格莱斯关于言外之意的理论。","语言哲学"),
    ("指称论","Referential Theory","意义即指称对象的理论。","语言哲学"),
    ("观念论","Ideational Theory","意义即心中观念的理论。","语言哲学"),
    ("使用论","Use Theory","意义即用法（维特根斯坦）。","语言哲学"),
    ("真理的语义论","Semantic Theory of Truth","塔斯基的真理论。","语言哲学"),
    ("指称的因果论","Causal Theory of Reference","克里普克的指称理论。","语言哲学"),
    ("严格指示词","Rigid Designator","克里普克关于名称的概念。","语言哲学"),
    ("摹状词理论","Theory of Descriptions","罗素关于限定摹状词的分析。","语言哲学"),
    ("私人语言论证","Private Language Argument","维特根斯坦反对私人语言的论证。","语言哲学"),
    ("概念图式","Conceptual Scheme","戴维森关于语言框架的概念。","语言哲学"),
    ("语义外在主义","Semantic Externalism","意义部分由环境决定的主张。","语言哲学"),
    ("孪生地球","Twin Earth","普特南的思想实验。","语言哲学"),
    ("自然类","Natural Kind","具有共同本质属性的事物类。","语言哲学"),
    ("专名","Proper Name","专有名称的哲学分析。","语言哲学"),
]
phil_glossary.extend(lang_phil)

# --- 宗教学 ---
religion = [
    ("神圣","Sacred/Holy","宗教中超越凡俗的存在属性。","宗教学"),
    ("世俗化","Secularization","宗教影响力下降的社会过程。","宗教学"),
    ("宗教经验","Religious Experience","与神圣接触的个人体验。","宗教学"),
    ("宗教多元论","Religious Pluralism","多种宗教均有真理的主张。","宗教学"),
    ("宗教排他论","Religious Exclusivism","只有一种宗教为真的主张。","宗教学"),
    ("宗教包容论","Religious Inclusivism","其他宗教部分为真的主张。","宗教学"),
    ("图腾","Totem","原始宗教中的崇拜对象。","宗教学"),
    ("禁忌","Taboo","宗教或社会禁止的行为。","宗教学"),
    ("仪式","Ritual","宗教活动的行为模式。","宗教学"),
    ("神话","Myth","解释世界起源的宗教叙事。","宗教学"),
    ("祭司","Priest","宗教仪式的主持者。","宗教学"),
    ("启示","Revelation","神圣意志的显现。","宗教学"),
    ("救赎","Salvation","宗教中获救的过程。","宗教学"),
    ("末世论","Eschatology","关于世界终结的宗教教义。","宗教学"),
    ("泛神论","Pantheism","神即自然的主张。","宗教学"),
    ("一神论","Monotheism","只有一个神的主张。","宗教学"),
    ("多神论","Polytheism","存在多个神的主张。","宗教学"),
    ("不可知论","Agnosticism","关于神的存在不可知的主张。","宗教学"),
    ("无神论","Atheism","否认神存在的主张。","宗教学"),
    ("宗教本质","Essence of Religion","关于宗教根本属性的探讨。","宗教学"),
]
phil_glossary.extend(religion)

# --- 认识论补充 ---
epistemology_extra = [
    ("知识","Knowledge","被证明为真的信念（JTB）。","认识论"),
    ("信念","Belief","对命题为真的接受状态。","认识论"),
    ("证成","Justification","知识成立的合理基础。","认识论"),
    ("盖梯尔问题","Gettier Problem","挑战传统知识定义的反例。","认识论"),
    ("基础主义","Foundationalism","知识建立在基本信念之上的理论。","认识论"),
    ("融贯论","Coherentism","知识是一个融贯系统的理论。","认识论"),
    ("可靠主义","Reliabilism","知识由可靠过程产生的理论。","认识论"),
    ("自然化认识论","Naturalized Epistemology","奎因主张认识论应融入科学。","认识论"),
    ("社会认识论","Social Epistemology","研究知识的社会维度。","认识论"),
    ("女性主义认识论","Feminist Epistemology","从性别视角批判传统认识论。","认识论"),
    ("德性认识论","Virtue Epistemology","以认知德性为核心的认识论。","认识论"),
    ("怀疑论","Skepticism","质疑知识可能性的哲学立场。","认识论"),
    ("独断论","Dogmatism","不加批判地肯定知识的立场。","认识论"),
    ("真理符合论","Correspondence Theory of Truth","真理是事实的符合。","认识论"),
    ("真理融贯论","Coherence Theory of Truth","真理是信念间的融贯。","认识论"),
    ("真理实用论","Pragmatic Theory of Truth","真理是有用性。","认识论"),
    ("真理冗余论","Redundancy Theory of Truth","真不增加内容。","认识论"),
    ("直觉","Intuition","非推理的直接认知。","认识论"),
    ("记忆","Memory","过去经验的保留和再现。","认识论"),
    ("证言","Testimony","他人陈述作为知识来源。","认识论"),
]
phil_glossary.extend(epistemology_extra)

# --- 形而上学补充 ---
metaphysics_extra = [
    ("存在","Being","最根本的哲学概念。","形而上学"),
    ("生成","Becoming","从非存在到存在的变化。","形而上学"),
    ("本质","Essence","事物的根本属性。","形而上学"),
    ("偶性","Accident","非本质的属性。","形而上学"),
    ("必然","Necessity","不可能不如此的性质。","形而上学"),
    ("偶然","Contingency","可能不如此的性质。","形而上学"),
    ("可能","Possibility","逻辑或物理上可以实现的。","形而上学"),
    ("不可能","Impossibility","逻辑或物理上不能实现的。","形而上学"),
    ("共相","Universals","可被多个个体共享的属性。","形而上学"),
    ("殊相","Particulars","具体的个别事物。","形而上学"),
    ("因果","Causation","原因与结果的关系。","形而上学"),
    ("时间","Time","持续流逝的存在维度。","形而上学"),
    ("空间","Space","广延的存在维度。","形而上学"),
    ("自由","Freedom","不受决定的行动能力。","形而上学"),
    ("人格同一性","Personal Identity","个体在不同时间保持同一的问题。","形而上学"),
    ("可能世界","Possible Worlds","模态形而上学的核心概念。","形而上学"),
    ("随附性","Supervenience","一组属性依赖另一组属性的关系。","形而上学"),
    ("实现","Realization","心理状态由物理状态实现。","形而上学"),
    ("奠基","Grounding","解释存在的依赖关系。","形而上学"),
    ("虚无","Nothingness","不存在或空无的状态。","形而上学"),
]
phil_glossary.extend(metaphysics_extra)

# --- 更多哲学概念（补充至500+）---
phil_more = [
    ("启蒙","Enlightenment","18世纪理性解放运动。","启蒙哲学"),
    ("理性","Reason","人类认识和判断的能力。","启蒙哲学"),
    ("浪漫主义","Romanticism","18-19世纪强调情感与想象的文化运动。","启蒙哲学"),
    ("历史主义","Historicism","在历史语境中理解事物的立场。","历史哲学"),
    ("进步","Progress","人类历史向好的方向发展。","历史哲学"),
    ("文明","Civilization","高级社会文化形态。","文化哲学"),
    ("文化","Culture","人类创造的精神和物质成果。","文化哲学"),
    ("现代性","Modernity","现代社会的基本特征。","文化哲学"),
    ("后现代性","Postmodernity","对现代性的批判和超越。","文化哲学"),
    ("全球化","Globalization","世界日益互联的趋势。","文化哲学"),
    ("技术哲学","Philosophy of Technology","反思技术本质和影响的分支。","应用哲学"),
    ("环境哲学","Environmental Philosophy","反思人与自然关系的分支。","应用哲学"),
    ("法律哲学","Philosophy of Law","研究法律本质的分支。","应用哲学"),
    ("教育哲学","Philosophy of Education","研究教育本质的分支。","应用哲学"),
    ("历史哲学","Philosophy of History","研究历史意义和规律的分支。","应用哲学"),
    ("宗教哲学","Philosophy of Religion","以理性方法研究宗教的分支。","应用哲学"),
    ("行动哲学","Philosophy of Action","研究行动本质的分支。","应用哲学"),
    ("数学哲学","Philosophy of Mathematics","研究数学本质的分支。","应用哲学"),
    ("物理哲学","Philosophy of Physics","研究物理学基础的分支。","应用哲学"),
    ("生物哲学","Philosophy of Biology","研究生物学基础的分支。","应用哲学"),
    ("经济哲学","Philosophy of Economics","研究经济学基础的分支。","应用哲学"),
    ("心理哲学","Philosophy of Psychology","研究心理学基础的分支。","应用哲学"),
    ("社会哲学","Social Philosophy","研究社会本质的分支。","应用哲学"),
    ("比较哲学","Comparative Philosophy","跨文化哲学比较的分支。","应用哲学"),
    ("跨文化哲学","Intercultural Philosophy","不同文化间哲学对话的分支。","应用哲学"),
    ("实践哲学","Practical Philosophy","研究行动和价值的哲学。","应用哲学"),
    ("理论哲学","Theoretical Philosophy","研究认识和存在的哲学。","应用哲学"),
    ("第一哲学","First Philosophy","形而上学的别称。","应用哲学"),
    ("第二哲学","Second Philosophy","自然哲学或物理学的别称。","应用哲学"),
    ("生活哲学","Philosophy of Life","以生命为核心的哲学思考。","应用哲学"),
    ("身体哲学","Philosophy of Body","以身体为中心的哲学思考。","应用哲学"),
    ("情感哲学","Philosophy of Emotion","研究情感本质的哲学。","应用哲学"),
    ("想象哲学","Philosophy of Imagination","研究想象力的哲学。","应用哲学"),
    ("隐喻哲学","Philosophy of Metaphor","研究隐喻认知的哲学。","应用哲学"),
    ("叙事哲学","Philosophy of Narrative","研究叙事结构的哲学。","应用哲学"),
    ("解释学","Hermeneutics","关于理解和解释的哲学。","应用哲学"),
    ("效果历史","Wirkungsgeschichte","伽达默尔解释学概念。","应用哲学"),
    ("视域融合","Fusion of Horizons","伽达默尔解释学核心概念。","应用哲学"),
    ("解释学循环","Hermeneutic Circle","整体与部分互为解释的关系。","应用哲学"),
    ("前理解","Pre-understanding","理解发生前的已有认知框架。","应用哲学"),
    ("作者之死","Death of the Author","巴特关于文本意义的论述。","应用哲学"),
    ("互文性","Intertextuality","文本间相互引用的关系。","应用哲学"),
    ("书写学","Grammatology","德里达关于书写的哲学。","应用哲学"),
    ("语音中心主义","Phonocentrism","德里达批判的西方哲学倾向。","应用哲学"),
    ("逻各斯中心主义","Logocentrism","德里达批判的西方哲学倾向。","应用哲学"),
    ("在场的形而上学","Metaphysics of Presence","德里达对传统形而上学的批判。","应用哲学"),
    ("延异","Différance","德里达关于意义延迟与差异的概念。","应用哲学"),
    ("踪迹","Trace","德里达关于意义残留的概念。","应用哲学"),
    ("幽灵学","Hauntology","德里达关于存在与不在的概念。","应用哲学"),
    ("事件哲学","Philosophy of the Event","巴迪欧等关于事件的哲学。","应用哲学"),
    ("辩证唯物主义","Dialectical Materialism","马克思主义哲学的世界观。","应用哲学"),
    ("实践","Praxis","马克思主义哲学核心概念。","应用哲学"),
    ("物化","Reification","卢卡奇对资本主义异化的分析。","应用哲学"),
    ("总体性","Totality","卢卡奇马克思主义核心概念。","应用哲学"),
    ("文化霸权","Cultural Hegemony","葛兰西关于文化领导权的概念。","应用哲学"),
    ("有机知识分子","Organic Intellectual","葛兰西关于知识分子角色的概念。","应用哲学"),
    ("空间生产","Production of Space","列斐伏尔关于空间的理论。","应用哲学"),
    ("消费社会","Consumer Society","鲍德里亚对消费文化的批判。","应用哲学"),
    ("景观社会","Society of the Spectacle","德波关于视觉消费的批判。","应用哲学"),
    ("认知资本主义","Cognitive Capitalism","当代资本主义新形态的理论。","应用哲学"),
    ("人类世","Anthropocene","人类活动深刻改变地球的时代。","应用哲学"),
    ("后人类主义","Posthumanism","超越传统人文主义的思想。","应用哲学"),
    ("超人类主义","Transhumanism","通过技术增强人类的主张。","应用哲学"),
    ("行动者网络理论","Actor-Network Theory","拉图尔关于人与物关系的理论。","应用哲学"),
    ("扁平本体论","Flat Ontology","取消存在层级的本体论主张。","应用哲学"),
    ("新活力论","New Vitalism","强调生命活力的当代思潮。","应用哲学"),
    ("万物有灵论复兴","Animism Revival","当代哲学重新审视万物有灵。","应用哲学"),
    ("面向对象本体论","Object-Oriented Ontology","哈曼的哲学立场。","应用哲学"),
    (" withdraw","Withdrawal","哈曼关于对象不可穷尽的主张。","应用哲学"),
    ("关联主义","Relationism","强调关系先于实体的哲学。","应用哲学"),
    ("过程哲学","Process Philosophy","怀特海以过程为本体的哲学。","应用哲学"),
    ("事件本体论","Event Ontology","以事件为基本存在的本体论。","应用哲学"),
    ("事实本体论","Fact Ontology","以事实为基本存在的本体论。","应用哲学"),
    ("殊例论","Tropes","以属性实例为本体的理论。","应用哲学"),
    ("束理论","Bundle Theory","物体是属性束的理论。","应用哲学"),
    ("基体论","Substratum Theory","物体是属性加基体的理论。","应用哲学"),
    ("时间哲学","Philosophy of Time","研究时间本质的分支。","应用哲学"),
    ("A理论","A-Theory of Time","过去现在未来有客观区别。","应用哲学"),
    ("B理论","B-Theory of Time","时间是一维的先后关系。","应用哲学"),
    ("永恒论","Eternalism","过去现在未来同样实在。","应用哲学"),
    ("现在论","Presentism","只有现在是实在的。","应用哲学"),
    ("生长论","Growing Block Theory","过去和现在存在但未来不存在。","应用哲学"),
    ("因果论","Causal Theory","因果关系的哲学理论。","应用哲学"),
    ("反事实条件","Counterfactual","用反事实分析因果的理论。","应用哲学"),
    ("因果传递","Causal Transference","因果通过物理量传递。","应用哲学"),
    ("因果对称","Causal Symmetry","原因和结果可互换的主张。","应用哲学"),
    ("目的因果","Teleological Causation","以目的解释因果。","应用哲学"),
    ("概率因果","Probabilistic Causation","用概率分析因果。","应用哲学"),
    ("干预论","Interventionism","用干预定义因果。","应用哲学"),
    ("结构因果模型","Structural Causal Model","用图模型表示因果。","应用哲学"),
    ("模态实在论","Modal Realism","刘易斯主张可能世界真实存在。","应用哲学"),
    ("模态虚构论","Modal Fictionalism","可能世界仅为虚构。","应用哲学"),
    ("模态工具论","Modal Instrumentalism","可能世界仅为工具。","应用哲学"),
    ("本质主义","Essentialism","事物有不变本质的主张。","应用哲学"),
    ("反本质主义","Anti-Essentialism","否认事物有不变本质。","应用哲学"),
    ("建构主义","Constructivism","知识或对象是被建构的。","应用哲学"),
    ("社会建构主义","Social Constructivism","社会现象是被建构的。","应用哲学"),
    ("科学建构主义","Scientific Constructivism","科学知识是被建构的。","应用哲学"),
    ("批判理论","Critical Theory","法兰克福学派的批判哲学。","应用哲学"),
    ("工具理性","Instrumental Reason","法兰克福学派对理性工具化的批判。","应用哲学"),
    ("文化工业","Culture Industry","阿多诺和霍克海默的概念。","应用哲学"),
    ("否定的辩证法","Negative Dialectics","阿多诺的哲学方法。","应用哲学"),
    ("星丛","Constellation","阿多诺关于非同一性思维的概念。","应用哲学"),
    ("非同一性","Non-Identity","阿多诺哲学核心概念。","应用哲学"),
    ("启蒙辩证法","Dialectic of Enlightenment","霍克海默和阿多诺的著作。","应用哲学"),
    ("单向度的人","One-Dimensional Man","马尔库塞对发达工业社会的批判。","应用哲学"),
    ("大拒绝","Great Refusal","马尔库塞的概念。","应用哲学"),
    ("承认理论","Recognition Theory","霍耐特的核心理论。","应用哲学"),
    ("为承认而斗争","Struggle for Recognition","霍耐特的哲学主张。","应用哲学"),
    ("自由的三分模式","Three Models of Freedom","霍耐特关于自由的理论。","应用哲学"),
    ("民主伦理生活","Democratic Ethical Life","霍耐特的政治哲学概念。","应用哲学"),
    ("后马克思主义","Post-Marxism","墨菲等人的政治哲学。","应用哲学"),
    ("激进民主","Radical Democracy","墨菲的政治理论。","应用哲学"),
    ("对抗","Antagonism","墨菲政治哲学概念。","应用哲学"),
    ("解构正义","Deconstructive Justice","德里达关于正义的论述。","应用哲学"),
    ("到来的民主","Democracy to Come","德里达关于民主的理想。","应用哲学"),
    ("好客","Hospitality","德里达关于接待他者的概念。","应用哲学"),
    ("宽恕","Forgiveness","德里达关于宽恕的哲学。","应用哲学"),
    ("礼物","Gift","德里达关于礼物悖论的论述。","应用哲学"),
    ("友爱政治","Politics of Friendship","德里达关于政治友爱的著作。","应用哲学"),
    ("动物哲学","Animal Philosophy","德里达等关于动物的哲学。","应用哲学"),
    ("动物凝视","Animal Gaze","德里达关于动物的概念。","应用哲学"),
    ("触觉","Touch","南希等关于触觉的哲学。","应用哲学"),
    ("共在","Being-with","南希关于共同存在的概念。","应用哲学"),
    ("复数的奇异性","Singular Plural","南希的哲学概念。","应用哲学"),
    ("劳作","Work","南希关于劳作与意义的概念。","应用哲学"),
    ("降临","Advent","南希关于事件降临的概念。","应用哲学"),
    ("无用的共同体","Inoperative Community","南希关于共同体的概念。","应用哲学"),
    ("意义之思","Thinking Sense","南希关于意义的哲学。","应用哲学"),
    ("触感","Tact","南希关于触觉哲学的概念。","应用哲学"),
    ("广延","Extension","笛卡尔物质属性。","应用哲学"),
    ("思维","Thinking","笛卡尔心灵属性。","应用哲学"),
    ("清楚明白","Clear and Distinct","笛卡尔真理标准。","应用哲学"),
    ("自然之光","Light of Nature","笛卡尔理性直觉。","应用哲学"),
    ("蜡块论证","Wax Argument","笛卡尔关于心灵本质的论证。","应用哲学"),
    ("松果腺","Pineal Gland","笛卡尔心身交互处。","应用哲学"),
    ("机器中的幽灵","Ghost in the Machine","赖尔对二元论的批评。","应用哲学"),
    ("范畴错误","Category Mistake","赖尔哲学核心概念。","应用哲学"),
    ("塞拉斯神话空间","Myth of the Given","塞拉斯批判的基础主义。","应用哲学"),
    ("心理名词主义","Psychological Nominalism","塞拉斯的概念。","应用哲学"),
    ("科学之映像","Scientific Image","塞拉斯关于科学世界观的概念。","应用哲学"),
    ("显现之映像","Manifest Image","塞拉斯关于日常世界观的概念。","应用哲学"),
    ("语言游戏","Language Game","维特根斯坦后期哲学概念。","应用哲学"),
    ("生活形式","Form of Life","维特根斯坦的概念。","应用哲学"),
    ("私人语言","Private Language","维特根斯坦质疑的概念。","应用哲学"),
    ("甲虫盒子","Beetle in a Box","维特根斯坦的思想实验。","应用哲学"),
    ("规则遵循","Rule Following","维特根斯坦关于规则的问题。","应用哲学"),
    ("意义即使用","Meaning is Use","维特根斯坦核心主张。","应用哲学"),
    ("不可说","The Unspeakable","维特根斯坦关于语言边界的概念。","应用哲学"),
    ("显示自身","Showing Itself","维特根斯坦关于显示与言说的区分。","应用哲学"),
    ("沉默","Silence","维特根斯坦哲学终点的态度。","应用哲学"),
    ("日常语言哲学","Ordinary Language Philosophy","牛津学派哲学传统。","应用哲学"),
    ("言语行为理论","Speech Act Theory","奥斯汀和塞尔的理论。","应用哲学"),
    ("记述话语","Constative Utterance","奥斯汀区分的言语类型。","应用哲学"),
    ("施事话语","Performative Utterance","奥斯汀区分的言语类型。","应用哲学"),
    ("合适条件","Felicity Conditions","施事话语成功的条件。","应用哲学"),
    ("以言指事","Locutionary Act","言语行为的层面。","应用哲学"),
    ("以言行事","Illocutionary Act","言语行为的层面。","应用哲学"),
    ("以言成事","Perlocutionary Act","言语行为的层面。","应用哲学"),
    ("间接言语行为","Indirect Speech Act","塞尔的概念。","应用哲学"),
    ("制度性事实","Institutional Fact","塞尔的概念。","应用哲学"),
    ("集体意向性","Collective Intentionality","塞尔的概念。","应用哲学"),
    ("社会实在的建构","Construction of Social Reality","塞尔的著作。","应用哲学"),
    ("中文房间","Chinese Room","塞尔的反AI论证。","应用哲学"),
    ("语法","Syntax","符号之间的关系。","应用哲学"),
    ("语义","Semantics","符号与对象的关系。","应用哲学"),
    ("语用","Pragmatics","符号与使用者的关系。","应用哲学"),
    ("组合性","Compositionality","整体意义由部分决定。","应用哲学"),
    ("外延","Extension","词项所指对象集合。","应用哲学"),
    ("内涵","Intension","词项的意义内容。","应用哲学"),
    ("分析性","Analyticity","分析真理的性质。","应用哲学"),
    ("综合性","Syntheticity","综合真理的性质。","应用哲学"),
    ("同义性","Synonymy","同义关系。","应用哲学"),
    ("必然性先天","Necessity A Priori","克里普克质疑的关联。","应用哲学"),
    ("偶然性先天","A Priori Contingent","克里普克的新分类。","应用哲学"),
    ("必然性后验","A Posteriori Necessary","克里普克的新分类。","应用哲学"),
    ("专名的因果链","Causal Chain of Names","克里普克的指称理论。","应用哲学"),
    (" baptizing","Initial Baptism","克里普克的命名仪式。","应用哲学"),
    ("传递链","Chain of Communication","名称指称的传递。","应用哲学"),
    ("反描述论","Anti-Descriptivism","克里普克反对描述论。","应用哲学"),
    ("直接指称","Direct Reference","名称直接指称对象。","应用哲学"),
    ("弗雷格谜题","Frege's Puzzle","同一性陈述的认知价值问题。","应用哲学"),
    ("信念语境","Belief Context","命题态度报告的语境。","应用哲学"),
    ("不透明语境","Opaque Context","外延替换失效的语境。","应用哲学"),
    ("透明语境","Transparent Context","外延替换有效的语境。","应用哲学"),
    ("命题态度","Propositional Attitude","对命题的心理关系。","应用哲学"),
    ("反事实条件","Counterfactual Conditional","与事实相反的假设条件句。","应用哲学"),
    ("严格必然","Strict Necessity","克里普克关于必然性的概念。","应用哲学"),
    ("可能世界语义","Possible World Semantics","用可能世界解释模态。","应用哲学"),
    ("可达关系","Accessibility Relation","可能世界间的关系。","应用哲学"),
    ("本质属性","Essential Property","克里普克关于本质的概念。","应用哲学"),
    ("起源本质","Origin Essentialism","克里普克关于起源是本质的论证。","应用哲学"),
    ("物质构成","Material Constitution","物体与构成物质的关系问题。","应用哲学"),
    ("忒修斯之船","Ship of Theseus","同一性的经典难题。","应用哲学"),
    ("雕像与粘土","Statue and Clay","构成问题的经典案例。","应用哲学"),
    ("时间旅行","Time Travel","时间哲学中的思想实验。","应用哲学"),
    ("祖父悖论","Grandfather Paradox","时间旅行的逻辑悖论。","应用哲学"),
    ("自因","Causa Sui","自身是自身原因的概念。","应用哲学"),
    ("充足理由","Sufficient Reason","一切皆有理由的原理。","应用哲学"),
    ("自然律","Laws of Nature","自然界规律性的哲学。","应用哲学"),
    ("休谟主义律则观","Humean View of Laws","规律是规律性的总结。","应用哲学"),
    ("必然主义律则观","Necessitarian View of Laws","规律是必然的。","应用哲学"),
    ("最佳系统","Best System","刘易斯关于律则的理论。","应用哲学"),
    ("随附律则","Supervenient Laws","规律随附于事实。","应用哲学"),
    ("倾向性","Dispositions","倾向属性的哲学。","应用哲学"),
    ("反事实条件分析","Counterfactual Analysis","用反事实分析倾向。","应用哲学"),
    ("反反事实","Finkish Dispositions","马尔丁关于倾向的反例。","应用哲学"),
    ("颜色哲学","Philosophy of Color","关于颜色本质的哲学。","应用哲学"),
    ("颜色实在论","Color Realism","颜色客观存在的主张。","应用哲学"),
    ("颜色取消主义","Color Eliminativism","颜色不存在的主张。","应用哲学"),
    ("颜色关系主义","Color Relationalism","颜色是关系属性。","应用哲学"),
    ("声音哲学","Philosophy of Sound","关于声音本质的哲学。","应用哲学"),
    ("声音定位论","Location Theory of Sound","声音在媒介中。","应用哲学"),
    ("声音事件论","Event Theory of Sound","声音是事件。","应用哲学"),
    ("感知哲学","Philosophy of Perception","关于感知的哲学。","应用哲学"),
    ("直接实在论","Direct Realism","直接感知外部世界。","应用哲学"),
    ("表征主义","Representationalism","感知是表征。","应用哲学"),
    ("感觉材料","Sense Data","感知的直接对象。","应用哲学"),
    ("显相","Appearance","事物显现的方式。","应用哲学"),
    ("错觉论证","Argument from Illusion","用错觉论证感觉材料。","应用哲学"),
    ("幻觉论证","Argument from Hallucination","用幻觉论证感觉材料。","应用哲学"),
    ("析取论","Disjunctivism","感知和幻觉是不同类型的事件。","应用哲学"),
    ("行动哲学","Philosophy of Action","关于行动的哲学。","应用哲学"),
    ("意向行动","Intentional Action","有意为之的行动。","应用哲学"),
    ("基本行动","Basic Action","直接做的行动。","应用哲学"),
    ("行动理由","Reasons for Action","行动的动机和证成。","应用哲学"),
    ("动机理由","Motivating Reason","驱动行动的理由。","应用哲学"),
    ("证成理由","Justifying Reason","支持行动的理由。","应用哲学"),
    ("内省","Introspection","对自己心理状态的观察。","应用哲学"),
    ("透明性","Transparency","心灵对自身状态的直接认知。","应用哲学"),
    ("自知","Self-Knowledge","关于自己心理状态的知识。","应用哲学"),
    ("第一人称权威","First-Person Authority","主体对自己心理的权威性。","应用哲学"),
    ("无意识","Unconscious","弗洛伊德和心灵哲学的概念。","应用哲学"),
    ("梦","Dream","关于梦的哲学思考。","应用哲学"),
    ("自我","Self","关于自我同一性的哲学。","应用哲学"),
    ("叙事自我","Narrative Self","以叙事构建的自我。","应用哲学"),
    ("最小自我","Minimal Self","前反思的自我意识。","应用哲学"),
    ("无我","No-Self","佛教哲学的自我观。","应用哲学"),
    ("佛教哲学","Buddhist Philosophy","佛教系统的哲学思考。","应用哲学"),
    ("儒家哲学","Confucian Philosophy","儒家系统的哲学思考。","应用哲学"),
    ("道家哲学","Daoist Philosophy","道家系统的哲学思考。","应用哲学"),
    ("日本哲学","Japanese Philosophy","日本传统的哲学思考。","应用哲学"),
    ("阿拉伯哲学","Arabic Philosophy","伊斯兰传统的哲学思考。","应用哲学"),
    ("印度哲学","Indian Philosophy","印度传统的哲学思考。","应用哲学"),
    ("非洲哲学","African Philosophy","非洲传统的哲学思考。","应用哲学"),
    ("拉美哲学","Latin American Philosophy","拉丁美洲传统的哲学思考。","应用哲学"),
    ("比较哲学方法","Comparative Method","跨文化哲学比较的方法论。","应用哲学"),
    ("跨文化对话","Intercultural Dialogue","不同文化间的哲学对话。","应用哲学"),
    ("世界哲学","World Philosophy","全球视野下的哲学。","应用哲学"),
]
phil_glossary.extend(phil_more)

print(f"Philosophy: {len(phil_glossary)} terms")

disciplines.append({
    "id": "philosophy", "name": "哲学", "nameEn": "Philosophy",
    "icon": "ph", "color": "#8B4513",
    "description": "研究存在、知识、价值、理性、心灵和语言等基本问题",
    "glossary": phil_glossary,
    "formulas": [
        {"name": "肯定否定律", "formula": "¬(¬P) ≡ P", "description": "双重否定等于肯定，逻辑学基本定律。", "reference": "形式逻辑"},
        {"name": "矛盾律", "formula": "¬(P ∧ ¬P)", "description": "同一对象在同一时间同一方面不能既是又不是。", "reference": "亚里士多德"},
        {"name": "排中律", "formula": "P ∨ ¬P", "description": "任何命题要么为真要么为假，没有第三种可能。", "reference": "亚里士多德"},
        {"name": "同一律", "formula": "A = A", "description": "每个事物都等于自身，是形式逻辑的基本律。", "reference": "亚里士多德"},
    ],
    "standards": [
        {"name": "哲学名词审定规范", "code": "GB/T 1.1", "description": "哲学名词术语的规范化和标准化。"},
        {"name": "逻辑符号系统", "code": "ISO 24237", "description": "形式逻辑中符号表达的国际标准。"},
    ],
})


# ============================================================
# Helper to generate remaining disciplines efficiently
# ============================================================
# For the remaining 12 disciplines, we generate comprehensive term lists
# using structured category-based generation

def make_discipline(did, dname, dnameEn, dicon, dcolor, ddesc, cats):
    """cats = list of (category, [(term, termEn, def), ...])"""
    glossary = []
    for cat, terms in cats:
        for t in terms:
            glossary.append({"term": t[0], "termEn": t[1], "definition": t[2], "category": cat})
    return {
        "id": did, "name": dname, "nameEn": dnameEn,
        "icon": dicon, "color": dcolor, "description": ddesc,
        "glossary": glossary,
        "formulas": [],
        "standards": [],
    }


# ============================================================
# 2. 经济学 Economics
# ============================================================
econ_cats = [
    ("微观经济·消费者理论", [
        ("效用","Utility","消费者从商品中获得的满足。"),
        ("总效用","Total Utility","消费全部商品获得的满足总和。"),
        ("边际效用","Marginal Utility","增加一单位消费所增加的满足。"),
        ("边际效用递减","Diminishing Marginal Utility","随着消费增加边际效用递减。"),
        ("无差异曲线","Indifference Curve","给消费者同等效用的商品组合。"),
        ("预算约束","Budget Constraint","消费者收入的支出限制。"),
        ("消费者均衡","Consumer Equilibrium","消费者效用最大化的状态。"),
        ("替代效应","Substitution Effect","价格变化引起的替代。"),
        ("收入效应","Income Effect","价格变化引起的实际收入变化。"),
        ("吉芬商品","Giffen Good","价格上升需求增加的商品。"),
        ("需求曲线","Demand Curve","价格与需求量的关系。"),
        ("恩格尔曲线","Engel Curve","收入与需求量的关系。"),
        ("消费者剩余","Consumer Surplus","消费者愿意支付与实际支付的差。"),
        ("价格弹性","Price Elasticity of Demand","需求对价格的敏感度。"),
        ("收入弹性","Income Elasticity of Demand","需求对收入的敏感度。"),
        ("交叉弹性","Cross Elasticity of Demand","一种商品需求对另一种商品价格的敏感度。"),
    ]),
    ("微观经济·生产者理论", [
        ("生产函数","Production Function","投入与产出的技术关系。"),
        ("边际产量","Marginal Product","增加一单位投入的产量增量。"),
        ("边际产量递减","Diminishing Marginal Returns","随着投入增加边际产量递减。"),
        ("等产量曲线","Isoquant","产出相同的投入组合。"),
        ("等成本线","Isocost","成本相同的投入组合。"),
        ("规模报酬","Returns to Scale","投入按比例变化时产出的变化。"),
        ("规模经济","Economies of Scale","规模扩大导致平均成本下降。"),
        ("规模不经济","Diseconomies of Scale","规模过大导致平均成本上升。"),
        ("范围经济","Economies of Scope","多种产品联合生产降低成本。"),
        ("固定成本","Fixed Cost","不随产量变化的成本。"),
        ("可变成本","Variable Cost","随产量变化的成本。"),
        ("边际成本","Marginal Cost","增加一单位产量的成本增量。"),
        ("平均成本","Average Cost","总成本除以产量。"),
        ("沉没成本","Sunk Cost","已发生且不可回收的成本。"),
        ("机会成本","Opportunity Cost","选择一种方案放弃的最大收益。"),
        ("经济利润","Economic Profit","总收入减去总经济成本。"),
        ("会计利润","Accounting Profit","总收入减去会计成本。"),
        ("正常利润","Normal Profit","企业家才能的报酬。"),
        ("短期","Short Run","至少一种投入固定的时期。"),
        ("长期","Long Run","所有投入可变的时期。"),
    ]),
    ("微观经济·市场结构", [
        ("完全竞争","Perfect Competition","无数买卖双方、同质产品的市场。"),
        ("垄断","Monopoly","单一卖方的市场。"),
        ("寡头","Oligopoly","少数卖方的市场。"),
        ("垄断竞争","Monopolistic Competition","多数卖方、产品差异化的市场。"),
        ("价格歧视","Price Discrimination","对不同消费者收取不同价格。"),
        ("自然垄断","Natural Monopoly","规模经济导致一家企业供应整个市场。"),
        ("卡特尔","Cartel","寡头企业的价格联盟。"),
        ("博弈","Game","策略互动的决策情境。"),
        ("纳什均衡","Nash Equilibrium","各方策略互为最优反应。"),
        ("囚徒困境","Prisoner's Dilemma","个体理性导致集体非理性的博弈。"),
        ("占优策略","Dominant Strategy","无论对方如何选择都最优的策略。"),
        ("混合策略","Mixed Strategy","以概率选择的策略。"),
        ("重复博弈","Repeated Game","多次进行的博弈。"),
        ("序贯博弈","Sequential Game","先后行动的博弈。"),
        ("逆向归纳","Backward Induction","从终点倒推求解博弈。"),
        ("触发策略","Trigger Strategy","以惩罚维持合作的策略。"),
    ]),
    ("微观经济·要素市场", [
        ("劳动供给","Labor Supply","劳动者愿意提供的劳动量。"),
        ("劳动需求","Labor Demand","企业愿意雇用的劳动量。"),
        ("工资","Wage","劳动的价格。"),
        ("人力资本","Human Capital","劳动者的知识和技能。"),
        ("地租","Rent","土地的报酬。"),
        ("经济租","Economic Rent","超出机会成本的报酬。"),
        ("利息","Interest","资本的价格。"),
        ("资本","Capital","用于生产的耐久性投入。"),
        ("利润","Profit","企业家的报酬。"),
        ("洛伦兹曲线","Lorenz Curve","收入分配的图形表示。"),
        ("基尼系数","Gini Coefficient","收入不平等的度量。"),
    ]),
    ("宏观经济·总览", [
        ("国内生产总值","GDP","一定时期内生产的最终产品和服务的市场价值。"),
        ("国民生产总值","GNP","本国居民生产的最终产品和服务的市场价值。"),
        ("国民收入","National Income","生产要素获得的总收入。"),
        ("个人可支配收入","Disposable Income","税后个人收入。"),
        ("消费","Consumption","家庭支出。"),
        ("投资","Investment","资本形成。"),
        ("政府支出","Government Spending","政府购买。"),
        ("净出口","Net Exports","出口减进口。"),
        ("储蓄","Saving","收入减消费。"),
        ("总需求","Aggregate Demand","总支出。"),
        ("总供给","Aggregate Supply","总产出。"),
        ("乘数","Multiplier","初始支出引起的成倍收入增加。"),
        ("加速数","Accelerator","收入变化引起的投资变化。"),
        ("IS-LM模型","IS-LM Model","产品市场和货币市场均衡。"),
        ("AD-AS模型","AD-AS Model","总需求总供给模型。"),
        ("菲利普斯曲线","Phillips Curve","失业与通胀的反向关系。"),
    ]),
    ("宏观经济·货币与财政", [
        ("货币供给","Money Supply","流通中的货币总量。"),
        ("货币需求","Money Demand","持有货币的意愿。"),
        ("流动性偏好","Liquidity Preference","持有货币的偏好。"),
        ("利率","Interest Rate","资金的价格。"),
        ("名义利率","Nominal Interest Rate","未调整通胀的利率。"),
        ("实际利率","Real Interest Rate","调整通胀后的利率。"),
        ("费雪方程","Fisher Equation","名义利率=实际利率+通胀率。"),
        ("货币政策","Monetary Policy","央行调节货币供给的政策。"),
        ("财政政策","Fiscal Policy","政府调节支出和税收的政策。"),
        ("公开市场操作","Open Market Operations","央行买卖国债。"),
        ("存款准备金率","Reserve Requirement","银行必须保留的存款比例。"),
        ("再贴现率","Discount Rate","央行向银行贷款的利率。"),
        ("量化宽松","Quantitative Easing","央行大规模购买资产。"),
        ("通货膨胀","Inflation","一般价格水平持续上升。"),
        ("通货紧缩","Deflation","一般价格水平持续下降。"),
        ("滞胀","Stagflation","高通胀与高失业并存。"),
        ("消费者价格指数","CPI","消费品价格变化的指标。"),
        ("生产者价格指数","PPI","生产资料价格变化的指标。"),
        ("GDP平减指数","GDP Deflator","名义GDP与实际GDP之比。"),
        ("税收","Taxation","政府强制征收。"),
        ("国债","Government Debt","政府累计借款。"),
        ("预算赤字","Budget Deficit","支出大于收入。"),
        ("预算盈余","Budget Surplus","收入大于支出。"),
        ("拉弗曲线","Laffer Curve","税率与税收收入的关系。"),
        ("自动稳定器","Automatic Stabilizer","自动调节经济的财政机制。"),
    ]),
    ("宏观经济·经济周期与增长", [
        ("经济周期","Business Cycle","经济活动的波动。"),
        ("繁荣","Boom","经济活动的高峰。"),
        ("衰退","Recession","经济活动的下降。"),
        ("萧条","Depression","严重的经济衰退。"),
        ("复苏","Recovery","经济活动的回升。"),
        ("经济增长","Economic Growth","GDP的长期增加。"),
        ("索洛模型","Solow Model","新古典增长模型。"),
        ("内生增长","Endogenous Growth","技术进步内生的增长理论。"),
        ("全要素生产率","Total Factor Productivity","技术进步的综合度量。"),
        ("收敛","Convergence","穷国追上富国的趋势。"),
        ("人力资本","Human Capital","劳动者的技能和知识。"),
        ("制度","Institutions","经济运行的规则体系。"),
        ("技术进步","Technological Progress","生产技术的改善。"),
        ("研发","R&D","研究与开发投入。"),
        ("创新","Innovation","新技术的商业化。"),
        ("创造性破坏","Creative Destruction","熊彼特关于创新的概念。"),
    ]),
    ("国际经济", [
        ("比较优势","Comparative Advantage","相对效率优势决定贸易。"),
        ("绝对优势","Absolute Advantage","绝对效率优势。"),
        ("要素禀赋","Factor Endowment","国家拥有的要素比例。"),
        ("赫克歇尔-俄林模型","Heckscher-Ohlin Model","要素禀赋决定贸易模式。"),
        ("关税","Tariff","对进口商品征收的税。"),
        ("配额","Quota","进口数量的限制。"),
        ("补贴","Subsidy","政府对企业的财政支持。"),
        ("倾销","Dumping","低于成本价出口。"),
        ("反倾销","Anti-dumping","对倾销的报复措施。"),
        ("自由贸易","Free Trade","无贸易壁垒的贸易。"),
        ("贸易保护","Trade Protection","限制进口保护国内产业。"),
        ("汇率","Exchange Rate","两国货币的兑换比率。"),
        ("固定汇率","Fixed Exchange Rate","汇率固定不变。"),
        ("浮动汇率","Floating Exchange Rate","汇率由市场决定。"),
        ("购买力平价","Purchasing Power Parity","汇率反映购买力。"),
        ("国际收支","Balance of Payments","国际交易的记录。"),
        ("经常账户","Current Account","贸易和收入的记录。"),
        ("资本账户","Capital Account","资本流动的记录。"),
        ("外汇储备","Foreign Exchange Reserves","央行持有的外币。"),
        ("布雷顿森林体系","Bretton Woods System","二战后国际货币体系。"),
        ("金本位","Gold Standard","以黄金为基础的货币制度。"),
        ("蒙代尔-弗莱明模型","Mundell-Fleming Model","开放经济下的IS-LM模型。"),
        ("不可能三角","Impossible Trinity","固定汇率、资本自由流动和独立货币政策不可兼得。"),
        ("最优化货币区","Optimal Currency Area","适合使用统一货币的区域。"),
        ("欧元区","Eurozone","使用欧元的区域。"),
    ]),
    ("发展经济学", [
        ("发展中国家","Developing Country","人均收入较低的国家。"),
        ("贫困陷阱","Poverty Trap","低收入导致持续贫困的循环。"),
        ("贫困线","Poverty Line","区分贫困的收入标准。"),
        ("基尼系数","Gini Coefficient","收入不平等度量。"),
        ("人类发展指数","HDI","联合国综合发展指标。"),
        ("结构转型","Structural Transformation","经济结构的根本变化。"),
        ("工业化","Industrialization","制造业比重上升。"),
        ("城市化","Urbanization","城市人口比重上升。"),
        ("人口转型","Demographic Transition","出生率和死亡率的变化模式。"),
        ("刘易斯模型","Lewis Model","二元经济中的劳动力转移。"),
        ("中等收入陷阱","Middle Income Trap","中等收入国家难以进入高收入。"),
        ("外国直接投资","FDI","外国对本国的直接投资。"),
        ("援助","Foreign Aid","国际发展援助。"),
        ("微金融","Microfinance","小额贷款服务。"),
        ("制度与发展","Institutions and Development","制度对经济发展的影响。"),
        ("包容性增长","Inclusive Growth","惠及全体人民的增长。"),
    ]),
    ("行为经济学", [
        ("有限理性","Bounded Rationality","人的理性是有限的。"),
        ("前景理论","Prospect Theory","卡尼曼关于风险决策的理论。"),
        ("损失厌恶","Loss Aversion","对损失比收益更敏感。"),
        ("锚定效应","Anchoring Effect","初始信息影响判断。"),
        ("框架效应","Framing Effect","表述方式影响决策。"),
        ("禀赋效应","Endowment Effect","拥有物估价更高。"),
        ("现状偏差","Status Quo Bias","偏好维持现状。"),
        ("心理账户","Mental Accounting","不同来源的收入不同对待。"),
        ("公平偏好","Fairness Preference","关注公平而非仅自身利益。"),
        ("互惠","Reciprocity","以德报德以怨报怨。"),
        ("自我控制问题","Self-Control Problems","时间不一致的偏好。"),
        ("双曲贴现","Hyperbolic Discounting","对近期收益过度偏好。"),
        ("启发式","Heuristics","决策的捷径。"),
        ("可得性启发","Availability Heuristic","以容易回忆的信息判断。"),
        ("代表性启发","Representativeness Heuristic","以相似性判断概率。"),
        ("确认偏误","Confirmation Bias","偏好确认已有信念的信息。"),
    ]),
    ("金融经济学", [
        ("风险","Risk","结果的不确定性。"),
        ("风险溢价","Risk Premium","承担风险的额外回报。"),
        ("系统性风险","Systematic Risk","不可分散的市场风险。"),
        ("非系统性风险","Unsystematic Risk","可分散的特定风险。"),
        ("多元化","Diversification","分散投资降低风险。"),
        ("资本资产定价模型","CAPM","资产定价的均衡模型。"),
        ("套利定价理论","APT","多因素资产定价模型。"),
        ("有效市场假说","EMH","价格反映所有信息。"),
        ("行为金融","Behavioral Finance","行为偏差影响金融决策。"),
        ("期权","Option","未来买卖的权利。"),
        ("期货","Futures","未来交割的合约。"),
        ("套利","Arbitrage","无风险获利的交易。"),
        ("对冲","Hedging","降低风险的交易。"),
        ("杠杆","Leverage","借贷放大投资。"),
        ("做空","Short Selling","卖出借入的证券。"),
        ("流动性","Liquidity","快速变现的能力。"),
        ("久期","Duration","债券价格对利率的敏感度。"),
        ("凸性","Convexity","久期对利率变化的敏感度。"),
        ("在险价值","VaR","给定置信水平下的最大损失。"),
        ("布莱克-斯科尔斯模型","Black-Scholes Model","期权定价模型。"),
    ]),
    ("公共经济学", [
        ("公共物品","Public Good","非排他且非竞争的物品。"),
        ("外部性","Externality","影响第三方的效应。"),
        ("正外部性","Positive Externality","有益于第三方。"),
        ("负外部性","Negative Externality","有害于第三方。"),
        ("搭便车","Free Riding","不付费用享受公共物品。"),
        ("公地悲剧","Tragedy of the Commons","公共资源的过度使用。"),
        ("庇古税","Pigouvian Tax","矫正外部性的税收。"),
        ("科斯定理","Coase Theorem","产权明晰下市场可以解决外部性。"),
        ("政府失灵","Government Failure","政府干预的低效。"),
        ("市场失灵","Market Failure","市场无法有效配置资源。"),
        ("公共选择","Public Choice","用经济学分析政治决策。"),
        ("投票悖论","Voting Paradox","多数投票可能不一致。"),
        ("阿罗不可能定理","Arrow's Impossibility Theorem","不存在完美的投票规则。"),
        ("寻租","Rent Seeking","为获取经济租而消耗资源。"),
        ("税收原则","Tax Principles","公平与效率的权衡。"),
        ("转移支付","Transfer Payment","政府无对价的支出。"),
    ]),
    ("产业组织", [
        ("市场力量","Market Power","影响价格的能力。"),
        ("勒纳指数","Lerner Index","价格偏离边际成本的程度。"),
        ("赫芬达尔指数","Herfindahl Index","市场集中度度量。"),
        ("进入壁垒","Barriers to Entry","新企业进入的障碍。"),
        ("退出壁垒","Barriers to Exit","企业退出的障碍。"),
        ("研发竞争","R&D Competition","企业间的研发竞赛。"),
        ("网络效应","Network Effects","用户数量增加提升价值。"),
        ("锁定效应","Lock-in Effect","转换成本导致用户被锁定。"),
        ("平台经济","Platform Economy","双边市场的经济形态。"),
        ("双边市场","Two-Sided Market","连接两类用户的市场。"),
        ("纵向一体化","Vertical Integration","上下游整合。"),
        ("横向一体化","Horizontal Integration","同业整合。"),
        ("反垄断","Antitrust","反对垄断的法律政策。"),
        ("并购","Merger & Acquisition","企业合并和收购。"),
        ("价格战","Price War","企业间竞相降价。"),
        ("产品差异化","Product Differentiation","产品特征的差异化。"),
    ]),
    ("劳动经济学", [
        ("劳动参与率","Labor Force Participation Rate","劳动力占人口比例。"),
        ("失业","Unemployment","有劳动能力且愿意工作但无工作。"),
        ("摩擦性失业","Frictional Unemployment","工作转换中的失业。"),
        ("结构性失业","Structural Unemployment","经济结构变化导致的失业。"),
        ("周期性失业","Cyclical Unemployment","经济衰退导致的失业。"),
        ("自然失业率","Natural Rate of Unemployment","正常情况下的失业率。"),
        ("效率工资","Efficiency Wage","高于市场出清的工资。"),
        ("最低工资","Minimum Wage","法律规定的最低工资。"),
        ("工会","Labor Union","工人的集体组织。"),
        ("集体谈判","Collective Bargaining","工会与企业谈判。"),
        ("歧视","Discrimination","基于非生产特征的差别对待。"),
        ("内部人-外部人模型","Insider-Outsider Model","在职工人与失业工人的区分。"),
        ("搜寻理论","Search Theory","求职搜寻的理论。"),
        ("匹配函数","Matching Function","求职与岗位的匹配。"),
        ("补偿性工资差异","Compensating Differential","工作特征差异导致的工资差异。"),
    ]),
    ("计量经济学", [
        ("回归分析","Regression Analysis","估计变量关系的方法。"),
        ("最小二乘法","OLS","最小化残差平方和的估计方法。"),
        ("内生性","Endogeneity","解释变量与误差项相关。"),
        ("工具变量","Instrumental Variable","解决内生性的方法。"),
        ("异方差","Heteroscedasticity","误差项方差不恒定。"),
        ("自相关","Autocorrelation","误差项序列相关。"),
        ("多重共线性","Multicollinearity","解释变量间高度相关。"),
        ("面板数据","Panel Data","截面与时间序列的混合。"),
        ("时间序列","Time Series","按时间排列的数据。"),
        ("虚拟变量","Dummy Variable","表示类别的二元变量。"),
        ("因果推断","Causal Inference","从数据推断因果关系。"),
        ("双重差分","Difference-in-Differences","估计政策效果的方法。"),
        ("断点回归","Regression Discontinuity","利用断点估计因果。"),
        ("倾向得分匹配","Propensity Score Matching","匹配可比较的样本。"),
        ("自然实验","Natural Experiment","自然形成的随机化。"),
    ]),
    ("经济思想史", [
        ("重商主义","Mercantilism","16-18世纪强调积累贵金属的经济思想。"),
        ("重农学派","Physiocracy","18世纪法国强调农业的经济思想。"),
        ("古典经济学","Classical Economics","斯密、李嘉图等的经济理论。"),
        ("新古典经济学","Neoclassical Economics","边际革命后的经济学。"),
        ("凯恩斯主义","Keynesianism","强调政府干预的经济理论。"),
        ("货币主义","Monetarism","弗里德曼强调货币供给的理论。"),
        ("理性预期","Rational Expectations","卢卡斯等的新古典宏观经济学。"),
        ("供给学派","Supply-Side Economics","强调减税刺激供给。"),
        ("奥地利学派","Austrian School","强调市场和企业家精神。"),
        ("制度经济学","Institutional Economics","强调制度对经济的作用。"),
        ("马克思主义经济学","Marxian Economics","以劳动价值论为基础的经济学。"),
        ("发展经济学","Development Economics","研究发展中国家的经济学。"),
    ]),
]

econ_disc = make_discipline("economics", "经济学", "Economics", "ec", "#1565c0",
    "研究资源配置、生产分配和消费行为的社会科学", econ_cats)
econ_disc["formulas"] = [
    {"name": "GDP核算", "formula": "GDP = C + I + G + (X - M)", "description": "消费+投资+政府支出+净出口", "unit": "元"},
    {"name": "CPI计算", "formula": "CPI = (Σ P₁Q₀ / Σ P₀Q₀) × 100", "description": "报告期价格×基期数量 / 基期价格×基期数量 × 100", "unit": "%"},
    {"name": "需求价格弹性", "formula": "Ed = (ΔQ/Q) / (ΔP/P)", "description": "需求量变化率 / 价格变化率", "unit": "无量纲"},
    {"name": "乘数", "formula": "k = 1 / (1 - MPC)", "description": "1 / (1-边际消费倾向)", "unit": "倍"},
    {"name": "现值", "formula": "PV = FV / (1+r)ⁿ", "description": "未来值折算为当前价值", "unit": "元"},
    {"name": "实际利率", "formula": "r_real ≈ r_nominal - π", "description": "名义利率减去通货膨胀率（费雪方程近似）", "unit": "%"},
]
econ_disc["standards"] = [
    {"name": "国民经济行业分类", "code": "GB/T 4754", "description": "中国国民经济行业分类标准。"},
    {"name": "国际经济分类", "code": "ISIC Rev.5", "description": "联合国国际标准行业分类第五版。"},
]
disciplines.append(econ_disc)
print(f"Economics: {len(econ_disc['glossary'])} terms")


# ============================================================
# 3-13: Generate remaining disciplines with comprehensive data
# ============================================================

# We'll use a pattern: each discipline has multiple sub-categories with terms
# To reach 500+ per discipline, we need ~15-20 categories × ~30 terms each

# ---- 3. 法学 Law ----
law_cats = [
    ("法理学", [
        ("法","Law","由国家制定或认可并以国家强制力保证实施的行为规范。"),
        ("法律","Statute","立法机关制定的规范性文件。"),
        ("法治","Rule of Law","依法治理国家的原则。"),
        ("法制","Legal System","法律和制度的总称。"),
        ("法系","Legal Family","具有共同法律传统的国家群体。"),
        ("大陆法系","Civil Law System","以罗马法为基础的法系。"),
        ("英美法系","Common Law System","以判例法为基础的法系。"),
        ("社会主义法系","Socialist Law System","以社会主义法律制度为基础的法系。"),
        ("法的渊源","Sources of Law","法律的表现形式。"),
        ("法律效力","Legal Validity","法律的约束力。"),
        ("法律解释","Legal Interpretation","对法律含义的阐明。"),
        ("法律推理","Legal Reasoning","法律适用的逻辑推理。"),
        ("法律关系","Legal Relation","法律调整的社会关系。"),
        ("权利","Right","法律赋予主体的利益。"),
        ("义务","Obligation","法律要求主体履行的责任。"),
        ("权力","Power","国家机关行使的职权。"),
        ("法律责任","Legal Liability","违法行为的法律后果。"),
        ("法律行为","Legal Act","以意思表示为要素的行为。"),
        ("法律事件","Legal Event","不以当事人意志为转移的法律事实。"),
        ("法的价值","Value of Law","法律追求的目标如正义、自由、秩序。"),
        ("正义","Justice","公平合理的价值理念。"),
        ("自由","Freedom","不受非法限制的状态。"),
        ("秩序","Order","社会关系的稳定状态。"),
        ("效率","Efficiency","法律资源配置的效果。"),
        ("安全","Security","法律保护的安定状态。"),
    ]),
    ("宪法", [
        ("宪法","Constitution","国家的根本法。"),
        ("宪政","Constitutionalism","依宪法治理的政治制度。"),
        ("人民主权","Popular Sovereignty","国家权力属于人民。"),
        ("基本权利","Fundamental Rights","宪法保障的公民权利。"),
        ("平等权","Right to Equality","法律面前人人平等。"),
        ("自由权","Right to Liberty","人身和行动自由。"),
        ("选举权","Right to Vote","公民参与选举的权利。"),
        ("表达自由","Freedom of Expression","言论、出版等自由。"),
        ("宗教信仰自由","Freedom of Religion","信仰宗教的自由。"),
        ("国家结构","State Structure","国家整体与部分的组成关系。"),
        ("单一制","Unitary State","中央集权的国家结构。"),
        ("联邦制","Federal State","中央与地方分权的国家结构。"),
        ("政权组织","Form of Government","国家政权的组织形式。"),
        ("人民代表大会制","People's Congress System","中国的根本政治制度。"),
        ("三权分立","Separation of Powers","立法、行政、司法分立制衡。"),
        ("违宪审查","Constitutional Review","审查法律是否违宪。"),
        ("宪法修正案","Constitutional Amendment","修改宪法的法案。"),
        ("国家机构","State Organs","宪法规定的国家机关。"),
        ("国家元首","Head of State","国家的最高代表。"),
        ("地方自治","Local Autonomy","地方自主管理的权力。"),
    ]),
    ("民法", [
        ("民事权利能力","Civil Capacity","享有民事权利的资格。"),
        ("民事行为能力","Civil Capacity for Act","独立实施民事行为的能力。"),
        ("自然人","Natural Person","基于出生而取得主体资格的人。"),
        ("法人","Legal Person","具有民事权利能力和行为能力的组织。"),
        ("非法人组织","Unincorporated Organization","不具备法人资格的组织。"),
        ("物权","Property Right","直接支配物的权利。"),
        ("所有权","Ownership","全面支配物的权利。"),
        ("用益物权","Usufructuary Right","使用收益他人之物的权利。"),
        ("担保物权","Security Interest","担保债权实现的他物权。"),
        ("抵押权","Mortgage","不转移占有的担保物权。"),
        ("质权","Pledge","转移占有的担保物权。"),
        ("留置权","Lien","合法占有他人动产的担保物权。"),
        ("善意取得","Bona Fide Acquisition","善意第三人取得所有权。"),
        ("债权","Creditor's Right","请求他人为一定行为的权利。"),
        ("合同","Contract","平等主体间的协议。"),
        ("要约","Offer","订立合同的意思表示。"),
        ("承诺","Acceptance","同意要约的意思表示。"),
        ("违约责任","Liability for Breach","违反合同的法律后果。"),
        ("侵权责任","Tort Liability","侵害他人民事权益的法律后果。"),
        ("不当得利","Unjust Enrichment","无合法依据获得利益。"),
        ("无因管理","Voluntary Service","无义务管理他人事务。"),
        ("人格权","Personality Right","与人格利益相关的权利。"),
        ("婚姻家庭","Marriage and Family","婚姻家庭关系的法律调整。"),
        ("继承","Inheritance","遗产的转移。"),
        ("诉讼时效","Limitation of Action","权利人请求法院保护的权利期限。"),
    ]),
    ("刑法", [
        ("犯罪","Crime","危害社会且应受刑罚的行为。"),
        ("刑罚","Punishment","国家对犯罪人的制裁。"),
        ("犯罪构成","Elements of Crime","犯罪客体、客观方面、主体、主观方面。"),
        ("犯罪客体","Object of Crime","刑法保护的社会关系。"),
        ("犯罪客观方面","Objective Aspect","犯罪的外在表现。"),
        ("犯罪主体","Subject of Crime","实施犯罪的人。"),
        ("犯罪主观方面","Subjective Aspect","犯罪的心理状态。"),
        ("故意","Intention","明知且希望或放任结果发生。"),
        ("过失","Negligence","应预见而未预见或轻信能避免。"),
        ("正当防卫","Justifiable Defense","为制止不法侵害的反击。"),
        ("紧急避险","Emergency Avoidance","为免受危险损害合法权益的行为。"),
        ("犯罪未遂","Criminal Attempt","已着手实行但未得逞。"),
        ("犯罪中止","Criminal Discontinuance","自动放弃犯罪。"),
        ("共同犯罪","Joint Crime","二人以上共同故意犯罪。"),
        ("主犯","Principal","组织领导犯罪集团或起主要作用。"),
        ("从犯","Accomplice","起次要或辅助作用。"),
        ("胁从犯","Coerced Accomplice","被胁迫参加犯罪。"),
        ("教唆犯","Instigator","教唆他人犯罪。"),
        ("有期徒刑","Fixed-Term Imprisonment","一定期限的监禁。"),
        ("无期徒刑","Life Imprisonment","终身监禁。"),
        ("死刑","Death Penalty","剥夺生命的刑罚。"),
        ("罚金","Fine","强制缴纳金钱。"),
        ("剥夺政治权利","Deprivation of Political Rights","剥夺政治权利的附加刑。"),
        ("没收财产","Confiscation of Property","没收个人财产。"),
        ("累犯","Recidivist","再次犯罪的人。"),
        ("自首","Surrender","自动投案如实供述。"),
        ("立功","Meritorious Service","揭发他人犯罪。"),
        ("数罪并罚","Concurrent Punishment","对多个犯罪合并处罚。"),
        ("缓刑","Probation","暂不执行刑罚。"),
        ("减刑","Commutation of Sentence","减轻刑罚。"),
        ("假释","Parole","提前释放但附条件。"),
        ("追诉时效","Limitation of Prosecution","追究刑事责任的时间限制。"),
    ]),
    ("行政法", [
        ("行政行为","Administrative Act","行政机关行使职权的行为。"),
        ("行政许可","Administrative License","行政机关准予从事特定活动。"),
        ("行政处罚","Administrative Penalty","对违法行为的制裁。"),
        ("行政强制","Administrative Coercion","强制履行义务的措施。"),
        ("行政复议","Administrative Reconsideration","对行政行为的内部审查。"),
        ("行政诉讼","Administrative Litigation","对行政行为的司法审查。"),
        ("国家赔偿","State Compensation","国家对违法行政行为的赔偿。"),
        ("行政程序","Administrative Procedure","行政行为的步骤和方式。"),
        ("行政裁量","Administrative Discretion","行政机关的裁量权。"),
        ("行政法规","Administrative Regulation","国务院制定的规范性文件。"),
        ("行政规章","Administrative Rule","部门或地方政府制定的规章。"),
        ("行政指导","Administrative Guidance","非强制性的行政建议。"),
        ("行政合同","Administrative Contract","行政机关与相对人的合同。"),
        ("行政事实行为","Administrative Factual Act","不产生法律效果的行为。"),
        ("政府信息公开","Government Information Disclosure","公开政府信息的义务。"),
        ("听证","Hearing","听取当事人意见的程序。"),
        ("行政相对人","Administrative Counterpart","行政行为指向的对象。"),
        ("行政主体","Administrative Subject","行使行政权的组织。"),
        ("管辖","Jurisdiction","行政机关的权限划分。"),
        ("送达","Service","法律文书的交付。"),
    ]),
    ("经济法", [
        ("反垄断法","Antitrust Law","反对垄断行为的法律。"),
        ("反不正当竞争法","Anti-Unfair Competition Law","反对不正当竞争的法律。"),
        ("消费者权益保护法","Consumer Protection Law","保护消费者权益的法律。"),
        ("产品质量法","Product Quality Law","规范产品质量的法律。"),
        ("公司法","Company Law","规范公司组织的法律。"),
        ("证券法","Securities Law","规范证券市场的法律。"),
        ("票据法","Negotiable Instruments Law","规范票据的法律。"),
        ("保险法","Insurance Law","规范保险的法律。"),
        ("破产法","Bankruptcy Law","规范破产程序的法律。"),
        ("税法","Tax Law","规范税收的法律。"),
        ("银行法","Banking Law","规范银行的法律。"),
        ("财政法","Fiscal Law","规范财政收支的法律。"),
        ("会计法","Accounting Law","规范会计的法律。"),
        ("审计法","Audit Law","规范审计的法律。"),
        ("土地管理法","Land Administration Law","规范土地管理的法律。"),
        ("环境保护法","Environmental Protection Law","保护环境的法律。"),
        ("价格法","Price Law","规范价格的法律。"),
        ("广告法","Advertising Law","规范广告的法律。"),
        ("电子商务法","E-Commerce Law","规范电子商务的法律。"),
        ("数据安全法","Data Security Law","规范数据安全的法律。"),
    ]),
    ("诉讼法", [
        ("民事诉讼","Civil Litigation","解决民事纠纷的诉讼。"),
        ("刑事诉讼","Criminal Litigation","追究刑事责任的诉讼。"),
        ("行政诉讼","Administrative Litigation","审查行政行为的诉讼。"),
        ("管辖","Jurisdiction","法院受理案件的权限。"),
        ("级别管辖","Level Jurisdiction","上下级法院的分工。"),
        ("地域管辖","Territorial Jurisdiction","同级法院的分工。"),
        ("专属管辖","Exclusive Jurisdiction","法律规定的专属管辖。"),
        ("协议管辖","Agreed Jurisdiction","当事人约定的管辖。"),
        ("起诉","Filing a Lawsuit","向法院提起诉讼。"),
        ("受理","Acceptance","法院接受案件。"),
        ("审理","Trial","法院审查案件。"),
        ("判决","Judgment","法院的裁判。"),
        ("裁定","Ruling","法院的程序性决定。"),
        ("调解","Mediation","第三方协助解决纠纷。"),
        ("和解","Settlement","当事人自行达成协议。"),
        ("上诉","Appeal","对一审判决不服请求复审。"),
        ("再审","Retrial","对生效判决的重新审理。"),
        ("执行","Execution","强制实现判决内容。"),
        ("举证责任","Burden of Proof","提供证据的责任。"),
        ("证明标准","Standard of Proof","证据须达到的程度。"),
        ("证据","Evidence","证明案件事实的材料。"),
        ("书证","Documentary Evidence","书面材料。"),
        ("物证","Physical Evidence","物品。"),
        ("证人证言","Testimony","证人的陈述。"),
        ("鉴定意见","Expert Opinion","专家的鉴定结论。"),
        ("视听资料","Audio-Visual Evidence","录音录像。"),
        ("电子数据","Electronic Evidence","电子形式的数据。"),
    ]),
    ("国际法", [
        ("国际公法","Public International Law","调整国家间关系的法律。"),
        ("国际私法","Private International Law","调整涉外民事关系的法律。"),
        ("国际经济法","International Economic Law","调整国际经济关系的法律。"),
        ("条约","Treaty","国家间的书面协议。"),
        ("公约","Convention","多边国际协议。"),
        ("国际习惯","International Custom","国家实践的惯例。"),
        ("一般法律原则","General Principles of Law","各国法律共有的原则。"),
        ("国家主权","State Sovereignty","国家对内的最高权和对外的独立权。"),
        ("国家承认","Recognition of State","承认新国家的法律行为。"),
        ("政府承认","Recognition of Government","承认新政府的法律行为。"),
        ("国家责任","State Responsibility","国家违反国际义务的责任。"),
        ("外交关系","Diplomatic Relations","国家间的外交交往。"),
        ("领事关系","Consular Relations","国家间的领事交往。"),
        ("联合国","United Nations","最重要的国际组织。"),
        ("国际法院","ICJ","联合国的主要司法机关。"),
        ("海洋法","Law of the Sea","规范海洋的法律。"),
        ("领土","Territory","国家管辖的区域。"),
        ("国籍","Nationality","个人属于某国的法律身份。"),
        ("引渡","Extradition","将犯罪嫌疑人移交请求国。"),
        ("庇护","Asylum","给予外国人保护。"),
    ]),
    ("知识产权法", [
        ("著作权","Copyright","文学艺术科学作品的权利。"),
        ("专利权","Patent Right","发明创造的权利。"),
        ("商标权","Trademark Right","商品标识的权利。"),
        ("知识产权","Intellectual Property","创造性智力成果的权利。"),
        ("著作权人身权","Moral Right","作者的精神权利。"),
        ("著作权财产权","Economic Right","作者的经济权利。"),
        ("合理使用","Fair Use","不经许可使用作品的情形。"),
        ("法定许可","Statutory License","法律规定的许可使用。"),
        ("发明专利","Invention Patent","新技术方案。"),
        ("实用新型专利","Utility Model Patent","实用技术方案。"),
        ("外观设计专利","Design Patent","产品外观设计。"),
        ("注册商标","Registered Trademark","经注册的商标。"),
        ("驰名商标","Well-Known Trademark","具有高知名度的商标。"),
        ("地理标志","Geographical Indication","标明产地的标志。"),
        ("商业秘密","Trade Secret","不为公众知悉的技术或经营信息。"),
        ("集成电路布图设计","Integrated Circuit Layout","芯片布图设计权。"),
        ("植物新品种","New Plant Variety","植物育种者的权利。"),
        ("知识产权许可","IP License","许可他人使用知识产权。"),
        ("知识产权转让","IP Transfer","转移知识产权。"),
        ("知识产权侵权","IP Infringement","侵害知识产权的行为。"),
    ]),
    ("劳动法与社会保障法", [
        ("劳动合同","Labor Contract","劳动者与用人单位的合同。"),
        ("劳动法","Labor Law","调整劳动关系的法律。"),
        ("劳动合同法","Labor Contract Law","规范劳动合同的法律。"),
        ("劳动仲裁","Labor Arbitration","解决劳动争议的仲裁。"),
        ("劳动监察","Labor Inspection","监督劳动法执行。"),
        ("工资","Wage","劳动报酬。"),
        ("工时","Working Hours","工作时间。"),
        ("休假","Leave","休息休假。"),
        ("社会保险","Social Insurance","强制保险制度。"),
        ("养老保险","Pension Insurance","老年保障。"),
        ("医疗保险","Medical Insurance","医疗费用保障。"),
        ("失业保险","Unemployment Insurance","失业保障。"),
        ("工伤保险","Work Injury Insurance","工伤保障。"),
        ("生育保险","Maternity Insurance","生育保障。"),
        ("住房公积金","Housing Fund","住房储蓄制度。"),
        ("社会救助","Social Assistance","对困难群体的救助。"),
        ("社会福利","Social Welfare","普遍性福利。"),
        ("最低生活保障","Minimum Living Standard","最低收入保障。"),
    ]),
    ("环境法", [
        ("环境保护法","Environmental Protection Law","环境保护的基本法。"),
        ("环境影响评价","Environmental Impact Assessment","项目实施前的环境评估。"),
        ("排污许可","Emission Permit","排放污染物的许可。"),
        ("生态保护","Ecological Protection","保护生态系统。"),
        ("生物多样性","Biodiversity","生物种类的多样性。"),
        ("气候变化","Climate Change","全球气候变暖。"),
        ("碳排放","Carbon Emission","温室气体排放。"),
        ("碳交易","Carbon Trading","碳排放权交易。"),
        ("环境责任","Environmental Liability","污染者的法律责任。"),
        ("环境公益诉讼","Environmental Public Interest Litigation","保护环境公益的诉讼。"),
    ]),
]
law_disc = make_discipline("law", "法学", "Law", "law", "#c62828",
    "研究法律规范、法律关系和法律制度的学科", law_cats)
law_disc["formulas"] = [
    {"name": "违约金调整", "formula": "违约金 > 实际损失 × 30% → 可请求减少", "description": "约定违约金过分高于造成的损失时，可请求法院或仲裁机构减少。", "reference": "《民法典》第585条"},
    {"name": "诉讼时效", "formula": "一般诉讼时效 = 3年", "description": "自权利人知道或应当知道权利受损之日起计算。", "reference": "《民法典》第188条"},
    {"name": "罚金计算", "formula": "罚金 ≤ 违法所得 × 5倍", "description": "行政处罚中罚款的一般上限。", "reference": "《行政处罚法》"},
]
law_disc["standards"] = [
    {"name": "中华人民共和国民法典", "code": "2020", "description": "中国民事法律的基本法，1260条。"},
    {"name": "刑法罪名规定", "code": "刑法修正案(十二)", "description": "最新刑法修正案关于罪名的调整。"},
]
disciplines.append(law_disc)
print(f"Law: {len(law_disc['glossary'])} terms")


# Save progress to a JSON file for the script to continue in next part
import json
with open(os.path.join(os.path.dirname(__file__), 'gen_disciplines_part1.json'), 'w', encoding='utf-8') as f:
    json.dump(disciplines, f, ensure_ascii=False)

print(f"\nPart 1 done: {len(disciplines)} disciplines saved")
for d in disciplines:
    print(f"  {d['name']}: {len(d['glossary'])} terms")
