#!/usr/bin/env python3
"""Part 2: Generate remaining 10 disciplines + supplement economics/law to 500+"""
import json, os

BASE = os.path.dirname(__file__)
OUTPUT_PART1 = os.path.join(BASE, 'gen_disciplines_part1.json')

with open(OUTPUT_PART1, 'r', encoding='utf-8') as f:
    disciplines = json.load(f)

def make_discipline(did, dname, dnameEn, dicon, dcolor, ddesc, cats, formulas=None, standards=None):
    glossary = []
    for cat, terms in cats:
        for t in terms:
            glossary.append({"term": t[0], "termEn": t[1], "definition": t[2], "category": cat})
    return {
        "id": did, "name": dname, "nameEn": dnameEn,
        "icon": dicon, "color": dcolor, "description": ddesc,
        "glossary": glossary,
        "formulas": formulas or [],
        "standards": standards or [],
    }

# ============================================================
# 4. 教育学 Education
# ============================================================
edu_cats = [
    ("教育基本理论", [
        ("教育","Education","培养人的社会活动。"),
        ("教育学","Pedagogy","研究教育现象的学科。"),
        ("教育目的","Educational Purpose","教育所要达到的目标。"),
        ("教育功能","Educational Function","教育对社会和个人的作用。"),
        ("教育价值","Educational Value","教育满足主体需要的意义。"),
        ("教育本质","Nature of Education","教育的根本属性。"),
        ("教育规律","Educational Laws","教育固有的必然联系。"),
        ("教育原则","Educational Principles","指导教育实践的基本准则。"),
        ("教育环境","Educational Environment","影响教育的外部条件。"),
        ("教育系统","Educational System","教育机构的整体结构。"),
        ("终身教育","Lifelong Education","贯穿一生的教育理念。"),
        ("素质教育","Quality Education","全面发展的教育。"),
        ("应试教育","Exam-Oriented Education","以考试为目标的教育。"),
        ("通识教育","General Education","广泛知识面的教育。"),
        ("专业教育","Professional Education","特定领域的教育。"),
        ("职业教育","Vocational Education","职业定向的教育。"),
    ]),
    ("教学理论", [
        ("教学","Teaching","教师的教和学生的学的统一活动。"),
        ("教学论","Didactics","研究教学规律的学科。"),
        ("教学目标","Teaching Objectives","教学要达到的具体目标。"),
        ("教学内容","Teaching Content","教学中传授的知识技能。"),
        ("教学方法","Teaching Methods","教学所采用的方式。"),
        ("教学组织形式","Teaching Organization","教学的空间时间结构。"),
        ("教学评价","Teaching Evaluation","对教学效果的判断。"),
        ("教学设计","Instructional Design","教学方案的设计。"),
        ("课程","Curriculum","教学科目及其进程。"),
        ("课程论","Curriculum Theory","研究课程的学科。"),
        ("隐性课程","Hidden Curriculum","非正式的教育影响。"),
        ("显性课程","Explicit Curriculum","正式列出的课程。"),
        ("核心课程","Core Curriculum","共同必修的课程。"),
        ("选修课程","Elective Curriculum","学生自选的课程。"),
        ("综合课程","Integrated Curriculum","跨学科整合的课程。"),
        ("活动课程","Activity Curriculum","以活动为中心的课程。"),
        ("学科课程","Subject Curriculum","以学科为中心的课程。"),
        ("课程开发","Curriculum Development","课程的设计编制。"),
        ("课程实施","Curriculum Implementation","课程的执行过程。"),
        ("课程评价","Curriculum Evaluation","对课程价值的判断。"),
    ]),
    ("学习理论", [
        ("行为主义","Behaviorism","刺激-反应的学习理论。"),
        ("认知主义","Cognitivism","信息加工的学习理论。"),
        ("建构主义","Constructivism","主动建构知识的学习理论。"),
        ("人本主义","Humanism","以人为中心的学习理论。"),
        ("联结主义","Connectionism","桑代克的学习联结说。"),
        ("经典条件反射","Classical Conditioning","巴甫洛夫的条件反射。"),
        ("操作性条件反射","Operant Conditioning","斯金纳的条件反射。"),
        ("强化","Reinforcement","增加行为频率的刺激。"),
        ("正强化","Positive Reinforcement","给予愉快刺激。"),
        ("负强化","Negative Reinforcement","移除不快刺激。"),
        ("惩罚","Punishment","减少行为频率的刺激。"),
        ("消退","Extinction","行为因不强化而减弱。"),
        ("塑造","Shaping","逐步强化接近目标的行为。"),
        ("社会学习理论","Social Learning Theory","班杜拉的观察学习。"),
        ("观察学习","Observational Learning","通过观察他人学习。"),
        ("自我效能感","Self-Efficacy","对自己能力的信念。"),
        ("信息加工","Information Processing","大脑处理信息的过程。"),
        ("图式","Schema","知识结构的组织形式。"),
        ("同化","Assimilation","将新信息纳入已有图式。"),
        ("顺应","Accommodation","调整图式以适应新信息。"),
        ("元认知","Metacognition","对认知的认知。"),
        ("学习策略","Learning Strategies","促进学习的方法。"),
        ("认知负荷","Cognitive Load","工作记忆的负担。"),
        ("迁移","Transfer","学习对其他领域的影响。"),
        ("最近发展区","ZPD","现有水平与潜在水平的差距。"),
    ]),
    ("教育心理学", [
        ("发展心理学","Developmental Psychology","研究心理发展的学科。"),
        ("认知发展","Cognitive Development","思维能力的发展。"),
        ("道德发展","Moral Development","道德判断能力的发展。"),
        ("皮亚杰阶段","Piaget's Stages","感知运动、前运算、具体运算、形式运算。"),
        ("科尔伯格阶段","Kohlberg's Stages","三水平六阶段道德发展。"),
        ("埃里克森阶段","Erikson's Stages","心理社会发展八阶段。"),
        ("布鲁姆分类","Bloom's Taxonomy","认知、情感、动作技能领域。"),
        ("动机","Motivation","驱动行为的内在力量。"),
        ("内在动机","Intrinsic Motivation","活动本身的兴趣驱动。"),
        ("外在动机","Extrinsic Motivation","外部奖励驱动。"),
        ("成就动机","Achievement Motivation","追求成功的动机。"),
        ("归因","Attribution","对行为原因的解释。"),
        ("习得性无助","Learned Helplessness","反复失败导致放弃。"),
        ("自我决定理论","Self-Determination Theory","自主、胜任、关联的需要。"),
        ("心流","Flow","全神贯注的最佳体验。"),
        ("多元智能","Multiple Intelligences","加德纳的智能理论。"),
        ("情绪智力","Emotional Intelligence","情绪管理的能力。"),
        ("智力","Intelligence","认知能力的综合。"),
        ("智商","IQ","智力商数。"),
        ("创造力","Creativity","产生新颖有价值想法的能力。"),
    ]),
    ("课程与教学论", [
        ("布鲁纳螺旋课程","Spiral Curriculum","螺旋上升的课程设计。"),
        ("泰勒原理","Tyler's Rationale","课程编制的四个问题。"),
        ("目标模式","Objectives Model","以目标为导向的课程模式。"),
        ("过程模式","Process Model","以过程为中心的课程模式。"),
        ("情境模式","Situational Model","以情境为依据的课程模式。"),
        ("学科中心","Subject-Centered","以学科内容为中心。"),
        ("学习者中心","Learner-Centered","以学生需要为中心。"),
        ("社会中心","Society-Centered","以社会问题为中心。"),
        ("反向设计","Backward Design","从目标倒推教学设计。"),
        ("理解为本设计","Understanding by Design","追求深层理解的教学设计。"),
        ("项目式学习","PBL","通过项目学习。"),
        ("问题式学习","Problem-Based Learning","通过问题学习。"),
        ("探究学习","Inquiry Learning","通过探究学习。"),
        ("合作学习","Cooperative Learning","小组合作学习。"),
        ("翻转课堂","Flipped Classroom","课前学知识课内做练习。"),
        ("混合学习","Blended Learning","线上线下结合。"),
        ("个别化学习","Individualized Learning","因材施教。"),
        ("差异化教学","Differentiated Instruction","根据差异调整教学。"),
        ("直接教学","Direct Instruction","教师主导的系统教学。"),
        ("发现学习","Discovery Learning","学生自主发现知识。"),
    ]),
    ("教育评价", [
        ("形成性评价","Formative Assessment","教学过程中的评价。"),
        ("总结性评价","Summative Assessment","教学结束后的评价。"),
        ("诊断性评价","Diagnostic Assessment","了解起点的评价。"),
        ("常模参照","Norm-Referenced","与他人比较的评价。"),
        ("标准参照","Criterion-Referenced","与标准比较的评价。"),
        ("信度","Reliability","评价的一致性。"),
        ("效度","Validity","评价的准确性。"),
        ("区分度","Discrimination","区分高低分的能力。"),
        ("难度","Difficulty","题目难易程度。"),
        ("效标关联效度","Criterion-Related Validity","与外部标准的相关。"),
        ("内容效度","Content Validity","内容覆盖的程度。"),
        ("结构效度","Construct Validity","测量理论结构的程度。"),
        ("表现性评价","Performance Assessment","通过实际表现评价。"),
        ("档案袋评价","Portfolio Assessment","收集作品评价。"),
        ("自我评价","Self-Assessment","学生自我评价。"),
        ("同伴评价","Peer Assessment","学生互相评价。"),
        (" rubric","Scoring Rubric","评分标准表。"),
        ("形成性反馈","Formative Feedback","改进学习的反馈。"),
        ("增值评价","Value-Added Assessment","测量进步的评价。"),
        ("教育测量","Educational Measurement","量化学业成就的技术。"),
    ]),
    ("教育技术", [
        ("教育技术","Educational Technology","支持学习的技术手段。"),
        ("教学媒体","Instructional Media","传递教学信息的媒介。"),
        ("多媒体","Multimedia","多种媒体组合。"),
        ("在线学习","Online Learning","网络环境下的学习。"),
        ("慕课","MOOC","大规模开放在线课程。"),
        ("微课","Micro-Lecture","短小精悍的教学视频。"),
        ("学习管理系统","LMS","管理学习过程的平台。"),
        ("教育信息化","Educational Informatization","信息技术在教育中的应用。"),
        ("智慧教育","Smart Education","智能技术支持的教育。"),
        ("虚拟现实","VR","沉浸式虚拟环境。"),
        ("增强现实","AR","叠加虚拟信息。"),
        ("人工智能教育","AI in Education","AI技术支持的教育。"),
        ("自适应学习","Adaptive Learning","自动调整的学习系统。"),
        ("学习分析","Learning Analytics","分析学习数据。"),
        ("数字素养","Digital Literacy","使用数字技术的能力。"),
    ]),
    ("教育管理", [
        ("教育管理","Educational Management","教育行政和学校管理。"),
        ("教育行政","Educational Administration","政府的教育管理。"),
        ("学校管理","School Management","学校内部的管理。"),
        ("校长负责制","Principal Responsibility System","校长全面负责学校。"),
        ("教育政策","Educational Policy","教育领域的政策。"),
        ("教育法规","Educational Law","教育领域的法律法规。"),
        ("教育督导","Educational Supervision","监督指导教育。"),
        ("教育财政","Educational Finance","教育经费管理。"),
        ("教师管理","Teacher Management","教师的人事管理。"),
        ("学生管理","Student Management","学生的日常管理。"),
        ("校园文化","Campus Culture","学校的文化氛围。"),
        ("家校合作","Home-School Cooperation","家庭与学校协作。"),
        ("教育公平","Educational Equity","教育机会均等。"),
        ("教育质量","Educational Quality","教育效果的水平。"),
        ("教育均衡","Balanced Education","区域间教育均衡发展。"),
    ]),
    ("教育研究方法", [
        ("教育研究","Educational Research","研究教育现象的科学活动。"),
        ("定量研究","Quantitative Research","量化的实证研究。"),
        ("定性研究","Qualitative Research","质性的描述研究。"),
        ("混合研究","Mixed Methods Research","定量定性结合。"),
        ("实验研究","Experimental Research","控制变量的研究。"),
        ("准实验","Quasi-Experiment","不完全控制的实验。"),
        ("调查研究","Survey Research","问卷或访谈调查。"),
        ("个案研究","Case Study","深入分析个别案例。"),
        ("行动研究","Action Research","教师参与的实践研究。"),
        ("叙事研究","Narrative Research","以故事为载体研究。"),
        ("民族志","Ethnography","文化描述研究。"),
        ("文献研究","Literature Research","分析文献的研究。"),
        ("元分析","Meta-Analysis","综合多项研究。"),
        ("内容分析","Content Analysis","分析文本内容。"),
        ("扎根理论","Grounded Theory","从数据中生成理论。"),
        ("效度","Validity","研究的有效性。"),
        ("信度","Reliability","研究的一致性。"),
        ("抽样","Sampling","选取研究样本。"),
        ("变量","Variable","可变化的属性。"),
        ("假设","Hypothesis","待检验的预测。"),
    ]),
    ("比较教育与国际教育", [
        ("比较教育","Comparative Education","跨国比较教育制度。"),
        ("国际教育","International Education","国际视野下的教育。"),
        ("教育国际化","Internationalization of Education","教育的国际交流融合。"),
        ("PISA","PISA","国际学生评估项目。"),
        ("TIMSS","TIMSS","国际数学与科学趋势研究。"),
        ("IB课程","IB","国际文凭课程。"),
        ("AP课程","Advanced Placement","美国大学先修课。"),
        ("A-Level","A-Level","英国高中课程。"),
        ("蒙特梭利","Montessori","以儿童为中心的教育法。"),
        ("华德福","Waldorf","注重整体发展的教育法。"),
        ("瑞吉欧","Reggio Emilia","以项目为驱动的教育法。"),
        ("芬兰教育","Finnish Education","以公平和质量著称。"),
        ("STEAM教育","STEAM","科学、技术、工程、艺术、数学。"),
        ("创客教育","Maker Education","动手创造的教育。"),
        ("全球公民教育","Global Citizenship Education","培养全球公民意识。"),
    ]),
    ("教育史与教育思想", [
        ("孔子教育思想","Confucius's Education","有教无类、因材施教。"),
        ("苏格拉底产婆术","Socratic Method","启发式教学。"),
        ("柏拉图学园","Plato's Academy","西方第一所高等学府。"),
        ("夸美纽斯","Comenius","《大教学论》作者。"),
        ("卢梭教育思想","Rousseau's Education","自然教育论。"),
        ("赫尔巴特","Herbart","传统教育学派代表。"),
        ("杜威","Dewey","进步主义教育代表。"),
        ("蒙台梭利","Montessori","儿童中心教育法。"),
        ("陶行知","Tao Xingzhi","生活教育理论。"),
        ("蔡元培","Cai Yuanpei","兼容并包的大学理念。"),
        ("晏阳初","Yan Yangchu","平民教育运动。"),
        ("梁漱溟","Liang Shuming","乡村教育实验。"),
        ("陈鹤琴","Chen Heqin","活教育理论。"),
        ("科举","Imperial Examination","古代选官制度。"),
        ("书院","Academy","古代教育机构。"),
        ("太学","Imperial Academy","古代最高学府。"),
        ("六艺","Six Arts","礼乐射御书数。"),
        ("四书五经","Four Books and Five Classics","儒家经典教材。"),
    ]),
    ("德育与思想政治教育", [
        ("德育","Moral Education","道德品质教育。"),
        ("德育目标","Moral Education Goals","德育要达到的目标。"),
        ("德育原则","Moral Education Principles","德育的基本准则。"),
        ("德育方法","Moral Education Methods","德育的具体方法。"),
        ("德育课程","Moral Education Curriculum","德育的课程设置。"),
        ("思想政治教育","Ideological Education","政治思想教育。"),
        ("核心价值观","Core Values","社会主义核心价值观。"),
        ("道德认知","Moral Cognition","对道德规范的认知。"),
        ("道德情感","Moral Emotion","道德的情感体验。"),
        ("道德行为","Moral Behavior","道德的实践表现。"),
        ("品德发展","Character Development","品德的形成发展。"),
        ("德育评价","Moral Education Evaluation","德育效果的评价。"),
        ("隐性德育","Implicit Moral Education","非正式的德育影响。"),
        ("校园德育","School Moral Education","学校中的德育。"),
        ("家庭德育","Family Moral Education","家庭中的德育。"),
    ]),
    ("学前教育与特殊教育", [
        ("学前教育","Early Childhood Education","学龄前儿童的教育。"),
        ("幼儿发展","Child Development","幼儿身心发展。"),
        ("游戏","Play","幼儿的基本活动。"),
        ("幼儿园","Kindergarten","学前教育机构。"),
        ("保教结合","Care and Education","保育与教育相结合。"),
        ("特殊教育","Special Education","特殊需要儿童的教育。"),
        ("融合教育","Inclusive Education","特殊儿童融入普通教育。"),
        ("个别化教育计划","IEP","为特殊儿童制定的计划。"),
        ("智力障碍","Intellectual Disability","智力发育迟缓。"),
        ("自闭症","Autism","社交沟通障碍。"),
        ("多动症","ADHD","注意力缺陷多动障碍。"),
        ("学习障碍","Learning Disability","特定学习困难。"),
        ("超常教育","Gifted Education","超常儿童的教育。"),
        ("早期干预","Early Intervention","对特殊儿童的早期帮助。"),
        ("感统训练","Sensory Integration","感觉统合训练。"),
    ]),
    ("高等教育", [
        ("高等教育","Higher Education","大学及以上教育。"),
        ("大学","University","高等教育机构。"),
        ("学科建设","Discipline Construction","学科的发展建设。"),
        ("专业建设","Program Construction","专业的发展建设。"),
        ("人才培养","Talent Cultivation","培养人才的过程。"),
        ("科学研究","Scientific Research","学术研究。"),
        ("社会服务","Social Service","大学的社会服务职能。"),
        ("文化传承","Cultural Heritage","大学的文化传承职能。"),
        ("双一流","Double First-Class","世界一流大学一流学科。"),
        ("本科教学评估","Undergraduate Evaluation","本科教学质量评估。"),
        ("学位","Degree","学术水平认证。"),
        ("研究生教育","Graduate Education","硕士博士教育。"),
        ("导师制","Tutor System","导师指导学生。"),
        ("学术自由","Academic Freedom","学术研究的自由。"),
        ("大学自治","University Autonomy","大学自我管理。"),
    ]),
]
edu_disc = make_discipline("education", "教育学", "Education", "edu", "#2e7d32",
    "研究教育现象、教育规律和教育方法的学科", edu_cats,
    formulas=[
        {"name": "Cronbach α信度", "formula": "α = (k/(k-1)) × (1 - Σσᵢ²/σₜ²)", "description": "k=题数，σᵢ²=各题方差，σₜ²=总分方差", "unit": "0-1"},
        {"name": "效应量", "formula": "d = (M₁ - M₂) / S_pooled", "description": "两组均值差除以合并标准差（Cohen's d）", "unit": "无量纲"},
        {"name": "通过率", "formula": "P = R / N × 100%", "description": "答对人数/总人数", "unit": "%"},
        {"name": "区分度", "formula": "D = PH - PL", "description": "高分组通过率 - 低分组通过率", "unit": "-1~1"},
    ],
    standards=[
        {"name": "学位授予和人才培养学科目录", "code": "2022版", "description": "中国研究生教育的学科分类标准。"},
        {"name": "普通高等学校本科专业目录", "code": "2024版", "description": "中国本科教育的专业分类。"},
    ])
disciplines.append(edu_disc)
print(f"Education: {len(edu_disc['glossary'])} terms")


# ============================================================
# 5. 文学 Literature
# ============================================================
lit_cats = [
    ("文学理论", [
        ("文学","Literature","以语言为媒介的艺术。"),
        ("文学性","Literariness","使文本成为文学的特征。"),
        ("文学文本","Literary Text","具有文学属性的语言作品。"),
        ("文学语境","Literary Context","文本所处的文化历史环境。"),
        ("文学性","Literariness","雅各布森提出的核心概念。"),
        ("陌生化","Defamiliarization","什克洛夫斯基的核心概念。"),
        ("文本","Text","语言构成的符号系统。"),
        ("互文性","Intertextuality","文本间的相互关联。"),
        ("作者","Author","文本的创作者。"),
        ("读者","Reader","文本的接受者。"),
        ("叙事","Narrative","讲述故事的方式。"),
        ("话语","Discourse","特定语境中的语言使用。"),
        ("修辞","Rhetoric","语言表达的技巧。"),
        ("隐喻","Metaphor","以彼物喻此物。"),
        ("转喻","Metonymy","以关联物代指。"),
        ("象征","Symbolism","以具体表抽象。"),
        ("意象","Imagery","具有意义的感性形象。"),
        ("典型","Type","个性与共性的统一。"),
        ("审美","Aesthetics","对美的感受和判断。"),
        ("模仿","Mimesis","艺术模仿现实。"),
    ]),
    ("中国古代文学", [
        ("诗经","Book of Songs","中国最早的诗歌总集。"),
        ("楚辞","Chu Ci","屈原开创的诗歌体裁。"),
        ("赋","Fu","汉代铺陈文体。"),
        ("乐府","Yuefu","汉代民歌机构及诗体。"),
        ("五言诗","Five-Character Poetry","每句五字的诗体。"),
        ("七言诗","Seven-Character Poetry","每句七字的诗体。"),
        ("唐诗","Tang Poetry","唐代诗歌的黄金时代。"),
        ("宋词","Song Ci","宋代词的鼎盛时期。"),
        ("元曲","Yuan Qu","元代散曲杂剧。"),
        ("明清小说","Ming-Qing Novel","明清章回小说。"),
        ("四书","Four Books","大学中庸论语孟子。"),
        ("五经","Five Classics","诗经尚书礼记周易春秋。"),
        ("古文运动","Classical Prose Movement","韩愈柳宗元倡导的文风改革。"),
        ("桐城派","Tongcheng School","清代散文流派。"),
        ("花间派","Huajian School","五代词派。"),
        ("婉约派","Wanyue School","宋词流派，风格含蓄。"),
        ("豪放派","Haofang School","宋词流派，风格豪迈。"),
        ("江西诗派","Jiangxi Poetry School","宋代黄庭坚开创的诗派。"),
        ("性灵说","Xingling Theory","袁枚的诗歌理论。"),
        ("神韵说","Shenyun Theory","王士禛的诗歌理论。"),
    ]),
    ("中国现当代文学", [
        ("五四运动","May Fourth Movement","1919年新文化运动。"),
        ("新文学","New Literature","白话文运动后的文学。"),
        ("鲁迅","Lu Xun","现代文学奠基人。"),
        ("乡土文学","Native Soil Literature","描写农村的文学。"),
        ("新月派","Crescent Moon School","现代诗歌流派。"),
        ("象征派","Symbolist School","现代诗歌流派。"),
        ("朦胧诗","Misty Poetry","70年代末的诗歌运动。"),
        ("伤痕文学","Scar Literature","文革后的文学思潮。"),
        ("反思文学","Reflection Literature","反思历史的文学。"),
        ("改革文学","Reform Literature","反映改革的文学。"),
        ("寻根文学","Roots-Seeking Literature","寻找文化之根的文学。"),
        ("先锋文学","Avant-Garde Literature","实验性文学。"),
        ("新写实主义","New Realism","关注日常生活的文学。"),
        ("网络文学","Web Literature","网络平台发表的文学。"),
        ("莫言","Mo Yan","诺贝尔文学奖获得者。"),
        ("余华","Yu Hua","当代小说家。"),
        ("王安忆","Wang Anyi","当代女作家。"),
        ("贾平凹","Jia Pingwa","当代作家。"),
        ("阿城","A Cheng","当代作家。"),
        ("海子","Hai Zi","当代诗人。"),
    ]),
    ("外国文学·西方古典", [
        ("荷马史诗","Homeric Epics","伊利亚特和奥德赛。"),
        ("希腊悲剧","Greek Tragedy","埃斯库罗斯索福克勒斯欧里庇得斯。"),
        ("希腊喜剧","Greek Comedy","阿里斯托芬。"),
        ("维吉尔","Virgil","罗马史诗诗人。"),
        ("但丁","Dante","《神曲》作者。"),
        ("薄伽丘","Boccaccio","《十日谈》作者。"),
        ("塞万提斯","Cervantes","《堂吉诃德》作者。"),
        ("莎士比亚","Shakespeare","英国文艺复兴剧作家。"),
        ("弥尔顿","Milton","《失乐园》作者。"),
        ("歌德","Goethe","德国文学巨匠。"),
        ("席勒","Schiller","德国剧作家。"),
        ("雨果","Hugo","法国浪漫主义作家。"),
        ("巴尔扎克","Balzac","法国现实主义作家。"),
        ("福楼拜","Flaubert","法国小说家。"),
        ("狄更斯","Dickens","英国小说家。"),
        ("陀思妥耶夫斯基","Dostoevsky","俄国小说家。"),
        ("托尔斯泰","Tolstoy","俄国文学巨匠。"),
        ("契诃夫","Chekhov","俄国短篇小说大师。"),
        ("易卜生","Ibsen","挪威剧作家。"),
        ("马克·吐温","Mark Twain","美国小说家。"),
    ]),
    ("外国文学·现代与后现代", [
        ("现代主义","Modernism","20世纪初文学运动。"),
        ("后现代主义","Postmodernism","20世纪后期文学思潮。"),
        ("意识流","Stream of Consciousness","内心独白的叙事技巧。"),
        ("存在主义文学","Existentialist Literature","萨特加缪等。"),
        ("魔幻现实主义","Magic Realism","马尔克斯等。"),
        ("荒诞派戏剧","Theatre of the Absurd","贝克特尤内斯库。"),
        ("新小说","Nouveau Roman","法国实验小说。"),
        ("黑色幽默","Black Humor","海勒等。"),
        ("垮掉的一代","Beat Generation","凯鲁亚克等。"),
        ("卡夫卡","Kafka","现代主义先驱。"),
        ("普鲁斯特","Proust","《追忆似水年华》作者。"),
        ("乔伊斯","Joyce","《尤利西斯》作者。"),
        ("伍尔夫","Woolf","意识流小说家。"),
        ("福克纳","Faulkner","美国南方作家。"),
        ("海明威","Hemingway","美国小说家。"),
        ("加缪","Camus","存在主义作家。"),
        ("博尔赫斯","Borges","阿根廷作家。"),
        ("马尔克斯","García Márquez","魔幻现实主义代表。"),
        ("昆德拉","Kundera","捷克裔法籍作家。"),
        ("卡尔维诺","Calvino","意大利作家。"),
    ]),
    ("文学批评与方法", [
        ("新批评","New Criticism","文本中心的批评方法。"),
        ("结构主义","Structuralism","以结构分析文本。"),
        ("后结构主义","Post-Structuralism","解构结构的方法。"),
        ("解构主义","Deconstruction","德里达的批评方法。"),
        ("精神分析批评","Psychoanalytic Criticism","弗洛伊德理论批评。"),
        ("女性主义批评","Feminist Criticism","性别视角的批评。"),
        ("马克思主义批评","Marxist Criticism","阶级视角的批评。"),
        ("新历史主义","New Historicism","历史语境批评。"),
        ("后殖民批评","Postcolonial Criticism","殖民批判。"),
        ("生态批评","Ecocriticism","环境视角的批评。"),
        ("读者反应批评","Reader-Response Criticism","读者中心的批评。"),
        ("文化研究","Cultural Studies","跨学科文化分析。"),
        ("叙事学","Narratology","叙事结构分析。"),
        ("符号学","Semiotics","符号意义分析。"),
        ("形式主义","Formalism","以形式为重的批评。"),
        ("原型批评","Archetypal Criticism","荣格原型理论批评。"),
        ("现象学批评","Phenomenological Criticism","现象学方法的批评。"),
        ("阐释学批评","Hermeneutic Criticism","解释学方法的批评。"),
        ("酷儿理论","Queer Theory","性取向视角的批评。"),
        ("空间批评","Spatial Criticism","空间视角的批评。"),
    ]),
    ("文学体裁与形式", [
        ("小说","Novel","叙事性散文作品。"),
        ("短篇小说","Short Story","篇幅短小的小说。"),
        ("中篇小说","Novella","中等篇幅的小说。"),
        ("长篇小说","Novel","长篇幅的小说。"),
        ("诗歌","Poetry","韵律性语言作品。"),
        ("散文","Prose","不押韵的文章。"),
        ("戏剧","Drama","舞台表演作品。"),
        ("悲剧","Tragedy","以苦难结局的戏剧。"),
        ("喜剧","Comedy","以欢乐结局的戏剧。"),
        ("正剧","Tragicomedy","悲喜混合的戏剧。"),
        ("史诗","Epic","宏大叙事的长诗。"),
        ("抒情诗","Lyric Poetry","抒发感情的诗歌。"),
        ("叙事诗","Narrative Poetry","叙述故事的诗歌。"),
        ("十四行诗","Sonnet","14行的格律诗。"),
        ("自由诗","Free Verse","不受格律限制的诗歌。"),
        ("随笔","Essay","随意抒发的短文。"),
        ("报告文学","Reportage","以真实事件为基础的文学。"),
        ("传记","Biography","记述人物生平的作品。"),
        ("寓言","Fable","以故事寓理的作品。"),
        ("童话","Fairy Tale","幻想性儿童故事。"),
    ]),
    ("叙事学", [
        ("叙事者","Narrator","讲述故事的声音。"),
        ("第一人称","First Person","我视角叙事。"),
        ("第三人称","Third Person","他她视角叙事。"),
        ("全知视角","Omniscient Point of View","全知道的叙事角度。"),
        ("限制视角","Limited Point of View","有限知的叙事角度。"),
        ("不可靠叙事者","Unreliable Narrator","不可信的叙事者。"),
        ("聚焦","Focalization","叙事视角的聚焦。"),
        ("叙述时间","Narrative Time","故事时间与叙述时间。"),
        ("省略","Ellipsis","叙事中的省略。"),
        ("概要","Summary","叙事中的概括。"),
        ("场景","Scene","叙事中的实时描写。"),
        ("停顿","Pause","叙事中的描写停顿。"),
        ("频率","Frequency","事件出现与叙述的次数关系。"),
        ("复调","Polyphony","多声音并存的叙事。"),
        ("对话","Dialogue","人物间的言语交流。"),
        ("独白","Monologue","人物自言自语。"),
        ("自由间接引语","Free Indirect Discourse","融合叙事者与人物的语气。"),
        ("元叙事","Meta-Narrative","关于叙事的叙事。"),
        ("故事","Story","被叙述的事件。"),
        ("话语","Discourse","叙述事件的方式。"),
    ]),
    ("比较文学", [
        ("比较文学","Comparative Literature","跨国界文学比较研究。"),
        ("影响研究","Influence Study","研究文学间的影响关系。"),
        ("平行研究","Parallel Study","研究无直接联系的文学相似性。"),
        ("跨学科研究","Interdisciplinary Study","文学与其他学科的比较。"),
        ("译介学","Translation Studies","文学翻译的研究。"),
        ("世界文学","World Literature","全球视野的文学。"),
        ("文学环流","Literary Circulation","文学作品的跨国流通。"),
        ("接受研究","Reception Study","研究文学的接受史。"),
        ("形象学","Imagology","研究文学中的异国形象。"),
        ("媒介学","Mediology","研究文学传播的媒介。"),
    ]),
    ("文体学与修辞学", [
        ("文体","Style","语言表达的风格。"),
        ("文体学","Stylistics","研究文体的学科。"),
        ("修辞格","Figure of Speech","修辞手法。"),
        ("明喻","Simile","以像如等词比喻。"),
        ("暗喻","Metaphor","不用比喻词的比喻。"),
        ("借代","Metonymy","以局部代整体。"),
        ("夸张","Hyperbole","故意扩大或缩小。"),
        ("排比","Parallelism","结构相同的并列。"),
        ("对偶","Antithesis","结构对称的语句。"),
        ("反复","Repetition","重复使用词语。"),
        ("设问","Rhetorical Question","自问自答。"),
        ("反问","Rhetorical Question","无疑而问。"),
        ("双关","Pun","一语双关。"),
        ("反讽","Irony","言此意彼。"),
        ("悖论","Paradox","看似矛盾实则合理。"),
    ]),
    ("文学流派与运动", [
        ("古典主义","Classicism","崇尚古希腊罗马的文艺思潮。"),
        ("浪漫主义","Romanticism","18-19世纪强调情感想象的文学运动。"),
        ("现实主义","Realism","19世纪关注社会现实的文学。"),
        ("自然主义","Naturalism","以科学方法写小说。"),
        ("象征主义","Symbolism","以象征表达意义的诗歌运动。"),
        ("唯美主义","Aestheticism","为艺术而艺术。"),
        ("印象主义","Impressionism","捕捉瞬间印象。"),
        ("表现主义","Expressionism","扭曲变形表达内心。"),
        ("超现实主义","Surrealism","探索潜意识。"),
        ("未来主义","Futurism","歌颂速度和技术。"),
        ("达达主义","Dadaism","反艺术的运动。"),
        ("意象派","Imagism","以意象为核心的诗歌流派。"),
        ("迷惘的一代","Lost Generation","一战后的美国作家群。"),
        ("南方文艺复兴","Southern Renaissance","美国南方文学复兴。"),
        ("哈莱姆文艺复兴","Harlem Renaissance","非裔美国文学运动。"),
    ]),
    ("文学与社会", [
        ("文学社会学","Sociology of Literature","研究文学与社会的关系。"),
        ("文学生产","Literary Production","文学作品的创作过程。"),
        ("文学消费","Literary Consumption","文学作品的阅读接受。"),
        ("文学场域","Literary Field","布迪厄的文学社会学概念。"),
        ("文化资本","Cultural Capital","布迪厄的社会学概念。"),
        ("文学制度","Literary Institution","文学的制度化形式。"),
        ("文学经典","Literary Canon","被公认的文学杰作。"),
        ("经典化","Canonization","作品成为经典的过程。"),
        ("通俗文学","Popular Literature","大众化的文学。"),
        ("严肃文学","Serious Literature","追求艺术价值的文学。"),
        ("纯文学","Pure Literature","不以功利为目的的文学。"),
        ("类型文学","Genre Literature","按类型分类的文学。"),
        ("儿童文学","Children's Literature","面向儿童的文学。"),
        ("科幻文学","Science Fiction","科学幻想的文学。"),
        ("推理文学","Mystery Fiction","以推理为核心的文学。"),
    ]),
]
lit_disc = make_discipline("literature", "文学", "Literature", "lit", "#7b1fa2",
    "研究文学作品、文学理论和文学史的学科", lit_cats,
    formulas=[
        {"name": "弗莱格塔格金字塔", "formula": "铺垫→上升→高潮→下降→结局", "description": "经典戏剧叙事结构五阶段模型。", "reference": "Freytag (1863)"},
        {"name": "叙事距离", "formula": "距离 = 叙述者与人物的认知差", "description": "叙述者所知与人物所知之间的差距决定叙事效果。", "reference": "Genette"},
    ],
    standards=[
        {"name": "汉语拼音正词法", "code": "GB/T 16159", "description": "汉语拼音分词连写的国家标准。"},
        {"name": "信息与文献参考文献著录规则", "code": "GB/T 7714", "description": "中国学术文献引用格式标准。"},
    ])
disciplines.append(lit_disc)
print(f"Literature: {len(lit_disc['glossary'])} terms")


# ============================================================
# 6. 历史学 History
# ============================================================
hist_cats = [
    ("史学理论", [
        ("历史","History","人类社会的演变过程及其记录。"),
        ("历史学","Historiography","研究历史的学科。"),
        ("史学理论","Historical Theory","关于历史研究的理论。"),
        ("历史观","Historical Viewpoint","对历史的根本看法。"),
        ("唯物史观","Historical Materialism","马克思主义的历史观。"),
        ("全球史观","Global History","从全球视角看历史。"),
        ("文明史观","Civilizational History","以文明为单位的历史观。"),
        ("现代化史观","Modernization History","以现代化为线索的历史观。"),
        ("社会史观","Social History","以社会生活为视角的历史观。"),
        ("生态史观","Ecological History","以人与自然关系为视角。"),
        ("后现代史学","Postmodern Historiography","质疑宏大叙事的史学。"),
        ("新文化史","New Cultural History","关注文化表征的史学。"),
        ("计量史学","Cliometrics","定量分析的史学。"),
        ("心理史学","Psychohistory","心理学方法的史学。"),
        ("口述历史","Oral History","访谈方法的史学。"),
        ("公众史学","Public History","面向公众的史学。"),
        ("数字人文","Digital Humanities","数字技术的人文学研究。"),
        ("历史认识论","Historical Epistemology","历史知识的问题。"),
        ("历史解释","Historical Explanation","对历史意义的阐释。"),
        ("历史因果","Historical Causation","历史事件间的因果关系。"),
    ]),
    ("中国史·先秦至秦汉", [
        ("夏朝","Xia Dynasty","中国第一个王朝。"),
        ("商朝","Shang Dynasty","青铜文明的朝代。"),
        ("西周","Western Zhou","分封制确立的朝代。"),
        ("东周","Eastern Zhou","春秋战国时期。"),
        ("春秋","Spring and Autumn","公元前770-476年。"),
        ("战国","Warring States","公元前475-221年。"),
        ("秦朝","Qin Dynasty","中国第一个统一王朝。"),
        ("汉朝","Han Dynasty","公元前202-公元220年。"),
        ("秦始皇","Qin Shi Huang","中国第一位皇帝。"),
        ("汉武帝","Emperor Wu of Han","汉朝鼎盛时期的皇帝。"),
        ("百家争鸣","Contention of Hundred Schools","春秋战国思想繁荣。"),
        ("商鞅变法","Shang Yang's Reforms","秦国变法图强。"),
        ("焚书坑儒","Burning of Books","秦始皇的文化政策。"),
        ("文景之治","Rule of Wen and Jing","汉初休养生息。"),
        ("丝绸之路","Silk Road","汉朝开辟的贸易路线。"),
        ("罢黜百家独尊儒术","Dismiss Hundred Schools","汉武帝的文化政策。"),
        ("王莽改制","Wang Mang's Reforms","新朝改革。"),
        ("光武中兴","Guangwu Restoration","东汉复兴。"),
        ("造纸术","Papermaking","汉代四大发明之一。"),
        ("张骞通西域","Zhang Qian's Mission","汉通西域。"),
    ]),
    ("中国史·魏晋至隋唐", [
        ("三国","Three Kingdoms","魏蜀吴鼎立。"),
        ("西晋","Western Jin","短暂统一。"),
        ("东晋","Eastern Jin","南渡政权。"),
        ("南北朝","Northern and Southern Dynasties","南北对峙。"),
        ("隋朝","Sui Dynasty","重新统一。"),
        ("唐朝","Tang Dynasty","公元618-907年。"),
        ("九品中正制","Nine-Rank System","魏晋选官制度。"),
        ("门阀士族","Aristocratic Families","魏晋士族势力。"),
        ("均田制","Equal-Field System","北魏至唐的土地制度。"),
        ("府兵制","Fubing System","兵农合一的军事制度。"),
        ("科举制","Imperial Examination","隋唐开始的选官制度。"),
        ("三省六部制","Three Departments Six Ministries","中央官制。"),
        ("贞观之治","Zhenguan Era","唐太宗时期。"),
        ("开元盛世","Kaiyuan Era","唐玄宗前期。"),
        ("安史之乱","An Lushan Rebellion","唐朝转折点。"),
        ("两税法","Two-Tax System","唐后期税制改革。"),
        ("藩镇割据","Regional Commands","唐后期军阀割据。"),
        ("佛教中国化","Sinicization of Buddhism","佛教本土化。"),
        ("唐诗","Tang Poetry","唐代文学高峰。"),
        ("丝绸之路贸易","Silk Road Trade","唐朝国际贸易。"),
    ]),
    ("中国史·宋元明清", [
        ("宋朝","Song Dynasty","公元960-1279年。"),
        ("元朝","Yuan Dynasty","蒙古族建立的王朝。"),
        ("明朝","Ming Dynasty","公元1368-1644年。"),
        ("清朝","Qing Dynasty","公元1644-1912年。"),
        ("杯酒释兵权","Dismissal of Generals","宋太祖集权。"),
        ("王安石变法","Wang Anshi's Reforms","北宋改革。"),
        ("靖康之变","Jingkang Incident","北宋灭亡。"),
        ("岳飞抗金","Yue Fei","南宋抗金名将。"),
        ("蒙古西征","Mongol Conquests","蒙古帝国扩张。"),
        ("行省制度","Provincial System","元朝行政制度。"),
        ("郑和下西洋","Zheng He's Voyages","明朝航海壮举。"),
        ("土木堡之变","Tumu Crisis","明朝军事危机。"),
        ("张居正改革","Zhang Juzheng's Reforms","明朝改革。"),
        ("一条鞭法","Single Whip Law","明朝税制改革。"),
        ("努尔哈赤","Nurhaci","后金建立者。"),
        ("康乾盛世","Kang-Qian Era","清朝鼎盛。"),
        ("摊丁入亩","Land Tax Reform","清朝税制改革。"),
        ("文字狱","Literary Inquisition","清朝思想控制。"),
        ("闭关锁国","Closed-Door Policy","清朝对外政策。"),
        ("鸦片战争","Opium War","1840年近代开端。"),
    ]),
    ("中国近现代史", [
        ("太平天国","Taiping Rebellion","农民起义运动。"),
        ("洋务运动","Self-Strengthening Movement","自强求富运动。"),
        ("戊戌变法","Hundred Days' Reform","维新变法。"),
        ("义和团运动","Boxer Rebellion","反帝爱国运动。"),
        ("辛亥革命","Xinhai Revolution","推翻帝制。"),
        ("中华民国","Republic of China","1912年建立。"),
        ("新文化运动","New Culture Movement","思想启蒙运动。"),
        ("五四运动","May Fourth Movement","反帝反封建运动。"),
        ("中国共产党成立","Founding of CPC","1921年。"),
        ("北伐战争","Northern Expedition","国共合作北伐。"),
        ("长征","Long March","红军战略转移。"),
        ("抗日战争","Anti-Japanese War","1937-1945年。"),
        ("解放战争","War of Liberation","1946-1949年。"),
        ("中华人民共和国成立","Founding of PRC","1949年10月1日。"),
        ("土地改革","Land Reform","农村土地制度变革。"),
        ("抗美援朝","Korean War","1950-1953年。"),
        ("三大改造","Three Transformations","社会主义改造。"),
        ("大跃进","Great Leap Forward","经济冒进运动。"),
        ("文化大革命","Cultural Revolution","1966-1976年。"),
        ("改革开放","Reform and Opening","1978年开始。"),
    ]),
    ("世界史·古代", [
        ("美索不达米亚","Mesopotamia","两河文明。"),
        ("古埃及","Ancient Egypt","尼罗河文明。"),
        ("古印度","Ancient India","印度河文明。"),
        ("古希腊","Ancient Greece","西方文明源头。"),
        ("古罗马","Ancient Rome","地中海文明。"),
        ("波斯帝国","Persian Empire","古代中东帝国。"),
        ("玛雅文明","Maya Civilization","中美洲文明。"),
        ("印加帝国","Inca Empire","南美洲文明。"),
        ("汉谟拉比法典","Code of Hammurabi","最早成文法典。"),
        ("雅典民主","Athenian Democracy","古代民主制度。"),
        ("罗马法","Roman Law","罗马法律体系。"),
        ("罗马帝国","Roman Empire","古代超级帝国。"),
        ("拜占庭帝国","Byzantine Empire","东罗马帝国。"),
        ("十字军东征","Crusades","中世纪宗教战争。"),
        ("黑死病","Black Death","中世纪瘟疫。"),
        ("文艺复兴","Renaissance","欧洲文化复兴。"),
        ("宗教改革","Reformation","基督教改革运动。"),
        ("地理大发现","Age of Discovery","大航海时代。"),
        ("启蒙运动","Enlightenment","理性思想运动。"),
        ("法国大革命","French Revolution","1789年革命。"),
    ]),
    ("世界史·近现代", [
        ("工业革命","Industrial Revolution","18世纪技术变革。"),
        ("美国独立战争","American Revolution","1776年独立。"),
        ("拿破仑战争","Napoleonic Wars","19世纪初欧洲战争。"),
        ("维也纳体系","Congress of Vienna","战后国际秩序。"),
        ("明治维新","Meiji Restoration","日本现代化。"),
        ("第一次世界大战","World War I","1914-1918年。"),
        ("俄国十月革命","October Revolution","1917年社会主义革命。"),
        ("凡尔赛体系","Versailles System","一战后国际秩序。"),
        ("大萧条","Great Depression","1929年经济危机。"),
        ("第二次世界大战","World War II","1939-1945年。"),
        ("冷战","Cold War","美苏对抗。"),
        ("非殖民化","Decolonization","殖民地独立运动。"),
        ("欧盟","European Union","欧洲一体化。"),
        ("全球化","Globalization","世界日益互联。"),
        ("信息革命","Information Revolution","数字技术变革。"),
    ]),
    ("史学方法", [
        ("史料","Historical Sources","历史研究的材料。"),
        ("一手史料","Primary Sources","原始史料。"),
        ("二手史料","Secondary Sources","后人整理的史料。"),
        ("史料批判","Source Criticism","对史料的考证。"),
        ("外部考证","External Criticism","史料真伪的考证。"),
        ("内部考证","Internal Criticism","史料内容的考证。"),
        ("编年体","Chronological Style","按时间记史。"),
        ("纪传体","Biographical Style","以人物记史。"),
        ("纪事本末体","Event-Centered Style","以事件记史。"),
        ("政书","Institutional History","典章制度史。"),
        ("方志","Local Gazetteer","地方志。"),
        ("谱牒","Genealogy","家族谱系。"),
        ("考古","Archaeology","物质遗存研究。"),
        ("金石学","Epigraphy","金石铭文研究。"),
        ("敦煌学","Dunhuang Studies","敦煌文献研究。"),
    ]),
    ("历史人物与事件", [
        ("黄帝","Yellow Emperor","中华民族始祖。"),
        ("孔子","Confucius","儒家创始人。"),
        ("秦始皇","Qin Shi Huang","统一中国。"),
        ("汉武帝","Emperor Wu","汉朝鼎盛。"),
        ("唐太宗","Emperor Taizong","贞观之治。"),
        ("成吉思汗","Genghis Khan","蒙古帝国。"),
        ("朱元璋","Zhu Yuanzhang","明朝建立者。"),
        ("康熙帝","Emperor Kangxi","清朝盛世。"),
        ("林则徐","Lin Zexu","禁烟运动。"),
        ("孙中山","Sun Yat-sen","辛亥革命领袖。"),
        ("毛泽东","Mao Zedong","新中国缔造者。"),
        ("邓小平","Deng Xiaoping","改革开放总设计师。"),
        ("亚历山大大帝","Alexander the Great","马其顿征服者。"),
        ("凯撒","Julius Caesar","罗马独裁者。"),
        ("拿破仑","Napoleon","法国皇帝。"),
        ("华盛顿","Washington","美国国父。"),
        ("林肯","Lincoln","废奴总统。"),
        ("罗斯福","Roosevelt","二战总统。"),
        ("甘地","Gandhi","印度独立领袖。"),
        ("曼德拉","Mandela","南非反种族隔离领袖。"),
    ]),
    ("专门史", [
        ("经济史","Economic History","经济发展史。"),
        ("思想史","Intellectual History","思想发展史。"),
        ("制度史","Institutional History","制度演变史。"),
        ("文化史","Cultural History","文化发展史。"),
        ("科技史","History of Science and Technology","科技发展史。"),
        ("军事史","Military History","战争军事史。"),
        ("外交史","Diplomatic History","对外关系史。"),
        ("民族史","Ethnic History","民族发展史。"),
        ("宗教史","Religious History","宗教发展史。"),
        ("艺术史","Art History","艺术发展史。"),
        ("人口史","Demographic History","人口变化史。"),
        ("环境史","Environmental History","人与环境关系史。"),
        ("性别史","Gender History","性别关系史。"),
        ("医学史","Medical History","医学发展史。"),
        ("教育史","Educational History","教育发展史。"),
    ]),
]
hist_disc = make_discipline("history", "历史学", "History", "his", "#5d4037",
    "研究人类社会发展过程及其规律的学科", hist_cats,
    formulas=[
        {"name": "碳14年代测定", "formula": "t = -8033 × ln(N/N₀)", "description": "N=当前碳14含量，N₀=初始碳14含量", "unit": "年"},
        {"name": "历史人口估算", "formula": "P(t) = P₀ × e^(rt)", "description": "指数增长模型估算历史人口", "unit": "人"},
    ],
    standards=[
        {"name": "中国历史年代标尺", "code": "夏商周断代工程", "description": "中国上古历史年代的标准框架。"},
        {"name": "历史档案著录规则", "code": "DA/T 18", "description": "中国档案行业的著录标准。"},
    ])
disciplines.append(hist_disc)
print(f"History: {len(hist_disc['glossary'])} terms")


# ============================================================
# 7. 理学 Natural Science
# ============================================================
sci_cats = [
    ("数学·基础", [
        ("集合","Set","数学基本对象。"),
        ("子集","Subset","集合的一部分。"),
        ("交集","Intersection","两集合的公共部分。"),
        ("并集","Union","两集合的合并。"),
        ("补集","Complement","全集中不属于某集的部分。"),
        ("映射","Mapping","集合间的对应关系。"),
        ("函数","Function","输入输出的对应。"),
        ("定义域","Domain","函数输入的范围。"),
        ("值域","Range","函数输出的范围。"),
        ("单射","Injection","一一对应的映射。"),
        ("满射","Surjection","覆盖值域的映射。"),
        ("双射","Bijection","一一对应且覆盖的映射。"),
        ("等价关系","Equivalence Relation","自反对称传递的关系。"),
        ("偏序关系","Partial Order","自反反对称传递的关系。"),
        ("基数","Cardinality","集合元素个数。"),
        ("序数","Ordinal Number","排序的位置。"),
        ("无穷","Infinity","无界限的概念。"),
        ("可数集","Countable Set","可与自然数对应的集合。"),
        ("不可数集","Uncountable Set","不可与自然数对应的集合。"),
        ("康托尔对角线","Cantor Diagonal","证明实数不可数的方法。"),
    ]),
    ("数学·微积分", [
        ("极限","Limit","函数趋近的值。"),
        ("连续","Continuity","函数无间断。"),
        ("导数","Derivative","瞬时变化率。"),
        ("微分","Differential","函数的线性近似。"),
        ("积分","Integral","函数曲线下的面积。"),
        ("定积分","Definite Integral","有确定上下限的积分。"),
        ("不定积分","Indefinite Integral","原函数。"),
        ("偏导数","Partial Derivative","多元函数对一个变量的导数。"),
        ("梯度","Gradient","偏导数组成的向量。"),
        ("散度","Divergence","向量场的源汇度。"),
        ("旋度","Curl","向量场的旋转度。"),
        ("泰勒级数","Taylor Series","函数的幂级数展开。"),
        ("傅里叶级数","Fourier Series","函数的三角级数展开。"),
        ("微分方程","Differential Equation","含导数的方程。"),
        ("常微分方程","ODE","一元函数的微分方程。"),
        ("偏微分方程","PDE","多元函数的微分方程。"),
        ("拉普拉斯变换","Laplace Transform","微分方程的变换求解法。"),
        ("中值定理","Mean Value Theorem","微分学基本定理。"),
        ("牛顿-莱布尼茨公式","Fundamental Theorem of Calculus","微分与积分的关系。"),
        ("链式法则","Chain Rule","复合函数求导法则。"),
    ]),
    ("数学·线性代数", [
        ("矩阵","Matrix","数表排列。"),
        ("行列式","Determinant","矩阵的标量函数。"),
        ("向量","Vector","有方向的量。"),
        ("线性组合","Linear Combination","向量的加权求和。"),
        ("线性无关","Linear Independence","向量间无线性关系。"),
        ("秩","Rank","线性无关的向量个数。"),
        ("特征值","Eigenvalue","矩阵的特征标量。"),
        ("特征向量","Eigenvector","矩阵的特征方向。"),
        ("对角化","Diagonalization","矩阵化为对角阵。"),
        ("正交","Orthogonality","向量垂直关系。"),
        ("正交矩阵","Orthogonal Matrix","列向量正交的矩阵。"),
        ("对称矩阵","Symmetric Matrix","转置等于自身的矩阵。"),
        ("逆矩阵","Inverse Matrix","乘积为单位阵的矩阵。"),
        ("转置","Transpose","行列互换。"),
        ("迹","Trace","对角元素之和。"),
        ("二次型","Quadratic Form","二次齐次多项式。"),
        ("奇异值分解","SVD","矩阵分解方法。"),
        ("最小二乘","Least Squares","最小化误差平方和。"),
        ("线性空间","Vector Space","向量的抽象空间。"),
        ("内积空间","Inner Product Space","有内积的线性空间。"),
    ]),
    ("数学·概率统计", [
        ("概率","Probability","事件发生的可能性。"),
        ("条件概率","Conditional Probability","给定条件下的概率。"),
        ("贝叶斯定理","Bayes' Theorem","更新概率的公式。"),
        ("随机变量","Random Variable","取值随机的变量。"),
        ("期望","Expectation","随机变量的平均值。"),
        ("方差","Variance","随机变量的离散程度。"),
        ("标准差","Standard Deviation","方差的平方根。"),
        ("协方差","Covariance","两个随机变量的关联。"),
        ("相关系数","Correlation Coefficient","标准化的协方差。"),
        ("大数定律","Law of Large Numbers","频率趋近概率。"),
        ("中心极限定理","Central Limit Theorem","样本均值的分布趋近正态。"),
        ("正态分布","Normal Distribution","钟形曲线分布。"),
        ("二项分布","Binomial Distribution","n次试验的成功次数。"),
        ("泊松分布","Poisson Distribution","稀有事件的计数。"),
        ("均匀分布","Uniform Distribution","等概率分布。"),
        ("指数分布","Exponential Distribution","寿命分布。"),
        ("假设检验","Hypothesis Testing","统计推断方法。"),
        ("p值","p-value","假设检验的显著性。"),
        ("置信区间","Confidence Interval","参数估计区间。"),
        ("最大似然估计","MLE","最大似然的参数估计。"),
    ]),
    ("物理学·力学", [
        ("牛顿第一定律","Newton's First Law","惯性定律。"),
        ("牛顿第二定律","Newton's Second Law","F=ma。"),
        ("牛顿第三定律","Newton's Third Law","作用力与反作用力。"),
        ("动量","Momentum","质量乘速度。"),
        ("角动量","Angular Momentum","转动动量。"),
        ("能量","Energy","做功的能力。"),
        ("动能","Kinetic Energy","运动的能量。"),
        ("势能","Potential Energy","位置的能量。"),
        ("功","Work","力乘位移。"),
        ("功率","Power","功的速率。"),
        ("力矩","Torque","力乘力臂。"),
        ("万有引力","Gravity","物体间的引力。"),
        ("摩擦力","Friction","接触面间的阻力。"),
        ("弹性","Elasticity","恢复形变的能力。"),
        ("简谐运动","Simple Harmonic Motion","正弦振动。"),
        ("波的叠加","Wave Superposition","波的干涉和衍射。"),
        ("多普勒效应","Doppler Effect","相对运动改变频率。"),
        ("流体力学","Fluid Mechanics","流体运动规律。"),
        ("伯努利原理","Bernoulli's Principle","流速与压强的关系。"),
        ("浮力","Buoyancy","流体对物体的上托力。"),
    ]),
    ("物理学·热学与电磁学", [
        ("温度","Temperature","热运动的度量。"),
        ("热量","Heat","热能的传递。"),
        ("热力学第一定律","First Law of Thermodynamics","能量守恒。"),
        ("热力学第二定律","Second Law of Thermodynamics","熵增定律。"),
        ("热力学第三定律","Third Law of Thermodynamics","绝对零度不可达。"),
        ("熵","Entropy","无序度的度量。"),
        ("卡诺循环","Carnot Cycle","理想热机循环。"),
        ("相变","Phase Transition","物质状态变化。"),
        ("电荷","Electric Charge","电的基本量。"),
        ("电场","Electric Field","电荷产生的场。"),
        ("电势","Electric Potential","电场的势能。"),
        ("电流","Electric Current","电荷的流动。"),
        ("电阻","Resistance","阻碍电流的能力。"),
        ("电容","Capacitance","储存电荷的能力。"),
        ("磁场","Magnetic Field","磁力作用的场。"),
        ("电磁感应","Electromagnetic Induction","变化的磁场产生电场。"),
        ("麦克斯韦方程组","Maxwell's Equations","电磁学基本方程。"),
        ("电磁波","Electromagnetic Wave","电磁场的传播。"),
        ("洛伦兹力","Lorentz Force","磁场对电荷的力。"),
        ("法拉第定律","Faraday's Law","电磁感应定律。"),
    ]),
    ("物理学·现代物理", [
        ("相对论","Relativity","爱因斯坦的理论。"),
        ("狭义相对论","Special Relativity","无引力的相对论。"),
        ("广义相对论","General Relativity","有引力的相对论。"),
        ("质能方程","E=mc²","质能等价。"),
        ("时间膨胀","Time Dilation","高速运动时间变慢。"),
        ("长度收缩","Length Contraction","高速运动长度变短。"),
        ("量子力学","Quantum Mechanics","微观世界的理论。"),
        ("波粒二象性","Wave-Particle Duality","粒子既是波又是粒子。"),
        ("不确定性原理","Uncertainty Principle","位置和动量不可同时确定。"),
        ("薛定谔方程","Schrödinger Equation","量子力学基本方程。"),
        ("量子叠加","Quantum Superposition","同时处于多个状态。"),
        ("量子纠缠","Quantum Entanglement","非定域关联。"),
        ("量子隧穿","Quantum Tunneling","穿越势垒。"),
        ("波函数","Wave Function","量子态的描述。"),
        ("测不准原理","Uncertainty Principle","海森堡不确定关系。"),
        ("原子结构","Atomic Structure","原子核和电子。"),
        ("核裂变","Nuclear Fission","重核分裂。"),
        ("核聚变","Nuclear Fusion","轻核聚合。"),
        ("标准模型","Standard Model","粒子物理基本理论。"),
        ("弦论","String Theory","以弦为基础的理论。"),
    ]),
    ("化学", [
        ("原子","Atom","物质基本单位。"),
        ("分子","Molecule","原子组合。"),
        ("元素","Element","同种质子数的原子。"),
        ("周期表","Periodic Table","元素分类表。"),
        ("化学键","Chemical Bond","原子间连接。"),
        ("共价键","Covalent Bond","共用电子对的键。"),
        ("离子键","Ionic Bond","正负离子间的键。"),
        ("金属键","Metallic Bond","金属原子间的键。"),
        ("氢键","Hydrogen Bond","氢原子的弱键。"),
        ("分子间力","Intermolecular Force","分子间的作用力。"),
        ("化学反应","Chemical Reaction","物质转化过程。"),
        ("氧化还原","Redox","电子转移反应。"),
        ("酸碱反应","Acid-Base Reaction","质子转移反应。"),
        ("催化剂","Catalyst","加速反应的物质。"),
        ("化学平衡","Chemical Equilibrium","正逆反应速率相等。"),
        ("勒夏特列原理","Le Chatelier's Principle","平衡移动方向。"),
        ("摩尔","Mole","物质的量的单位。"),
        ("浓度","Concentration","单位体积的溶质量。"),
        ("pH值","pH","酸碱度度量。"),
        ("有机化学","Organic Chemistry","碳化合物化学。"),
    ]),
    ("生物学", [
        ("细胞","Cell","生命基本单位。"),
        ("细胞膜","Cell Membrane","细胞外层结构。"),
        ("细胞核","Nucleus","遗传物质所在。"),
        ("线粒体","Mitochondria","能量工厂。"),
        ("叶绿体","Chloroplast","光合作用场所。"),
        ("DNA","DNA","遗传物质。"),
        ("RNA","RNA","遗传信息传递者。"),
        ("蛋白质","Protein","氨基酸组成的大分子。"),
        ("基因","Gene","遗传信息单位。"),
        ("基因组","Genome","全部遗传信息。"),
        ("转录","Transcription","DNA到RNA。"),
        ("翻译","Translation","RNA到蛋白质。"),
        ("基因表达","Gene Expression","基因信息转化为蛋白质。"),
        ("突变","Mutation","DNA序列变化。"),
        ("自然选择","Natural Selection","达尔文进化论核心。"),
        ("遗传","Heredity","亲代传递特征。"),
        ("变异","Variation","个体间的差异。"),
        ("物种","Species","生物分类基本单位。"),
        ("生态系统","Ecosystem","生物与环境的统一。"),
        ("生物多样性","Biodiversity","生物种类的多样性。"),
    ]),
    ("天文学与地球科学", [
        ("太阳系","Solar System","太阳和行星系统。"),
        ("恒星","Star","发光的天体。"),
        ("行星","Planet","绕恒星运行的天体。"),
        ("卫星","Satellite","绕行星运行的天体。"),
        ("银河系","Milky Way","我们所在的星系。"),
        ("星系","Galaxy","恒星系统。"),
        ("黑洞","Black Hole","光无法逃逸的天体。"),
        ("宇宙大爆炸","Big Bang","宇宙起源理论。"),
        ("板块构造","Plate Tectonics","地壳运动理论。"),
        ("地震","Earthquake","地壳震动。"),
        ("火山","Volcano","岩浆喷发。"),
        ("矿物","Mineral","天然无机固体。"),
        ("岩石","Rock","矿物集合体。"),
        ("大气层","Atmosphere","地球大气。"),
        ("海洋","Ocean","地球水体。"),
    ]),
]
sci_disc = make_discipline("science", "理学", "Natural Science", "sci", "#00838f",
    "数学、物理学、化学、生物学等自然科学的基础研究", sci_cats,
    formulas=[
        {"name": "牛顿第二定律", "formula": "F = ma", "description": "力=质量×加速度", "unit": "N"},
        {"name": "爱因斯坦质能方程", "formula": "E = mc²", "description": "能量=质量×光速²", "unit": "J"},
        {"name": "理想气体状态方程", "formula": "PV = nRT", "description": "压力×体积=物质的量×气体常数×温度", "unit": "Pa·m³"},
        {"name": "pH值", "formula": "pH = -log[H⁺]", "description": "氢离子浓度的负对数", "unit": "0-14"},
        {"name": "导数定义", "formula": "f'(x) = lim(h→0) [f(x+h) - f(x)] / h", "description": "函数在某点的瞬时变化率", "unit": "无量纲"},
        {"name": "正态分布", "formula": "f(x) = (1/(σ√2π)) × e^(-(x-μ)²/(2σ²))", "description": "μ=均值，σ=标准差", "unit": "概率密度"},
        {"name": "孟德尔遗传比", "formula": "F2 = 3:1 (单因子) / 9:3:3:1 (双因子)", "description": "杂交后代性状分离比", "unit": "比例"},
    ],
    standards=[
        {"name": "国际单位制", "code": "SI (2019)", "description": "国际通用的七基本单位制。"},
        {"name": "化学命名法", "code": "IUPAC", "description": "国际纯粹与应用化学联合会命名规则。"},
    ])
disciplines.append(sci_disc)
print(f"Science: {len(sci_disc['glossary'])} terms")


# ============================================================
# 8. 工学 Engineering
# ============================================================
eng_cats = [
    ("计算机科学", [
        ("算法","Algorithm","解决问题的步骤。"),
        ("数据结构","Data Structure","数据的组织方式。"),
        ("时间复杂度","Time Complexity","算法运行时间的增长。"),
        ("空间复杂度","Space Complexity","算法内存使用增长。"),
        ("递归","Recursion","函数调用自身。"),
        ("排序算法","Sorting Algorithm","排列数据的算法。"),
        ("搜索算法","Search Algorithm","查找数据的算法。"),
        ("动态规划","Dynamic Programming","最优子结构的求解。"),
        ("贪心算法","Greedy Algorithm","局部最优选择。"),
        ("分治法","Divide and Conquer","分解-解决-合并。"),
        ("回溯法","Backtracking","试错搜索。"),
        ("图论","Graph Theory","图结构的数学理论。"),
        ("树","Tree","层次结构的图。"),
        ("哈希表","Hash Table","键值映射结构。"),
        ("栈","Stack","后进先出结构。"),
        ("队列","Queue","先进先出结构。"),
        ("链表","Linked List","节点链接的结构。"),
        ("数组","Array","连续存储结构。"),
        ("面向对象","Object-Oriented","以对象为中心的编程范式。"),
        ("函数式编程","Functional Programming","以函数为中心的编程范式。"),
    ]),
    ("软件工程", [
        ("软件生命周期","Software Life Cycle","软件开发的全过程。"),
        ("需求分析","Requirements Analysis","确定软件需求。"),
        ("系统设计","System Design","软件架构设计。"),
        ("编码","Coding","编写程序代码。"),
        ("测试","Testing","验证软件质量。"),
        ("调试","Debugging","定位和修复错误。"),
        ("部署","Deployment","软件上线运行。"),
        ("维护","Maintenance","软件持续更新。"),
        ("敏捷开发","Agile Development","迭代增量开发。"),
        ("瀑布模型","Waterfall Model","顺序开发模型。"),
        ("DevOps","DevOps","开发运维一体化。"),
        ("CI/CD","CI/CD","持续集成持续部署。"),
        ("版本控制","Version Control","代码版本管理。"),
        ("代码审查","Code Review","同行评审代码。"),
        ("重构","Refactoring","改善代码结构。"),
        ("设计模式","Design Pattern","可复用的设计经验。"),
        ("微服务","Microservices","服务拆分架构。"),
        ("API","API","应用程序接口。"),
        ("REST","REST","表述性状态转移架构。"),
        ("数据库","Database","数据管理系统。"),
    ]),
    ("电子工程", [
        ("电路","Circuit","电流路径。"),
        ("电阻","Resistor","阻碍电流的元件。"),
        ("电容","Capacitor","储存电荷的元件。"),
        ("电感","Inductor","储存磁能的元件。"),
        ("二极管","Diode","单向导电元件。"),
        ("三极管","Transistor","放大开关元件。"),
        ("集成电路","Integrated Circuit","芯片。"),
        ("放大器","Amplifier","放大信号的电路。"),
        ("滤波器","Filter","选择频率的电路。"),
        ("振荡器","Oscillator","产生信号的电路。"),
        ("模数转换","ADC","模拟到数字的转换。"),
        ("数模转换","DAC","数字到模拟的转换。"),
        ("信号","Signal","携带信息的物理量。"),
        ("频谱","Spectrum","信号的频率成分。"),
        ("调制","Modulation","载波编码信息。"),
        ("解调","Demodulation","从载波恢复信息。"),
        ("天线","Antenna","发射接收电磁波。"),
        ("射频","RF","射频技术。"),
        ("嵌入式系统","Embedded System","专用计算机系统。"),
        ("FPGA","FPGA","现场可编程门阵列。"),
    ]),
    ("机械工程", [
        ("力学","Mechanics","研究力和运动的学科。"),
        ("材料力学","Strength of Materials","材料受力变形。"),
        ("应力","Stress","单位面积内力。"),
        ("应变","Strain","相对变形。"),
        ("弹性模量","Elastic Modulus","应力应变之比。"),
        ("屈服强度","Yield Strength","开始塑性变形的应力。"),
        ("抗拉强度","Tensile Strength","最大承受应力。"),
        ("疲劳","Fatigue","循环载荷下的破坏。"),
        ("断裂力学","Fracture Mechanics","裂纹扩展研究。"),
        ("有限元","FEM","数值分析方法。"),
        ("运动学","Kinematics","研究运动的几何性质。"),
        ("动力学","Dynamics","研究力与运动的关系。"),
        ("机构","Mechanism","传递运动的装置。"),
        ("齿轮","Gear","传动元件。"),
        ("轴承","Bearing","支撑旋转的元件。"),
        ("凸轮","Cam","转换运动的元件。"),
        ("连杆","Linkage","传递运动的杆件。"),
        ("摩擦","Friction","接触面间的阻力。"),
        ("润滑","Lubrication","减少摩擦的措施。"),
        ("公差","Tolerance","允许的尺寸偏差。"),
    ]),
    ("土木工程", [
        ("结构工程","Structural Engineering","建筑结构设计。"),
        ("混凝土","Concrete","水泥砂石混合材料。"),
        ("钢筋混凝土","Reinforced Concrete","混凝土中加钢筋。"),
        ("钢结构","Steel Structure","钢材建筑结构。"),
        ("地基","Foundation","建筑的基础。"),
        ("桩基","Pile Foundation","桩支撑的地基。"),
        ("梁","Beam","承受弯矩的构件。"),
        ("柱","Column","承受压力的构件。"),
        ("板","Slab","承受面荷载的构件。"),
        ("剪力墙","Shear Wall","抵抗水平力的墙体。"),
        ("抗震设计","Seismic Design","抗震的结构设计。"),
        ("荷载","Load","结构承受的力。"),
        ("恒载","Dead Load","结构自重。"),
        ("活载","Live Load","可变荷载。"),
        ("风载","Wind Load","风压力。"),
        ("地震作用","Seismic Action","地震对结构的影响。"),
        ("桥梁工程","Bridge Engineering","桥梁设计建造。"),
        ("隧道工程","Tunnel Engineering","隧道设计建造。"),
        ("道路工程","Road Engineering","道路设计建造。"),
        ("水工结构","Hydraulic Structure","水利工程结构。"),
    ]),
    ("化学工程", [
        ("化工热力学","Chemical Thermodynamics","化工中的热力学。"),
        ("传质","Mass Transfer","物质传递过程。"),
        ("传热","Heat Transfer","热量传递过程。"),
        ("动量传递","Momentum Transfer","流体动量传递。"),
        ("反应器","Reactor","化学反应设备。"),
        ("催化","Catalysis","加速反应的技术。"),
        ("分离过程","Separation Process","混合物分离。"),
        ("蒸馏","Distillation","利用沸点差分离。"),
        ("萃取","Extraction","利用溶解度差分离。"),
        ("结晶","Crystallization","从溶液析出晶体。"),
        ("吸收","Absorption","气体被液体吸收。"),
        ("吸附","Adsorption","物质附着于表面。"),
        ("膜分离","Membrane Separation","利用膜分离。"),
        ("流体力学","Fluid Mechanics","流体运动规律。"),
        ("化工工艺","Chemical Process","化工生产流程。"),
    ]),
    ("材料科学与工程", [
        ("材料","Material","制造物品的物质。"),
        ("金属材料","Metallic Material","金属及合金。"),
        ("陶瓷材料","Ceramic Material","无机非金属材料。"),
        ("高分子材料","Polymer Material","大分子材料。"),
        ("复合材料","Composite Material","多相组合材料。"),
        ("纳米材料","Nanomaterial","纳米尺度材料。"),
        ("晶体结构","Crystal Structure","原子排列方式。"),
        ("非晶态","Amorphous","无规则排列。"),
        ("相图","Phase Diagram","相平衡图。"),
        ("扩散","Diffusion","原子迁移。"),
        ("相变","Phase Transition","结构变化。"),
        ("塑性变形","Plastic Deformation","永久变形。"),
        ("弹性变形","Elastic Deformation","可恢复变形。"),
        ("强化机制","Strengthening Mechanism","提高强度的方法。"),
        ("腐蚀","Corrosion","材料退化。"),
    ]),
    ("控制工程", [
        ("控制系统","Control System","控制对象的系统。"),
        ("反馈","Feedback","输出返回输入。"),
        ("开环控制","Open-Loop Control","无反馈的控制。"),
        ("闭环控制","Closed-Loop Control","有反馈的控制。"),
        ("PID控制","PID Control","比例积分微分控制。"),
        ("传递函数","Transfer Function","输入输出的数学描述。"),
        ("状态空间","State Space","状态变量描述。"),
        ("稳定性","Stability","系统恢复平衡的能力。"),
        ("可控性","Controllability","状态可被控制。"),
        ("可观测性","Observability","状态可被观测。"),
        ("鲁棒性","Robustness","系统抗干扰能力。"),
        ("最优控制","Optimal Control","最优化性能的控制。"),
        ("自适应控制","Adaptive Control","参数自适应的控制。"),
        ("非线性控制","Nonlinear Control","非线性系统控制。"),
        ("数字控制","Digital Control","数字信号控制。"),
    ]),
    ("人工智能", [
        ("机器学习","Machine Learning","从数据学习的方法。"),
        ("深度学习","Deep Learning","多层神经网络学习。"),
        ("神经网络","Neural Network","模仿大脑的计算模型。"),
        ("卷积神经网络","CNN","图像处理的神经网络。"),
        ("循环神经网络","RNN","序列处理的神经网络。"),
        ("Transformer","Transformer","注意力机制的模型。"),
        ("自然语言处理","NLP","语言处理的AI技术。"),
        ("计算机视觉","Computer Vision","图像理解的AI技术。"),
        ("强化学习","Reinforcement Learning","通过奖励学习。"),
        ("生成对抗网络","GAN","生成模型的方法。"),
        ("大语言模型","LLM","大规模语言模型。"),
        ("提示工程","Prompt Engineering","设计提示的技术。"),
        ("迁移学习","Transfer Learning","跨任务知识迁移。"),
        ("联邦学习","Federated Learning","隐私保护的分布式学习。"),
        ("图神经网络","GNN","图结构的神经网络。"),
    ]),
    ("通信工程", [
        ("通信","Communication","信息传输。"),
        ("信道","Channel","信息传输的通道。"),
        ("带宽","Bandwidth","频率范围。"),
        ("信噪比","SNR","信号与噪声之比。"),
        ("香农定理","Shannon's Theorem","信道容量定理。"),
        ("编码","Coding","信息编码。"),
        ("解码","Decoding","信息解码。"),
        ("加密","Encryption","信息加密。"),
        ("多路复用","Multiplexing","多信号共用信道。"),
        ("蜂窝网络","Cellular Network","移动通信网络。"),
        ("5G","5G","第五代移动通信。"),
        ("光纤通信","Optical Fiber Communication","光纤传输。"),
        ("卫星通信","Satellite Communication","卫星中继通信。"),
        ("蓝牙","Bluetooth","短距离无线通信。"),
        ("WiFi","WiFi","无线局域网。"),
    ]),
    ("能源工程", [
        ("可再生能源","Renewable Energy","可再生的能源。"),
        ("太阳能","Solar Energy","太阳辐射能。"),
        ("风能","Wind Energy","风力发电。"),
        ("水能","Hydropower","水力发电。"),
        ("核能","Nuclear Energy","核裂变核聚变能。"),
        ("生物质能","Biomass Energy","生物质的能量。"),
        ("地热能","Geothermal Energy","地热资源。"),
        ("潮汐能","Tidal Energy","潮汐的能量。"),
        ("氢能","Hydrogen Energy","氢燃料。"),
        ("储能","Energy Storage","能量储存技术。"),
        ("电池","Battery","化学能储存。"),
        ("燃料电池","Fuel Cell","氢氧反应发电。"),
        ("智能电网","Smart Grid","智能化电力网络。"),
        ("碳中和","Carbon Neutrality","净零碳排放。"),
        ("能源效率","Energy Efficiency","能源利用效率。"),
    ]),
    ("生物工程", [
        ("基因工程","Genetic Engineering","基因操作技术。"),
        ("蛋白质工程","Protein Engineering","蛋白质设计改造。"),
        ("发酵工程","Fermentation Engineering","微生物发酵技术。"),
        ("细胞工程","Cell Engineering","细胞操作技术。"),
        ("酶工程","Enzyme Engineering","酶的改造应用。"),
        ("CRISPR","CRISPR","基因编辑技术。"),
        ("合成生物学","Synthetic Biology","合成生物系统。"),
        ("生物传感器","Biosensor","生物检测器件。"),
        ("生物材料","Biomaterial","医用生物材料。"),
        ("组织工程","Tissue Engineering","人工组织构建。"),
    ]),
]
eng_disc = make_discipline("engineering", "工学", "Engineering", "eng", "#455a64",
    "应用科学原理设计和建造结构、机器、系统的学科", eng_cats,
    formulas=[
        {"name": "欧姆定律", "formula": "V = IR", "description": "电压=电流×电阻", "unit": "V"},
        {"name": "功率", "formula": "P = VI = I²R = V²/R", "description": "电功率计算", "unit": "W"},
        {"name": "胡克定律", "formula": "σ = Eε", "description": "应力=弹性模量×应变", "unit": "Pa"},
        {"name": "PID控制律", "formula": "u(t) = Kp·e(t) + Ki·∫e(t)dt + Kd·de(t)/dt", "description": "比例+积分+微分", "unit": "控制量"},
        {"name": "傅里叶变换", "formula": "F(ω) = ∫f(t)e^(-iωt)dt", "description": "时域到频域的转换", "unit": "频谱"},
        {"name": "雷诺数", "formula": "Re = ρvL/μ", "description": "惯性力/粘性力，判断流动状态", "unit": "无量纲"},
    ],
    standards=[
        {"name": "机械制图标准", "code": "GB/T 4458", "description": "中国机械制图国家标准。"},
        {"name": "电气安全标准", "code": "IEC 61010", "description": "国际电气测量安全标准。"},
    ])
disciplines.append(eng_disc)
print(f"Engineering: {len(eng_disc['glossary'])} terms")


# Save intermediate
with open(os.path.join(BASE, 'gen_disciplines_part2.json'), 'w', encoding='utf-8') as f:
    json.dump(disciplines, f, ensure_ascii=False)
print(f"\nPart 2 done: {len(disciplines)} disciplines")
for d in disciplines:
    print(f"  {d['name']}: {len(d['glossary'])} terms")
